// All Fintutto Ecosystem Apps - definitions, features, pricing, and URLs

const APP_URLS = {
  portal: import.meta.env.VITE_APP_URL_PORTAL || 'https://portal.fintutto.cloud',
  vermietify: import.meta.env.VITE_APP_URL_VERMIETIFY || 'https://vermietify.fintutto.cloud',
  mieter: import.meta.env.VITE_APP_URL_MIETER || 'https://mieter.fintutto.de',
  hausmeister: import.meta.env.VITE_APP_URL_HAUSMEISTER || 'https://hausmeisterpro.fintutto.cloud',
  ablesung: import.meta.env.VITE_APP_URL_ABLESUNG || 'https://zaehler.fintutto.cloud',
  bescheidboxer: import.meta.env.VITE_APP_URL_BESCHEIDBOXER || 'https://app.bescheidboxer.de',
  financialCompass: import.meta.env.VITE_APP_URL_FINANCIAL_COMPASS || 'https://fintutto.cloud',
  adminHub: import.meta.env.VITE_APP_URL_ADMIN_HUB || 'https://admin.fintutto.cloud',
  financeCoach: import.meta.env.VITE_APP_URL_FINANCE_COACH || 'https://finance-coach.fintutto.cloud',
  financeMentor: import.meta.env.VITE_APP_URL_FINANCE_MENTOR || 'https://finance-mentor.fintutto.cloud',
  arbeitslosPortal: import.meta.env.VITE_APP_URL_ARBEITSLOS_PORTAL || 'https://arbeitslos-portal.fintutto.cloud',
  aiGuide: import.meta.env.VITE_APP_URL_AI_GUIDE || 'https://ai-guide.fintutto.cloud',
  lernApp: import.meta.env.VITE_APP_URL_LERN_APP || 'https://lernen.fintutto.cloud',
  guideTranslatorSales: import.meta.env.VITE_APP_URL_GT_SALES || 'https://sales.translator.fintutto.cloud',
  consumerGuideTranslator: import.meta.env.VITE_APP_URL_GT_CONSUMER || 'https://consumer.guidetranslator.com',
  bizPortal: import.meta.env.VITE_APP_URL_BIZ_PORTAL || 'https://biz.fintutto.cloud',
  fintuttoCloud: import.meta.env.VITE_APP_URL_FINTUTTO_CLOUD || 'https://www.fintutto.cloud',
}

export interface AppInfo {
  id: string
  name: string
  tagline: string
  description: string
  icon: string // emoji
  color: string // tailwind gradient class
  url: string
  registerUrl: string
  features: string[]
  pricing: {
    free: string
    plans: { name: string; price: string; period: string; highlight?: boolean }[]
  }
  stats: { label: string; value: string }[]
  targetAudience: string
  badge?: string
  category: 'immobilien' | 'finanzen' | 'lifestyle' | 'sales' | 'bildung' | 'karriere'
}

export const FINTUTTO_APPS: AppInfo[] = [
  {
    id: 'portal',
    name: 'Fintutto Portal',
    tagline: 'Alle Mietrecht-Tools an einem Ort',
    description:
      '27 professionelle Tools: Rechner für Vermieter, Checker für Mieter und rechtssichere Formulare für alle. Basierend auf aktuellem deutschen Mietrecht.',
    icon: '✨',
    color: 'from-purple-600 to-indigo-600',
    url: APP_URLS.portal,
    registerUrl: `${APP_URLS.portal}/register`,
    features: [
      '7 Vermieter-Rechner (Kaution, Rendite, Kaufnebenkosten...)',
      '10 Mieter-Checker (Mietpreisbremse, Kündigung, Nebenkosten...)',
      '5 rechtssichere Formulare (Mietvertrag, Übergabeprotokoll...)',
      'KI-Assistent für Mietrecht-Fragen',
      'PDF-Export aller Berechnungen',
      'Credit-basiertes System – fair & flexibel',
    ],
    pricing: {
      free: '3 Credits/Monat kostenlos',
      plans: [
        { name: 'Mieter', price: '4,99', period: '/Monat' },
        { name: 'Vermieter', price: '7,99', period: '/Monat' },
        { name: 'Kombi Pro', price: '11,99', period: '/Monat', highlight: true },
        { name: 'Unlimited', price: '19,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Tools', value: '27' },
      { label: 'Bundesländer', value: '16' },
      { label: 'DSGVO', value: '100%' },
    ],
    targetAudience: 'Mieter & Vermieter',
    badge: 'Neu',
    category: 'finanzen',
  },
  {
    id: 'translator',
    name: 'Uebersetzer',
    tagline: 'Die meistgenutzte App im Fintutto-Oekosystem',
    description: '22 Sprachen, Echtzeit-Uebersetzung, Google Cloud Text-to-Speech, Spracheingabe, Live-Sessions und Uebersetzungsverlauf. Komplett kostenlos.',
    icon: '🌐',
    color: 'from-sky-500 to-blue-600',
    url: '/uebersetzer',
    registerUrl: 'https://translator.fintutto.cloud',
    features: ['22 Sprachen unterstuetzt', 'Google Cloud Text-to-Speech (Neural2 & Chirp 3 HD)', 'Spracheingabe per Mikrofon', 'Uebersetzungsverlauf', 'Echtzeit-Uebersetzung', 'Live-Sessions fuer Gruppen', 'Offline-Modus (mobile App)', 'Clipboard-Integration'],
    pricing: { free: 'Komplett kostenlos', plans: [{ name: 'Free', price: '0', period: 'fuer immer', highlight: true }] },
    stats: [{ label: 'Sprachen', value: '22' }, { label: 'TTS', value: 'Cloud' }, { label: 'Preis', value: 'Gratis' }],
    targetAudience: 'Alle Nutzer',
    badge: 'Beliebteste App',
    category: 'lifestyle',
  },
  {
    id: 'vermietify',
    name: 'Vermietify',
    tagline: 'Die komplette Immobilienverwaltung',
    description:
      'Gebäude, Mieter, Verträge, Zahlungen, Dokumente – alles in einer App. Mit 69 Formularen, automatischer Nebenkostenabrechnung und KI-Assistent.',
    icon: '🏠',
    color: 'from-blue-600 to-cyan-500',
    url: APP_URLS.vermietify,
    registerUrl: `${APP_URLS.vermietify}/register`,
    features: [
      'Gebäude- & Einheitenverwaltung',
      'Mieterverwaltung mit Vertragsdaten',
      '69 Formulare & Vorlagen',
      'Automatische Nebenkostenabrechnung',
      'Zahlungsübersicht & Mahnwesen',
      'KI-Assistent für Vermieter-Fragen',
      'Dokumenten-Management (Upload & Archiv)',
    ],
    pricing: {
      free: '3 Credits/Monat kostenlos',
      plans: [
        { name: 'Starter', price: '2,99', period: '/Monat' },
        { name: 'Pro', price: '7,99', period: '/Monat', highlight: true },
        { name: 'Unlimited', price: '14,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Formulare', value: '69' },
      { label: 'Features', value: '50+' },
      { label: 'KI-Assistent', value: 'Ja' },
    ],
    targetAudience: 'Vermieter & Hausverwaltungen',
    category: 'immobilien',
  },
  {
    id: 'mieter',
    name: 'Mieter-App',
    tagline: 'Dein digitaler Mieter-Assistent',
    description:
      'Mängel melden, Zähler ablesen, Dokumente anfordern und direkt mit der Hausverwaltung chatten. Mit 10 Rechts-Checkern für deine Mietrechte.',
    icon: '🔑',
    color: 'from-green-600 to-emerald-500',
    url: APP_URLS.mieter,
    registerUrl: `${APP_URLS.mieter}/register`,
    features: [
      'Mangel melden mit Foto-Upload',
      'Zählerstand digital ablesen',
      'Dokumente anfordern (Bescheinigungen etc.)',
      'Chat mit Hausverwaltung',
      'Hausordnung & Notfallkontakte',
      '10 Mietrecht-Checker (Mietpreisbremse, Kündigung...)',
      'KI-Assistent für Mieter-Fragen',
    ],
    pricing: {
      free: '1 Check/Monat kostenlos',
      plans: [
        { name: 'Basic', price: '0,99', period: '/Monat' },
        { name: 'Premium', price: '3,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Checker', value: '10' },
      { label: 'Chat', value: 'Live' },
      { label: 'KI', value: 'Ja' },
    ],
    targetAudience: 'Mieter',
    category: 'immobilien',
  },
  {
    id: 'hausmeister',
    name: 'HausmeisterPro',
    tagline: 'Facility Management leicht gemacht',
    description:
      'Aufgaben verwalten, Belege fotografieren, mit Eigentümern kommunizieren. Die digitale Zentrale für Hausmeister und Facility Manager.',
    icon: '🔧',
    color: 'from-orange-500 to-amber-500',
    url: APP_URLS.hausmeister,
    registerUrl: `${APP_URLS.hausmeister}/register`,
    features: [
      'Aufgabenverwaltung (erstellen, zuweisen, tracken)',
      'Belegerfassung mit Foto-Upload',
      'Chat mit Eigentümer / Hausverwaltung',
      'Status-Tracking für alle Aufträge',
      'Materialverwaltung & Bestellungen',
      'Anbindung an Mieter-App (Mängelmeldungen)',
    ],
    pricing: {
      free: 'Grundfunktionen kostenlos',
      plans: [
        { name: 'Pro', price: '4,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Aufgaben', value: '∞' },
      { label: 'Chat', value: 'Live' },
      { label: 'Belege', value: 'Foto' },
    ],
    targetAudience: 'Hausmeister & Facility Manager',
    category: 'immobilien',
  },
  {
    id: 'ablesung',
    name: 'Ablesung',
    tagline: 'Zählerstand-Erfassung digitalisiert',
    description:
      'Strom, Gas, Wasser, Heizung – alle Zählerstände digital erfassen, tracken und analysieren. Mit Verbrauchsanalyse und CSV-Import.',
    icon: '📊',
    color: 'from-teal-500 to-cyan-500',
    url: APP_URLS.ablesung,
    registerUrl: `${APP_URLS.ablesung}/register`,
    features: [
      'Digitale Zählerstand-Erfassung',
      'Gebäude- & Einheitenverwaltung',
      'Verbrauchsanalyse über Zeiträume',
      'CSV-Import für historische Daten',
      'OCR/Kamera-Erfassung (geplant)',
      'Anbindung an Vermietify (gemeinsame Daten)',
    ],
    pricing: {
      free: 'Grundfunktionen kostenlos',
      plans: [
        { name: 'Pro', price: '2,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Zählertypen', value: '4+' },
      { label: 'Analyse', value: 'Ja' },
      { label: 'Import', value: 'CSV' },
    ],
    targetAudience: 'Vermieter & Hausverwaltungen',
    category: 'immobilien',
  },
  {
    id: 'bescheidboxer',
    name: 'BescheidBoxer',
    tagline: 'Bescheide verstehen & anfechten',
    description:
      'Lade deinen Bescheid hoch und lass ihn analysieren. Grundsteuer, Nebenkosten, Betriebskostenabrechnungen – finde versteckte Fehler und spare Geld.',
    icon: '🥊',
    color: 'from-red-500 to-rose-500',
    url: APP_URLS.bescheidboxer,
    registerUrl: `${APP_URLS.bescheidboxer}/register`,
    features: [
      'Bescheid-Upload & KI-Analyse',
      'Grundsteuerbescheid prüfen',
      'Nebenkostenabrechnung prüfen',
      'Fehler automatisch erkennen',
      'Widerspruch-Vorlagen generieren',
      'Ersparnis-Rechner: So viel kannst du sparen',
    ],
    pricing: {
      free: '1 Analyse/Monat kostenlos',
      plans: [
        { name: 'Basic', price: '2,99', period: '/Monat' },
        { name: 'Pro', price: '7,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Bescheid-Typen', value: '5+' },
      { label: 'KI-Analyse', value: 'Ja' },
      { label: 'Widerspruch', value: 'Auto' },
    ],
    targetAudience: 'Mieter & Eigentümer',
    badge: 'Neu',
    category: 'finanzen',
  },
  {
    id: 'vermieter-portal',
    name: 'Vermieter-Portal',
    tagline: 'Rechner & Formulare für Vermieter',
    description: 'Spezialisierte Tools für Vermieter: Mietrendite, Eigenkapital, Kaufnebenkosten-Rechner und rechtssichere Formulare.',
    icon: '🏢',
    color: 'from-indigo-600 to-blue-500',
    url: '/rechner',
    registerUrl: '/register',
    features: ['7 Vermieter-Rechner', '5 rechtssichere Formulare', 'Mietrendite-Berechnung', 'Kaufnebenkosten-Kalkulation', 'Eigenkapital-Planung'],
    pricing: { free: 'Alle Rechner kostenlos', plans: [{ name: 'Pro', price: '5,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Rechner', value: '7' }, { label: 'Formulare', value: '5' }, { label: 'Kostenlos', value: 'Ja' }],
    targetAudience: 'Vermieter & Eigentümer',
    category: 'immobilien',
  },
  {
    id: 'admin-hub',
    name: 'Admin-Hub',
    tagline: 'Zentrale Verwaltung aller Fintutto Apps',
    description: 'Benutzerverwaltung, Organisationen, App-übergreifende Einstellungen und Berechtigungen.',
    icon: '⚙️',
    color: 'from-slate-600 to-zinc-500',
    url: APP_URLS.adminHub,
    registerUrl: `${APP_URLS.adminHub}/register`,
    features: ['Benutzerverwaltung & Rollen', 'Organisationsverwaltung', 'App-übergreifende Einstellungen', 'Lizenz- & Aboverwaltung', 'Audit-Log & Aktivitätsprotokoll'],
    pricing: { free: 'Grundfunktionen inklusive', plans: [{ name: 'Team', price: '9,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Apps', value: '24' }, { label: 'Rollen', value: '∞' }, { label: 'SSO', value: 'Ja' }],
    targetAudience: 'Hausverwaltungen & Teams',
    category: 'finanzen',
  },
  {
    id: 'financial-compass',
    name: 'Financial Compass',
    tagline: 'Deine Finanzübersicht auf einen Blick',
    description: 'Einnahmen, Ausgaben, Steuern – alle Finanzdaten zusammengeführt. Mit automatischer Buchhaltung und Steuerreports.',
    icon: '🧭',
    color: 'from-violet-600 to-purple-500',
    url: APP_URLS.financialCompass,
    registerUrl: `${APP_URLS.financialCompass}/register`,
    features: ['Einnahmen- & Ausgabenübersicht', 'Automatische Kategorisierung', 'Steuerreports (Anlage V)', 'Mieteinnahmen-Tracking', 'Export für Steuerberater'],
    pricing: { free: 'Grundübersicht kostenlos', plans: [{ name: 'Plus', price: '4,99', period: '/Monat' }, { name: 'Pro', price: '9,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Reports', value: '10+' }, { label: 'Export', value: 'CSV/PDF' }, { label: 'Steuer', value: 'Auto' }],
    targetAudience: 'Vermieter & Eigentümer',
    category: 'finanzen',
  },
  {
    id: 'fittutto',
    name: 'FitTutto',
    tagline: 'Dein persoenlicher Fitness-Begleiter',
    description:
      'Trainingsplaene, Workout-Tracking, Ernaehrungstracking, Koerpermessungen und KI-Coaching. 250+ Uebungen, Set-by-Set Logging, Makro-Tracker und mehr.',
    icon: '💪',
    color: 'from-orange-500 to-red-500',
    url: '/fittutto',
    registerUrl: '/register',
    features: [
      'Individuelle Trainingsplaene erstellen & generieren',
      'Workout-Tracking mit 250+ Uebungen',
      'Ernaehrungstracking mit Makro-Zielen',
      'Koerper-Tracking (Gewicht, Umfaenge, KFA)',
      'KI-Fitness-Coach fuer personalisierte Tipps',
      'Persoenliche Rekorde & Streak-Tracking',
    ],
    pricing: {
      free: 'Grundfunktionen kostenlos',
      plans: [
        { name: 'Speichern', price: '2,99', period: '/Monat' },
        { name: 'Basic', price: '4,99', period: '/Monat', highlight: true },
        { name: 'Premium', price: '9,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Uebungen', value: '250+' },
      { label: 'KI-Coach', value: 'Ja' },
      { label: 'Tracking', value: '360\u00B0' },
    ],
    targetAudience: 'Fitness-Enthusiasten',
    badge: 'Neu',
    category: 'lifestyle',
  },
  {
    id: 'pflanzen-manager',
    name: 'Pflanzen-Manager',
    tagline: 'Zimmerpflanzen-Pflege leicht gemacht',
    description: 'Gießerinnerungen, Pflanzenprofile, Standort-Tracking und Pflege-Tipps.',
    icon: '🌱',
    color: 'from-green-500 to-lime-500',
    url: 'https://zimmerpflanze.fintutto.cloud',
    registerUrl: 'https://zimmerpflanze.fintutto.cloud/register',
    features: ['Pflanzenprofile mit Fotos', 'Gieß-Erinnerungen', 'Standort-Tracking', 'Pflege-Tipps & Anleitungen', 'Wachstums-Verlauf'],
    pricing: { free: 'Bis 5 Pflanzen kostenlos', plans: [{ name: 'Unlimited', price: '1,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Pflanzen', value: '∞' }, { label: 'Tipps', value: '200+' }, { label: 'Erinnerung', value: 'Push' }],
    targetAudience: 'Pflanzenliebhaber',
    category: 'lifestyle',
  },
  {
    id: 'luggagex',
    name: 'LuggageX',
    tagline: 'Gepäck-Tracking & Reise-Checklisten',
    description: 'Reisegepäck digital verwalten: Packlisten, Gewichts-Tracker und Versicherungsübersicht.',
    icon: '🧳',
    color: 'from-amber-500 to-orange-500',
    url: 'https://luggagex.fintutto.cloud',
    registerUrl: 'https://luggagex.fintutto.cloud/register',
    features: ['Digitale Packlisten', 'Gewichts-Tracker pro Koffer', 'Reise-Checklisten', 'Gepäck-Versicherung', 'Reise-Verlauf'],
    pricing: { free: 'Grundfunktionen kostenlos', plans: [{ name: 'Pro', price: '1,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Listen', value: '∞' }, { label: 'Reisen', value: '∞' }, { label: 'Gewicht', value: 'Auto' }],
    targetAudience: 'Reisende',
    category: 'lifestyle',
  },
  {
    id: 'guidetranslator',
    name: 'GuideTranslator',
    tagline: 'Übersetzer-Tool für Kreuzfahrtschiffe',
    description: 'Spezialisiertes Übersetzungstool für Reiseleiter und Guides auf Kreuzfahrtschiffen.',
    icon: '🚢',
    color: 'from-cyan-600 to-teal-500',
    url: 'https://app.guidetranslator.com',
    registerUrl: 'https://app.guidetranslator.com/register',
    features: ['Branchenspezifische Phrasen', 'Kreuzfahrt-Terminologie', 'Offline-Modus verfügbar', 'Mehrsprachige Durchsagen', 'Gäste-Kommunikation'],
    pricing: { free: 'Demo verfügbar', plans: [{ name: 'Pro', price: '9,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Sprachen', value: '15+' }, { label: 'Phrasen', value: '1000+' }, { label: 'Offline', value: 'Ja' }],
    targetAudience: 'Reiseleiter & Guides',
    category: 'sales',
  },
  {
    id: 'command-center',
    name: 'Command Center',
    tagline: 'Fintutto Steuerungszentrale',
    description: 'Überblick über alle Fintutto-Apps, Nutzerstatistiken und System-Health.',
    icon: '🎛️',
    color: 'from-gray-700 to-slate-600',
    url: 'https://commander.fintutto.cloud',
    registerUrl: 'https://commander.fintutto.cloud',
    features: ['App-Status Dashboard', 'Nutzerstatistiken', 'Deployment-Übersicht', 'System-Health Monitoring', 'Cross-App Analytics'],
    pricing: { free: 'Nur für Admins', plans: [{ name: 'Admin', price: '0', period: 'inklusive', highlight: true }] },
    stats: [{ label: 'Apps', value: '24' }, { label: 'Uptime', value: '99.9%' }, { label: 'Analytics', value: 'Echtzeit' }],
    targetAudience: 'Administratoren',
    category: 'sales',
  },
  // --- Neue Apps ---
  {
    id: 'finance-coach',
    name: 'Finance Coach',
    tagline: 'Dein persönlicher Finanz-Coach',
    description: 'KI-gestütztes Finanz-Coaching: Budgetplanung, Sparstrategien, Schuldenabbau und individuelle Finanzberatung für jeden Lebensabschnitt.',
    icon: '💰',
    color: 'from-emerald-600 to-teal-500',
    url: APP_URLS.financeCoach,
    registerUrl: `${APP_URLS.financeCoach}/register`,
    features: [
      'KI-Finanz-Coaching',
      'Budgetplanung & Sparziele',
      'Schuldenabbau-Strategien',
      'Monatliche Finanzberichte',
      'Personalisierte Spartipps',
    ],
    pricing: {
      free: 'Basis-Coaching kostenlos',
      plans: [
        { name: 'Basic', price: '3,99', period: '/Monat' },
        { name: 'Pro', price: '7,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Strategien', value: '50+' },
      { label: 'KI-Coach', value: 'Ja' },
      { label: 'Reports', value: 'Monatlich' },
    ],
    targetAudience: 'Alle Nutzer',
    badge: 'Neu',
    category: 'finanzen',
  },
  {
    id: 'finance-mentor',
    name: 'Finance Mentor',
    tagline: 'Finanzwissen für Fortgeschrittene',
    description: 'Investment-Strategien, Vermögensaufbau, Steueroptimierung und Altersvorsorge. Mentoring-Programm mit KI-Unterstützung.',
    icon: '📈',
    color: 'from-blue-700 to-indigo-600',
    url: APP_URLS.financeMentor,
    registerUrl: `${APP_URLS.financeMentor}/register`,
    features: [
      'Investment-Strategien & ETF-Planung',
      'Vermögensaufbau-Roadmap',
      'Steueroptimierung-Tipps',
      'Altersvorsorge-Rechner',
      'KI-Mentor für Finanzfragen',
    ],
    pricing: {
      free: 'Grundkurse kostenlos',
      plans: [
        { name: 'Mentor', price: '9,99', period: '/Monat', highlight: true },
        { name: 'VIP', price: '19,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Kurse', value: '30+' },
      { label: 'Strategien', value: '25+' },
      { label: 'KI-Mentor', value: 'Ja' },
    ],
    targetAudience: 'Investoren & Sparer',
    category: 'finanzen',
  },
  {
    id: 'arbeitslos-portal',
    name: 'Arbeitslos-Portal',
    tagline: 'Unterstützung bei Arbeitslosigkeit',
    description: 'Antragshelfer für ALG I & II, Widerspruch-Vorlagen, Bewerbungshilfe und Rechtsinfo. Alles was du brauchst, wenn du arbeitslos wirst.',
    icon: '🤝',
    color: 'from-amber-600 to-orange-500',
    url: APP_URLS.arbeitslosPortal,
    registerUrl: `${APP_URLS.arbeitslosPortal}/register`,
    features: [
      'ALG-I & ALG-II Antragshelfer',
      'Widerspruch-Vorlagen für Bescheide',
      'Bewerbungsvorlagen & Tipps',
      'Rechtsinfo & Fristen-Tracker',
      'Umschulungs- & Weiterbildungsfinder',
    ],
    pricing: {
      free: 'Komplett kostenlos',
      plans: [{ name: 'Free', price: '0', period: 'für immer', highlight: true }],
    },
    stats: [
      { label: 'Vorlagen', value: '40+' },
      { label: 'Anträge', value: 'ALG I/II' },
      { label: 'Preis', value: 'Gratis' },
    ],
    targetAudience: 'Arbeitssuchende',
    badge: 'Kostenlos',
    category: 'karriere',
  },
  {
    id: 'ai-guide',
    name: 'AI Guide',
    tagline: 'Dein KI-Assistent für alles',
    description: 'Universeller KI-Assistent: Texte schreiben, Fragen beantworten, Dokumente analysieren und kreative Aufgaben lösen – powered by Claude.',
    icon: '🤖',
    color: 'from-violet-600 to-fuchsia-500',
    url: APP_URLS.aiGuide,
    registerUrl: `${APP_URLS.aiGuide}/register`,
    features: [
      'KI-Chat für alle Fragen',
      'Dokument-Upload & Analyse',
      'Texte schreiben & optimieren',
      'Mehrsprachige Unterstützung',
      'Powered by Claude AI',
    ],
    pricing: {
      free: '10 Anfragen/Tag kostenlos',
      plans: [
        { name: 'Plus', price: '4,99', period: '/Monat' },
        { name: 'Pro', price: '9,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'KI-Modell', value: 'Claude' },
      { label: 'Sprachen', value: '20+' },
      { label: 'Upload', value: 'PDF/DOC' },
    ],
    targetAudience: 'Alle Nutzer',
    badge: 'Neu',
    category: 'bildung',
  },
  {
    id: 'lern-app',
    name: 'LernApp',
    tagline: 'Lernen mit KI-Unterstützung',
    description: 'Intelligente Lernplattform: Karteikarten, Quizze, Lernpläne und KI-Tutor. Für Schule, Studium und Weiterbildung.',
    icon: '📚',
    color: 'from-cyan-600 to-blue-500',
    url: APP_URLS.lernApp,
    registerUrl: `${APP_URLS.lernApp}/register`,
    features: [
      'KI-generierte Karteikarten',
      'Adaptive Quizze & Tests',
      'Personalisierte Lernpläne',
      'KI-Tutor für Erklärungen',
      'Fortschritts-Tracking & Statistiken',
      'Spaced Repetition System',
    ],
    pricing: {
      free: 'Basis-Funktionen kostenlos',
      plans: [
        { name: 'Schüler', price: '2,99', period: '/Monat' },
        { name: 'Student', price: '4,99', period: '/Monat', highlight: true },
        { name: 'Pro', price: '9,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Fächer', value: '50+' },
      { label: 'KI-Tutor', value: 'Ja' },
      { label: 'Karteikarten', value: '∞' },
    ],
    targetAudience: 'Schüler, Studenten & Lernende',
    badge: 'Neu',
    category: 'bildung',
  },
  {
    id: 'guidetranslator-sales',
    name: 'GuideTranslator Sales',
    tagline: 'B2B-Vertrieb für GuideTranslator',
    description: 'Vertriebsplattform für GuideTranslator: Firmenkunden verwalten, Lizenzen verkaufen, Demos planen und Umsätze tracken.',
    icon: '💼',
    color: 'from-indigo-600 to-violet-500',
    url: APP_URLS.guideTranslatorSales,
    registerUrl: `${APP_URLS.guideTranslatorSales}/register`,
    features: [
      'CRM für Kreuzfahrt-Reedereien',
      'Lizenz-Management',
      'Demo-Terminplanung',
      'Umsatz-Dashboard',
      'Vertrags-Verwaltung',
    ],
    pricing: {
      free: 'Nur für Sales-Team',
      plans: [{ name: 'Sales', price: '0', period: 'intern', highlight: true }],
    },
    stats: [
      { label: 'Kunden', value: 'B2B' },
      { label: 'Lizenzen', value: '∞' },
      { label: 'CRM', value: 'Ja' },
    ],
    targetAudience: 'Sales-Team & Partner',
    category: 'sales',
  },
  {
    id: 'consumer-guidetranslator',
    name: 'GuideTranslator Consumer',
    tagline: 'Übersetzer für Kreuzfahrt-Gäste',
    description: 'Die Consumer-Version von GuideTranslator: Für Passagiere auf Kreuzfahrtschiffen. Menüs, Durchsagen und Landausflüge übersetzen.',
    icon: '🛳️',
    color: 'from-teal-500 to-emerald-500',
    url: APP_URLS.consumerGuideTranslator,
    registerUrl: `${APP_URLS.consumerGuideTranslator}/register`,
    features: [
      'Menü-Übersetzung per Kamera',
      'Durchsagen verstehen',
      'Landausflug-Infos übersetzen',
      'Offline-Phrasenbuch',
      'Schiffsspezifisches Vokabular',
    ],
    pricing: {
      free: 'Basis-Phrasen kostenlos',
      plans: [
        { name: 'Reise', price: '4,99', period: '/Reise' },
        { name: 'Jahresabo', price: '14,99', period: '/Jahr', highlight: true },
      ],
    },
    stats: [
      { label: 'Sprachen', value: '15+' },
      { label: 'Phrasen', value: '500+' },
      { label: 'Offline', value: 'Ja' },
    ],
    targetAudience: 'Kreuzfahrt-Passagiere',
    category: 'sales',
  },
  {
    id: 'biz-portal',
    name: 'Biz Portal',
    tagline: 'Business-Tools für Unternehmer',
    description: 'Rechnungen erstellen, Kunden verwalten, Angebote schreiben und Buchhaltung führen. Die Business-Zentrale für Selbstständige und KMU.',
    icon: '🏢',
    color: 'from-slate-700 to-blue-600',
    url: APP_URLS.bizPortal,
    registerUrl: `${APP_URLS.bizPortal}/register`,
    features: [
      'Rechnungs-Erstellung',
      'Kunden- & Kontaktverwaltung',
      'Angebote & Kostenvoranschläge',
      'Einfache Buchhaltung (EÜR)',
      'Dashboard mit Umsatzübersicht',
    ],
    pricing: {
      free: 'Bis 5 Rechnungen/Monat',
      plans: [
        { name: 'Starter', price: '4,99', period: '/Monat' },
        { name: 'Business', price: '9,99', period: '/Monat', highlight: true },
        { name: 'Enterprise', price: '19,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Rechnungen', value: '∞' },
      { label: 'Kunden', value: '∞' },
      { label: 'EÜR', value: 'Ja' },
    ],
    targetAudience: 'Selbstständige & KMU',
    category: 'sales',
  },
  {
    id: 'fintutto-cloud',
    name: 'Fintutto Cloud',
    tagline: 'Die Startseite des Ökosystems',
    description: 'Zentrale Landing-Page des Fintutto-Universums. Übersicht aller Apps, News, Updates und der Einstiegspunkt für neue Nutzer.',
    icon: '☁️',
    color: 'from-sky-600 to-indigo-500',
    url: APP_URLS.fintuttoCloud,
    registerUrl: `${APP_URLS.fintuttoCloud}/register`,
    features: [
      'Ökosystem-Übersicht',
      'Neuigkeiten & Updates',
      'App-Vergleich & Empfehlungen',
      'Schnellzugriff auf alle Apps',
      'Registrierung & Onboarding',
    ],
    pricing: {
      free: 'Komplett kostenlos',
      plans: [{ name: 'Free', price: '0', period: 'für immer', highlight: true }],
    },
    stats: [
      { label: 'Apps', value: '24' },
      { label: 'Nutzer', value: '1000+' },
      { label: 'Kostenlos', value: 'Ja' },
    ],
    targetAudience: 'Alle Nutzer',
    category: 'finanzen',
  },
]

