// All Fintutto Ecosystem Apps - definitions, features, pricing, and URLs

const APP_URLS = {
  portal: import.meta.env.VITE_APP_URL_PORTAL || 'https://portal.fintutto.cloud',
  vermietify: import.meta.env.VITE_APP_URL_VERMIETIFY || 'https://vermietify.vercel.app',
  mieter: import.meta.env.VITE_APP_URL_MIETER || 'https://mieter-kw8d.vercel.app',
  hausmeister: import.meta.env.VITE_APP_URL_HAUSMEISTER || 'https://hausmeister-pro.vercel.app',
  ablesung: import.meta.env.VITE_APP_URL_ABLESUNG || 'https://ablesung.vercel.app',
  bescheidboxer: import.meta.env.VITE_APP_URL_BESCHEIDBOXER || 'https://bescheidboxer.vercel.app',
}

export interface AppInfo {
  id: string
  name: string
  tagline: string
  description: string
  icon: string // emoji
  color: string // tailwind gradient class
  url: string
  registerUrl: string
  features: string[]
  pricing: {
    free: string
    plans: { name: string; price: string; period: string; highlight?: boolean }[]
  }
  stats: { label: string; value: string }[]
  targetAudience: string
  badge?: string
  category: 'immobilien' | 'finanzen' | 'lifestyle' | 'sales'
}

export const FINTUTTO_APPS: AppInfo[] = [
  {
    id: 'portal',
    name: 'Fintutto Portal',
    tagline: 'Alle Mietrecht-Tools an einem Ort',
    description:
      '27 professionelle Tools: Rechner für Vermieter, Checker für Mieter und rechtssichere Formulare für alle. Basierend auf aktuellem deutschen Mietrecht.',
    icon: '✨',
    color: 'from-purple-600 to-indigo-600',
    url: APP_URLS.portal,
    registerUrl: `${APP_URLS.portal}/register`,
    features: [
      '7 Vermieter-Rechner (Kaution, Rendite, Kaufnebenkosten...)',
      '10 Mieter-Checker (Mietpreisbremse, Kündigung, Nebenkosten...)',
      '5 rechtssichere Formulare (Mietvertrag, Übergabeprotokoll...)',
      'KI-Assistent für Mietrecht-Fragen',
      'PDF-Export aller Berechnungen',
      'Credit-basiertes System – fair & flexibel',
    ],
    pricing: {
      free: '3 Credits/Monat kostenlos',
      plans: [
        { name: 'Mieter', price: '4,99', period: '/Monat' },
        { name: 'Vermieter', price: '7,99', period: '/Monat' },
        { name: 'Kombi Pro', price: '11,99', period: '/Monat', highlight: true },
        { name: 'Unlimited', price: '19,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Tools', value: '27' },
      { label: 'Bundesländer', value: '16' },
      { label: 'DSGVO', value: '100%' },
    ],
    targetAudience: 'Mieter & Vermieter',
    badge: 'Neu',
    category: 'finanzen',
  },
  {
    id: 'vermietify',
    name: 'Vermietify',
    tagline: 'Die komplette Immobilienverwaltung',
    description:
      'Gebäude, Mieter, Verträge, Zahlungen, Dokumente – alles in einer App. Mit 69 Formularen, automatischer Nebenkostenabrechnung und KI-Assistent.',
    icon: '🏠',
    color: 'from-blue-600 to-cyan-500',
    url: APP_URLS.vermietify,
    registerUrl: `${APP_URLS.vermietify}/register`,
    features: [
      'Gebäude- & Einheitenverwaltung',
      'Mieterverwaltung mit Vertragsdaten',
      '69 Formulare & Vorlagen',
      'Automatische Nebenkostenabrechnung',
      'Zahlungsübersicht & Mahnwesen',
      'KI-Assistent für Vermieter-Fragen',
      'Dokumenten-Management (Upload & Archiv)',
    ],
    pricing: {
      free: '3 Credits/Monat kostenlos',
      plans: [
        { name: 'Starter', price: '2,99', period: '/Monat' },
        { name: 'Pro', price: '7,99', period: '/Monat', highlight: true },
        { name: 'Unlimited', price: '14,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Formulare', value: '69' },
      { label: 'Features', value: '50+' },
      { label: 'KI-Assistent', value: 'Ja' },
    ],
    targetAudience: 'Vermieter & Hausverwaltungen',
    category: 'immobilien',
  },
  {
    id: 'mieter',
    name: 'Mieter-App',
    tagline: 'Dein digitaler Mieter-Assistent',
    description:
      'Mängel melden, Zähler ablesen, Dokumente anfordern und direkt mit der Hausverwaltung chatten. Mit 10 Rechts-Checkern für deine Mietrechte.',
    icon: '🔑',
    color: 'from-green-600 to-emerald-500',
    url: APP_URLS.mieter,
    registerUrl: `${APP_URLS.mieter}/register`,
    features: [
      'Mangel melden mit Foto-Upload',
      'Zählerstand digital ablesen',
      'Dokumente anfordern (Bescheinigungen etc.)',
      'Chat mit Hausverwaltung',
      'Hausordnung & Notfallkontakte',
      '10 Mietrecht-Checker (Mietpreisbremse, Kündigung...)',
      'KI-Assistent für Mieter-Fragen',
    ],
    pricing: {
      free: '1 Check/Monat kostenlos',
      plans: [
        { name: 'Basic', price: '0,99', period: '/Monat' },
        { name: 'Premium', price: '3,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Checker', value: '10' },
      { label: 'Chat', value: 'Live' },
      { label: 'KI', value: 'Ja' },
    ],
    targetAudience: 'Mieter',
    category: 'immobilien',
  },
  {
    id: 'hausmeister',
    name: 'HausmeisterPro',
    tagline: 'Facility Management leicht gemacht',
    description:
      'Aufgaben verwalten, Belege fotografieren, mit Eigentümern kommunizieren. Die digitale Zentrale für Hausmeister und Facility Manager.',
    icon: '🔧',
    color: 'from-orange-500 to-amber-500',
    url: APP_URLS.hausmeister,
    registerUrl: `${APP_URLS.hausmeister}/register`,
    features: [
      'Aufgabenverwaltung (erstellen, zuweisen, tracken)',
      'Belegerfassung mit Foto-Upload',
      'Chat mit Eigentümer / Hausverwaltung',
      'Status-Tracking für alle Aufträge',
      'Materialverwaltung & Bestellungen',
      'Anbindung an Mieter-App (Mängelmeldungen)',
    ],
    pricing: {
      free: 'Grundfunktionen kostenlos',
      plans: [
        { name: 'Pro', price: '4,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Aufgaben', value: '∞' },
      { label: 'Chat', value: 'Live' },
      { label: 'Belege', value: 'Foto' },
    ],
    targetAudience: 'Hausmeister & Facility Manager',
    category: 'immobilien',
  },
  {
    id: 'ablesung',
    name: 'Ablesung',
    tagline: 'Zählerstand-Erfassung digitalisiert',
    description:
      'Strom, Gas, Wasser, Heizung – alle Zählerstände digital erfassen, tracken und analysieren. Mit Verbrauchsanalyse und CSV-Import.',
    icon: '📊',
    color: 'from-teal-500 to-cyan-500',
    url: APP_URLS.ablesung,
    registerUrl: `${APP_URLS.ablesung}/register`,
    features: [
      'Digitale Zählerstand-Erfassung',
      'Gebäude- & Einheitenverwaltung',
      'Verbrauchsanalyse über Zeiträume',
      'CSV-Import für historische Daten',
      'OCR/Kamera-Erfassung (geplant)',
      'Anbindung an Vermietify (gemeinsame Daten)',
    ],
    pricing: {
      free: 'Grundfunktionen kostenlos',
      plans: [
        { name: 'Pro', price: '2,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Zählertypen', value: '4+' },
      { label: 'Analyse', value: 'Ja' },
      { label: 'Import', value: 'CSV' },
    ],
    targetAudience: 'Vermieter & Hausverwaltungen',
    category: 'immobilien',
  },
  {
    id: 'bescheidboxer',
    name: 'BescheidBoxer',
    tagline: 'Bescheide verstehen & anfechten',
    description:
      'Lade deinen Bescheid hoch und lass ihn analysieren. Grundsteuer, Nebenkosten, Betriebskostenabrechnungen – finde versteckte Fehler und spare Geld.',
    icon: '🥊',
    color: 'from-red-500 to-rose-500',
    url: APP_URLS.bescheidboxer,
    registerUrl: `${APP_URLS.bescheidboxer}/register`,
    features: [
      'Bescheid-Upload & KI-Analyse',
      'Grundsteuerbescheid prüfen',
      'Nebenkostenabrechnung prüfen',
      'Fehler automatisch erkennen',
      'Widerspruch-Vorlagen generieren',
      'Ersparnis-Rechner: So viel kannst du sparen',
    ],
    pricing: {
      free: '1 Analyse/Monat kostenlos',
      plans: [
        { name: 'Basic', price: '2,99', period: '/Monat' },
        { name: 'Pro', price: '7,99', period: '/Monat', highlight: true },
      ],
    },
    stats: [
      { label: 'Bescheid-Typen', value: '5+' },
      { label: 'KI-Analyse', value: 'Ja' },
      { label: 'Widerspruch', value: 'Auto' },
    ],
    targetAudience: 'Mieter & Eigentümer',
    badge: 'Neu',
    category: 'finanzen',
  },
  {
    id: 'vermieter-portal',
    name: 'Vermieter-Portal',
    tagline: 'Rechner & Formulare für Vermieter',
    description: 'Spezialisierte Tools für Vermieter: Mietrendite, Eigenkapital, Kaufnebenkosten-Rechner und rechtssichere Formulare.',
    icon: '🏢',
    color: 'from-indigo-600 to-blue-500',
    url: 'https://vermieter.fintutto.cloud',
    registerUrl: 'https://vermieter.fintutto.cloud/register',
    features: ['7 Vermieter-Rechner', '5 rechtssichere Formulare', 'Mietrendite-Berechnung', 'Kaufnebenkosten-Kalkulation', 'Eigenkapital-Planung'],
    pricing: { free: 'Alle Rechner kostenlos', plans: [{ name: 'Pro', price: '5,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Rechner', value: '7' }, { label: 'Formulare', value: '5' }, { label: 'Kostenlos', value: 'Ja' }],
    targetAudience: 'Vermieter & Eigentümer',
    category: 'immobilien',
  },
  {
    id: 'admin-hub',
    name: 'Admin-Hub',
    tagline: 'Zentrale Verwaltung aller Fintutto Apps',
    description: 'Benutzerverwaltung, Organisationen, App-übergreifende Einstellungen und Berechtigungen.',
    icon: '⚙️',
    color: 'from-slate-600 to-zinc-500',
    url: 'https://fintutto-admin-hub.vercel.app',
    registerUrl: 'https://fintutto-admin-hub.vercel.app/register',
    features: ['Benutzerverwaltung & Rollen', 'Organisationsverwaltung', 'App-übergreifende Einstellungen', 'Lizenz- & Aboverwaltung', 'Audit-Log & Aktivitätsprotokoll'],
    pricing: { free: 'Grundfunktionen inklusive', plans: [{ name: 'Team', price: '9,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Apps', value: '15' }, { label: 'Rollen', value: '∞' }, { label: 'SSO', value: 'Ja' }],
    targetAudience: 'Hausverwaltungen & Teams',
    category: 'finanzen',
  },
  {
    id: 'financial-compass',
    name: 'Financial Compass',
    tagline: 'Deine Finanzübersicht auf einen Blick',
    description: 'Einnahmen, Ausgaben, Steuern – alle Finanzdaten zusammengeführt. Mit automatischer Buchhaltung und Steuerreports.',
    icon: '🧭',
    color: 'from-violet-600 to-purple-500',
    url: 'https://fintutto-your-financial-compass.vercel.app',
    registerUrl: 'https://fintutto-your-financial-compass.vercel.app/register',
    features: ['Einnahmen- & Ausgabenübersicht', 'Automatische Kategorisierung', 'Steuerreports (Anlage V)', 'Mieteinnahmen-Tracking', 'Export für Steuerberater'],
    pricing: { free: 'Grundübersicht kostenlos', plans: [{ name: 'Plus', price: '4,99', period: '/Monat' }, { name: 'Pro', price: '9,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Reports', value: '10+' }, { label: 'Export', value: 'CSV/PDF' }, { label: 'Steuer', value: 'Auto' }],
    targetAudience: 'Vermieter & Eigentümer',
    category: 'finanzen',
  },
  {
    id: 'fittutto',
    name: 'FitTutto',
    tagline: 'Dein KI-Personal Trainer',
    description: 'Individuelle Trainingspläne, 500+ Übungen, Ernährungstracking und Gamification.',
    icon: '💪',
    color: 'from-green-600 to-emerald-500',
    url: 'https://fittutto.fintutto.cloud',
    registerUrl: 'https://fittutto.fintutto.cloud/auth',
    features: ['KI-generierte Trainingspläne', '500+ Übungen', 'Ernährungstracking', 'Fortschrittsstatistiken', 'Persönliche Rekorde'],
    pricing: { free: 'Trainingsplan erstellen kostenlos', plans: [{ name: 'Basic', price: '4,99', period: '/Monat', highlight: true }, { name: 'Premium', price: '9,99', period: '/Monat' }] },
    stats: [{ label: 'Übungen', value: '500+' }, { label: 'KI-Pläne', value: 'Ja' }, { label: 'Ernährung', value: 'Tracking' }],
    targetAudience: 'Fitness-Enthusiasten',
    badge: 'Neu',
    category: 'lifestyle',
  },
  {
    id: 'translator',
    name: 'Übersetzer',
    tagline: 'Online-Übersetzer mit Text-to-Speech',
    description: '22 Sprachen, Echtzeit-Übersetzung, Text-to-Speech und Verlauf.',
    icon: '🌐',
    color: 'from-sky-500 to-blue-500',
    url: 'https://translator-fintutto.vercel.app',
    registerUrl: 'https://translator-fintutto.vercel.app',
    features: ['22 Sprachen unterstützt', 'Text-to-Speech Ausgabe', 'Übersetzungsverlauf', 'Echtzeit-Übersetzung', 'Clipboard-Integration'],
    pricing: { free: 'Komplett kostenlos', plans: [{ name: 'Free', price: '0', period: 'für immer', highlight: true }] },
    stats: [{ label: 'Sprachen', value: '22' }, { label: 'TTS', value: 'Ja' }, { label: 'Preis', value: 'Gratis' }],
    targetAudience: 'Alle Nutzer',
    category: 'lifestyle',
  },
  {
    id: 'pflanzen-manager',
    name: 'Pflanzen-Manager',
    tagline: 'Zimmerpflanzen-Pflege leicht gemacht',
    description: 'Gießerinnerungen, Pflanzenprofile, Standort-Tracking und Pflege-Tipps.',
    icon: '🌱',
    color: 'from-green-500 to-lime-500',
    url: 'https://zimmerpflanze.vercel.app',
    registerUrl: 'https://zimmerpflanze.vercel.app/register',
    features: ['Pflanzenprofile mit Fotos', 'Gieß-Erinnerungen', 'Standort-Tracking', 'Pflege-Tipps & Anleitungen', 'Wachstums-Verlauf'],
    pricing: { free: 'Bis 5 Pflanzen kostenlos', plans: [{ name: 'Unlimited', price: '1,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Pflanzen', value: '∞' }, { label: 'Tipps', value: '200+' }, { label: 'Erinnerung', value: 'Push' }],
    targetAudience: 'Pflanzenliebhaber',
    category: 'lifestyle',
  },
  {
    id: 'luggagex',
    name: 'LuggageX',
    tagline: 'Gepäck-Tracking & Reise-Checklisten',
    description: 'Reisegepäck digital verwalten: Packlisten, Gewichts-Tracker und Versicherungsübersicht.',
    icon: '🧳',
    color: 'from-amber-500 to-orange-500',
    url: 'https://luggagex-fintutto.vercel.app',
    registerUrl: 'https://luggagex-fintutto.vercel.app',
    features: ['Digitale Packlisten', 'Gewichts-Tracker pro Koffer', 'Reise-Checklisten', 'Gepäck-Versicherung', 'Reise-Verlauf'],
    pricing: { free: 'Grundfunktionen kostenlos', plans: [{ name: 'Pro', price: '1,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Listen', value: '∞' }, { label: 'Reisen', value: '∞' }, { label: 'Gewicht', value: 'Auto' }],
    targetAudience: 'Reisende',
    category: 'lifestyle',
  },
  {
    id: 'guidetranslator',
    name: 'GuideTranslator',
    tagline: 'Übersetzer-Tool für Kreuzfahrtschiffe',
    description: 'Spezialisiertes Übersetzungstool für Reiseleiter und Guides auf Kreuzfahrtschiffen.',
    icon: '🚢',
    color: 'from-cyan-600 to-teal-500',
    url: 'https://app.guidetranslator.com',
    registerUrl: 'https://app.guidetranslator.com/register',
    features: ['Branchenspezifische Phrasen', 'Kreuzfahrt-Terminologie', 'Offline-Modus verfügbar', 'Mehrsprachige Durchsagen', 'Gäste-Kommunikation'],
    pricing: { free: 'Demo verfügbar', plans: [{ name: 'Pro', price: '9,99', period: '/Monat', highlight: true }] },
    stats: [{ label: 'Sprachen', value: '15+' }, { label: 'Phrasen', value: '1000+' }, { label: 'Offline', value: 'Ja' }],
    targetAudience: 'Reiseleiter & Guides',
    category: 'sales',
  },
  {
    id: 'command-center',
    name: 'Command Center',
    tagline: 'Fintutto Steuerungszentrale',
    description: 'Überblick über alle Fintutto-Apps, Nutzerstatistiken und System-Health.',
    icon: '🎛️',
    color: 'from-gray-700 to-slate-600',
    url: 'https://fintutto-command-center.vercel.app',
    registerUrl: 'https://fintutto-command-center.vercel.app',
    features: ['App-Status Dashboard', 'Nutzerstatistiken', 'Deployment-Übersicht', 'System-Health Monitoring', 'Cross-App Analytics'],
    pricing: { free: 'Nur für Admins', plans: [{ name: 'Admin', price: '0', period: 'inklusive', highlight: true }] },
    stats: [{ label: 'Apps', value: '15' }, { label: 'Uptime', value: '99.9%' }, { label: 'Analytics', value: 'Echtzeit' }],
    targetAudience: 'Administratoren',
    category: 'sales',
  },
  {
    id: 'fittutto',
    name: 'FitTutto',
    tagline: 'Dein persoenlicher Fitness-Begleiter',
    description:
      'Trainingsplaene, Workout-Tracking, Ernaehrungstracking, Koerpermessungen und KI-Coaching. 250+ Uebungen, Set-by-Set Logging, Makro-Tracker und mehr.',
    icon: '💪',
    color: 'from-orange-500 to-red-500',
    url: '/fittutto',
    registerUrl: '/register',
    features: [
      'Individuelle Trainingsplaene erstellen & generieren',
      'Workout-Tracking mit 250+ Uebungen',
      'Ernaehrungstracking mit Makro-Zielen',
      'Koerper-Tracking (Gewicht, Umfaenge, KFA)',
      'KI-Fitness-Coach fuer personalisierte Tipps',
      'Persoenliche Rekorde & Streak-Tracking',
    ],
    pricing: {
      free: 'Grundfunktionen kostenlos',
      plans: [
        { name: 'Speichern', price: '2,99', period: '/Monat' },
        { name: 'Basic', price: '4,99', period: '/Monat', highlight: true },
        { name: 'Premium', price: '9,99', period: '/Monat' },
      ],
    },
    stats: [
      { label: 'Uebungen', value: '250+' },
      { label: 'KI-Coach', value: 'Ja' },
      { label: 'Tracking', value: '360°' },
    ],
    targetAudience: 'Fitness-Enthusiasten',
    badge: 'Neu',
  },
]

