import { Exercise } from './fitness-types'
import { EXERCISES_EXTENDED } from './exercises-extended'

// ============================================
// FitTutto - Deutsche Uebungsbibliothek
// 250+ Uebungen mit Anleitungen
// ============================================

const EXERCISES_BASE: Exercise[] = [
  // ==================== BRUST ====================
  {
    id: 'bench-press-barbell',
    name: 'Bankdruecken (Langhantel)',
    nameEn: 'Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Lege dich flach auf die Bank, Fuesse fest am Boden.',
      'Greife die Stange etwas breiter als schulterbreit.',
      'Hebe die Stange aus der Ablage und halte sie ueber der Brust.',
      'Senke die Stange kontrolliert zur Mitte der Brust.',
      'Druecke die Stange explosiv nach oben zurueck.',
    ],
    tips: ['Schultern zusammenziehen und in die Bank druecken', 'Handgelenke gerade halten'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'bench-press-dumbbell',
    name: 'Bankdruecken (Kurzhanteln)',
    nameEn: 'Dumbbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Lege dich auf die Bank, eine Kurzhantel in jeder Hand.',
      'Druecke die Hanteln nach oben, bis die Arme gestreckt sind.',
      'Senke die Hanteln langsam seitlich ab, Ellbogen ca. 45 Grad.',
      'Druecke wieder nach oben und spanne die Brust an.',
    ],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'incline-bench-press',
    name: 'Schraegbankdruecken',
    nameEn: 'Incline Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Stelle die Bank auf ca. 30-45 Grad Neigung ein.',
      'Greife die Stange schulterbreit.',
      'Senke die Stange zur oberen Brust.',
      'Druecke explosiv nach oben.',
    ],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Schraegbank Kurzhanteldruecken',
    nameEn: 'Incline Dumbbell Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Stelle die Bank auf 30-45 Grad ein.',
      'Nimm je eine Kurzhantel und druecke sie nach oben.',
      'Senke kontrolliert ab, Ellbogen ca. 45 Grad vom Koerper.',
      'Druecke wieder hoch und spanne die obere Brust an.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'cable-flys',
    name: 'Kabelzug Flys',
    nameEn: 'Cable Flys',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['cable'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Stelle die Kabel auf Schulterhoehe ein.',
      'Greife beide Griffe und tritt einen Schritt vor.',
      'Fuehre die Haende in einem Bogen vor der Brust zusammen.',
      'Lasse kontrolliert zurueck in die Ausgangsposition.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'push-ups',
    name: 'Liegestuetze',
    nameEn: 'Push-Ups',
    category: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Stuetze dich mit den Haenden schulterbreit auf den Boden.',
      'Halte den Koerper gerade wie ein Brett.',
      'Senke dich ab, bis die Brust fast den Boden beruehrt.',
      'Druecke dich wieder hoch.',
    ],
    tips: ['Koerper immer gerade halten', 'Blick nach unten richten'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'dips-chest',
    name: 'Dips (Brust)',
    nameEn: 'Chest Dips',
    category: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Greife die Holme und stuetze dich hoch.',
      'Lehne den Oberkoerper leicht nach vorne.',
      'Senke dich ab, bis die Oberarme parallel zum Boden sind.',
      'Druecke dich wieder hoch.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'chest-press-machine',
    name: 'Brustpresse (Maschine)',
    nameEn: 'Chest Press Machine',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['machine'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Setze dich an die Maschine, Ruecken an das Polster.',
      'Greife die Griffe auf Brusthoehe.',
      'Druecke nach vorne, bis die Arme fast gestreckt sind.',
      'Lasse kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },

  // ==================== RUECKEN ====================
  {
    id: 'deadlift',
    name: 'Kreuzheben',
    nameEn: 'Deadlift',
    category: 'strength',
    primaryMuscles: ['back', 'hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'traps', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    locations: ['gym'],
    instructions: [
      'Stelle dich hueftbreit vor die Stange.',
      'Greife die Stange etwas breiter als schulterbreit.',
      'Halte den Ruecken gerade, Brust raus.',
      'Hebe die Stange durch Strecken der Beine und Hueften.',
      'Senke kontrolliert wieder ab.',
    ],
    tips: ['Ruecken IMMER gerade halten', 'Stange nah am Koerper fuehren'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 180,
  },
  {
    id: 'barbell-row',
    name: 'Langhantelrudern',
    nameEn: 'Barbell Row',
    category: 'strength',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'traps', 'lower_back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Beuge dich mit geradem Ruecken nach vorne (ca. 45 Grad).',
      'Greife die Stange schulterbreit im Untergriff oder Obergriff.',
      'Ziehe die Stange zum Bauchnabel.',
      'Senke kontrolliert ab.',
    ],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'pull-ups',
    name: 'Klimmzuege',
    nameEn: 'Pull-Ups',
    category: 'bodyweight',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Haenge an der Stange im Obergriff, etwas breiter als schulterbreit.',
      'Ziehe dich hoch, bis das Kinn ueber der Stange ist.',
      'Senke dich kontrolliert wieder ab.',
    ],
    tips: ['Schultern nach unten und hinten ziehen', 'Kein Schwung'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'chin-ups',
    name: 'Klimmzuege (Untergriff)',
    nameEn: 'Chin-Ups',
    category: 'bodyweight',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['back', 'forearms'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Haenge an der Stange im Untergriff, schulterbreit.',
      'Ziehe dich hoch, bis das Kinn ueber der Stange ist.',
      'Senke dich kontrolliert wieder ab.',
    ],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'lat-pulldown',
    name: 'Latzug',
    nameEn: 'Lat Pulldown',
    category: 'strength',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: ['cable'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Setze dich an den Latzug, Oberschenkel unter dem Polster.',
      'Greife die Stange breit im Obergriff.',
      'Ziehe die Stange zur oberen Brust.',
      'Lasse kontrolliert zurueck nach oben.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'seated-cable-row',
    name: 'Kabelrudern sitzend',
    nameEn: 'Seated Cable Row',
    category: 'strength',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'traps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Setze dich an das Kabelruder-Geraet.',
      'Greife den Griff, Ruecken gerade, leicht nach vorne gebeugt.',
      'Ziehe den Griff zum Bauchnabel, druecke die Schultern zurueck.',
      'Lasse kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'dumbbell-row',
    name: 'Kurzhantelrudern einarmig',
    nameEn: 'One-Arm Dumbbell Row',
    category: 'strength',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'traps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Stuetze ein Knie und eine Hand auf die Bank.',
      'Halte die Kurzhantel im anderen Arm haengend.',
      'Ziehe die Hantel zum Hueftbereich hoch.',
      'Senke kontrolliert ab.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    nameEn: 'Face Pulls',
    category: 'strength',
    primaryMuscles: ['traps', 'shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['cable'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Stelle den Kabelzug auf Kopfhoehe ein.',
      'Greife das Seil mit beiden Haenden.',
      'Ziehe das Seil zum Gesicht, Ellbogen nach aussen.',
      'Halte kurz und lasse kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },

  // ==================== SCHULTERN ====================
  {
    id: 'overhead-press',
    name: 'Schulterdruecken (Langhantel)',
    nameEn: 'Overhead Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Stehe aufrecht, Stange auf Schluesselbeinniveau.',
      'Druecke die Stange ueber den Kopf bis die Arme gestreckt sind.',
      'Senke kontrolliert zurueck.',
    ],
    tips: ['Koerperspannung halten', 'Nicht ins Hohlkreuz gehen'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Schulterdruecken (Kurzhanteln)',
    nameEn: 'Dumbbell Shoulder Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Setze dich aufrecht hin, Kurzhanteln auf Schulterhoehe.',
      'Druecke die Hanteln ueber Kopf.',
      'Senke kontrolliert zurueck zur Schulter.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'lateral-raises',
    name: 'Seitheben',
    nameEn: 'Lateral Raises',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Stehe aufrecht, Kurzhanteln seitlich haengend.',
      'Hebe die Arme seitlich an, bis sie parallel zum Boden sind.',
      'Halte kurz oben und senke kontrolliert.',
    ],
    tips: ['Nicht schwingen', 'Leicht nach vorne beugen'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'front-raises',
    name: 'Frontheben',
    nameEn: 'Front Raises',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['chest'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Stehe aufrecht, Kurzhanteln vor den Oberschenkeln.',
      'Hebe abwechselnd einen Arm nach vorne auf Schulterhoehe.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'reverse-flys',
    name: 'Reverse Flys',
    nameEn: 'Reverse Flys',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps', 'back'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Beuge den Oberkoerper nach vorne, Kurzhanteln haengend.',
      'Hebe die Arme seitlich nach oben/hinten.',
      'Druecke die Schulterblaetter zusammen.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    nameEn: 'Arnold Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Starte mit Kurzhanteln vor der Brust, Handflaechen zu dir.',
      'Druecke nach oben und drehe die Haende dabei nach aussen.',
      'Oben angekommen zeigen die Handflaechen nach vorne.',
      'Umkehren und kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },

  // ==================== BIZEPS ====================
  {
    id: 'barbell-curl',
    name: 'Langhantel Curls',
    nameEn: 'Barbell Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Stehe aufrecht, Langhantel im Untergriff schulterbreit.',
      'Beuge die Arme und bringe die Stange zur Schulter.',
      'Oberarme bleiben am Koerper.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'dumbbell-curl',
    name: 'Kurzhantel Curls',
    nameEn: 'Dumbbell Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Stehe aufrecht, je eine Kurzhantel in jeder Hand.',
      'Curle abwechselnd oder gleichzeitig nach oben.',
      'Drehe die Hand beim Hochbringen leicht nach aussen (Supination).',
      'Senke kontrolliert ab.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'hammer-curls',
    name: 'Hammer Curls',
    nameEn: 'Hammer Curls',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Stehe aufrecht, Kurzhanteln seitlich mit neutralem Griff.',
      'Beuge die Arme, Daumen zeigen nach oben.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'preacher-curl',
    name: 'Scott Curls',
    nameEn: 'Preacher Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Lege die Oberarme auf das Preacher-Polster.',
      'Curle die SZ-Stange nach oben.',
      'Senke langsam und kontrolliert ab.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'cable-curl',
    name: 'Kabelzug Curls',
    nameEn: 'Cable Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Stelle dich vor den unteren Kabelzug.',
      'Greife die Stange im Untergriff.',
      'Curle nach oben, Oberarme bleiben fixiert.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },

  // ==================== TRIZEPS ====================
  {
    id: 'tricep-pushdown',
    name: 'Trizeps-Druecken am Kabel',
    nameEn: 'Tricep Pushdown',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Stelle dich vor den oberen Kabelzug.',
      'Greife die Stange oder das Seil im Obergriff.',
      'Druecke nach unten bis die Arme gestreckt sind.',
      'Lasse kontrolliert zurueck, Oberarme am Koerper.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Trizeps ueber Kopf',
    nameEn: 'Overhead Tricep Extension',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Halte eine Kurzhantel mit beiden Haenden ueber dem Kopf.',
      'Senke die Hantel hinter dem Kopf ab.',
      'Strecke die Arme wieder nach oben.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'close-grip-bench',
    name: 'Enges Bankdruecken',
    nameEn: 'Close-Grip Bench Press',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Lege dich auf die Bank, Griff enger als schulterbreit.',
      'Senke die Stange zur unteren Brust.',
      'Druecke nach oben, Fokus auf Trizeps.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    nameEn: 'Skull Crushers',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Lege dich auf die Bank, SZ-Stange gestreckt ueber der Brust.',
      'Beuge die Ellbogen und senke die Stange zur Stirn.',
      'Strecke die Arme wieder nach oben.',
    ],
    tips: ['Ellbogen zeigen zur Decke, nicht nach aussen'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'dips-triceps',
    name: 'Dips (Trizeps)',
    nameEn: 'Tricep Dips',
    category: 'bodyweight',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Stuetze dich auf den Holmen, Koerper aufrecht.',
      'Senke dich ab, Ellbogen nach hinten.',
      'Druecke dich wieder hoch.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },

  // ==================== BEINE: QUADRIZEPS ====================
  {
    id: 'squat',
    name: 'Kniebeugen (Langhantel)',
    nameEn: 'Barbell Back Squat',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Positioniere die Stange auf dem oberen Ruecken/Nacken.',
      'Stehe etwas breiter als schulterbreit.',
      'Gehe in die Hocke, bis die Oberschenkel parallel sind.',
      'Druecke dich durch die Fersen wieder hoch.',
    ],
    tips: ['Knie ueber den Zehen', 'Brust raus, Ruecken gerade'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 180,
  },
  {
    id: 'front-squat',
    name: 'Frontkniebeugen',
    nameEn: 'Front Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'abs'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    locations: ['gym'],
    instructions: [
      'Stange liegt vorne auf den Schultern/Schluesselbein.',
      'Ellbogen hoch, Oberarme parallel zum Boden.',
      'Gehe tief in die Hocke.',
      'Druecke dich kontrolliert wieder hoch.',
    ],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 180,
  },
  {
    id: 'leg-press',
    name: 'Beinpresse',
    nameEn: 'Leg Press',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Setze dich in die Beinpresse, Fuesse schulterbreit.',
      'Lasse das Gewicht kontrolliert herunter.',
      'Druecke durch die Fersen nach oben (Knie nicht ganz strecken).',
    ],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 120,
  },
  {
    id: 'leg-extension',
    name: 'Beinstrecken',
    nameEn: 'Leg Extension',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Setze dich an die Maschine, Polster am Schienbein.',
      'Strecke die Beine nach vorne.',
      'Halte kurz und senke kontrolliert.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'lunges',
    name: 'Ausfallschritte',
    nameEn: 'Lunges',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Stehe aufrecht.',
      'Mache einen grossen Schritt nach vorne.',
      'Senke das hintere Knie Richtung Boden.',
      'Druecke dich zurueck in den Stand.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squats',
    nameEn: 'Goblet Squat',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Halte eine Kurzhantel oder Kettlebell vor der Brust.',
      'Gehe in die tiefe Hocke.',
      'Druecke dich durch die Fersen wieder hoch.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarische Kniebeugen',
    nameEn: 'Bulgarian Split Squat',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Stelle einen Fuss hinter dir auf eine Bank.',
      'Halte Kurzhanteln seitlich.',
      'Senke dich ab, bis das vordere Knie 90 Grad zeigt.',
      'Druecke dich wieder hoch.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },

  // ==================== BEINE: BEINBEUGER & GESAESS ====================
  {
    id: 'romanian-deadlift',
    name: 'Rumaenisches Kreuzheben',
    nameEn: 'Romanian Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Halte die Stange vor den Oberschenkeln.',
      'Schiebe die Hueften nach hinten, Knie leicht gebeugt.',
      'Senke die Stange entlang der Beine bis zur Schienbeinmitte.',
      'Richte dich durch die Hueften wieder auf.',
    ],
    tips: ['Ruecken IMMER gerade', 'Dehnung in den Beinbeugern spueren'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'leg-curl',
    name: 'Beinbeuger (Maschine)',
    nameEn: 'Leg Curl',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Lege dich auf die Beinbeuger-Maschine.',
      'Beuge die Beine und ziehe das Polster zur Gesaessmuskulatur.',
      'Halte kurz und strecke kontrolliert.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    nameEn: 'Hip Thrust',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Lehne den oberen Ruecken an eine Bank.',
      'Positioniere die Stange auf den Hueften.',
      'Druecke die Hueften nach oben, bis der Koerper gerade ist.',
      'Halte kurz oben und senke kontrolliert.',
    ],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    nameEn: 'Glute Bridge',
    category: 'bodyweight',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Lege dich auf den Ruecken, Knie angewinkelt.',
      'Druecke die Hueften hoch, bis der Koerper gerade ist.',
      'Spanne die Gesaessmuskulatur oben an.',
      'Senke kontrolliert.',
    ],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== WADEN ====================
  {
    id: 'standing-calf-raise',
    name: 'Wadenheben stehend',
    nameEn: 'Standing Calf Raise',
    category: 'strength',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Stelle dich an die Wadenheben-Maschine.',
      'Druecke dich auf die Zehenspitzen hoch.',
      'Halte kurz oben und senke langsam ab.',
    ],
    defaultSets: 4, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'seated-calf-raise',
    name: 'Wadenheben sitzend',
    nameEn: 'Seated Calf Raise',
    category: 'strength',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    locations: ['gym'],
    instructions: [
      'Setze dich an die Maschine, Knie unter dem Polster.',
      'Druecke die Fersen hoch.',
      'Senke kontrolliert ab, volle Dehnung unten.',
    ],
    defaultSets: 4, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== BAUCH ====================
  {
    id: 'crunches',
    name: 'Crunches',
    nameEn: 'Crunches',
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Lege dich auf den Ruecken, Knie angewinkelt.',
      'Hebe Kopf und Schultern vom Boden.',
      'Spanne den Bauch an und rolle nach oben.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },
  {
    id: 'plank',
    name: 'Plank',
    nameEn: 'Plank',
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'lower_back', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Stuetze dich auf die Unterarme.',
      'Halte den Koerper gerade wie ein Brett.',
      'Spanne Bauch und Gesaess an.',
      'Halte die Position.',
    ],
    defaultSets: 3, defaultReps: 60, defaultRestSeconds: 60,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Beinheben haengend',
    nameEn: 'Hanging Leg Raise',
    category: 'bodyweight',
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: ['obliques'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Haenge an einer Stange mit gestreckten Armen.',
      'Hebe die Beine gestreckt bis auf 90 Grad.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    nameEn: 'Russian Twist',
    category: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Setze dich mit angewinkelten Knien, Fuesse leicht angehoben.',
      'Lehne den Oberkoerper leicht zurueck.',
      'Drehe den Oberkoerper abwechselnd nach links und rechts.',
    ],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },
  {
    id: 'cable-woodchop',
    name: 'Kabelzug Holzhacker',
    nameEn: 'Cable Woodchop',
    category: 'strength',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'shoulders'],
    equipment: ['cable'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Stelle den Kabelzug auf Schulterhoehe ein.',
      'Greife den Griff mit beiden Haenden.',
      'Drehe den Oberkoerper diagonal nach unten zur anderen Seite.',
      'Kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    nameEn: 'Ab Wheel Rollout',
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lower_back', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    locations: ['gym', 'home'],
    instructions: [
      'Knie auf dem Boden, Haende am Ab Wheel.',
      'Rolle langsam nach vorne, Koerper strecken.',
      'Ziehe dich mit dem Bauch wieder zurueck.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    nameEn: 'Mountain Climbers',
    category: 'cardio',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors', 'shoulders', 'quads'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Starte in der Liegestuetzposition.',
      'Ziehe abwechselnd ein Knie zur Brust.',
      'Bewege dich schnell wie beim Laufen.',
    ],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 45,
  },

  // ==================== UNTERARME ====================
  {
    id: 'wrist-curls',
    name: 'Handgelenk-Curls',
    nameEn: 'Wrist Curls',
    category: 'strength',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Setze dich hin, Unterarme auf den Oberschenkeln.',
      'Halte die Kurzhanteln mit den Handflaechen nach oben.',
      'Beuge die Handgelenke nach oben.',
      'Senke kontrolliert.',
    ],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'farmers-walk',
    name: 'Farmers Walk',
    nameEn: 'Farmers Walk',
    category: 'strength',
    primaryMuscles: ['forearms', 'traps'],
    secondaryMuscles: ['abs', 'shoulders'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Nimm zwei schwere Kurzhanteln oder Kettlebells.',
      'Halte sie seitlich am Koerper.',
      'Gehe aufrecht eine bestimmte Strecke.',
    ],
    defaultSets: 3, defaultReps: 40, defaultRestSeconds: 90,
  },

  // ==================== CARDIO ====================
  {
    id: 'burpees',
    name: 'Burpees',
    nameEn: 'Burpees',
    category: 'cardio',
    primaryMuscles: ['abs', 'quads', 'chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'glutes'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Stehe aufrecht.',
      'Gehe in die Hocke, Haende auf den Boden.',
      'Springe mit den Fuessen nach hinten in die Liegestuetz-Position.',
      'Mache eine Liegestuetze.',
      'Springe zurueck in die Hocke.',
      'Springe hoch mit den Armen ueber dem Kopf.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'jumping-jacks',
    name: 'Hampelmann',
    nameEn: 'Jumping Jacks',
    category: 'cardio',
    primaryMuscles: ['quads', 'calves'],
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Stehe aufrecht, Arme seitlich.',
      'Springe und oeffne Beine und Arme gleichzeitig.',
      'Springe zurueck in die Ausgangsposition.',
    ],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 30,
  },
  {
    id: 'box-jumps',
    name: 'Box Jumps',
    nameEn: 'Box Jumps',
    category: 'cardio',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Stehe vor einer stabilen Box.',
      'Schwinge die Arme und springe auf die Box.',
      'Lande weich mit beiden Fuessen.',
      'Steige kontrolliert herunter.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'jump-rope',
    name: 'Seilspringen',
    nameEn: 'Jump Rope',
    category: 'cardio',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['quads', 'forearms', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Halte die Seilgriffe seitlich.',
      'Schwinge das Seil ueber den Kopf.',
      'Springe mit beiden Fuessen knapp ueber das Seil.',
    ],
    defaultSets: 3, defaultReps: 60, defaultRestSeconds: 30,
  },
  {
    id: 'battle-ropes',
    name: 'Battle Ropes',
    nameEn: 'Battle Ropes',
    category: 'cardio',
    primaryMuscles: ['shoulders', 'abs'],
    secondaryMuscles: ['biceps', 'forearms', 'quads'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Greife ein Ende in jede Hand.',
      'Stehe leicht in den Knien.',
      'Schlage abwechselnd oder gleichzeitig Wellen.',
    ],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 60,
  },

  // ==================== BEWEGLICHKEIT ====================
  {
    id: 'foam-rolling-quads',
    name: 'Faszienrolle Oberschenkel',
    nameEn: 'Foam Rolling Quads',
    category: 'flexibility',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['foam_roller'],
    difficulty: 'beginner',
    locations: ['gym', 'home'],
    instructions: [
      'Lege dich auf die Faszienrolle mit den Oberschenkeln.',
      'Rolle langsam von der Huefte zum Knie.',
      'Verweile auf schmerzhaften Stellen.',
    ],
    defaultSets: 1, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hueftbeuger-Dehnung',
    nameEn: 'Hip Flexor Stretch',
    category: 'flexibility',
    primaryMuscles: ['hip_flexors'],
    secondaryMuscles: ['quads'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Gehe in den Ausfallschritt, hinteres Knie am Boden.',
      'Schiebe die Huefte nach vorne.',
      'Halte die Dehnung 30 Sekunden pro Seite.',
    ],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'shoulder-stretch',
    name: 'Schulter-Dehnung',
    nameEn: 'Shoulder Stretch',
    category: 'flexibility',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Ziehe einen Arm vor der Brust zur Gegenseite.',
      'Halte 30 Sekunden pro Seite.',
    ],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'cat-cow',
    name: 'Katze-Kuh',
    nameEn: 'Cat-Cow',
    category: 'flexibility',
    primaryMuscles: ['lower_back'],
    secondaryMuscles: ['abs'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Gehe in den Vierfuesslerstand.',
      'Wechsle zwischen Runduecken (Katze) und Hohlkreuz (Kuh).',
      'Bewege dich langsam und fliessend.',
    ],
    defaultSets: 2, defaultReps: 10, defaultRestSeconds: 0,
  },
  {
    id: 'pigeon-stretch',
    name: 'Tauben-Dehnung',
    nameEn: 'Pigeon Stretch',
    category: 'flexibility',
    primaryMuscles: ['glutes', 'hip_flexors'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    locations: ['gym', 'home', 'outdoor'],
    instructions: [
      'Bringe ein Bein angewinkelt nach vorne.',
      'Strecke das andere Bein nach hinten.',
      'Lehne dich vor und halte 30 Sekunden pro Seite.',
    ],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },

  // ==================== GANZKÖRPER / COMPOUND ====================
  {
    id: 'clean-and-press',
    name: 'Umsetzen & Druecken',
    nameEn: 'Clean and Press',
    category: 'strength',
    primaryMuscles: ['shoulders', 'quads', 'glutes'],
    secondaryMuscles: ['back', 'traps', 'abs'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    locations: ['gym'],
    instructions: [
      'Stehe vor der Stange, hueftbreit.',
      'Hebe die Stange explosiv zur Schulter (Umsetzen).',
      'Druecke die Stange ueber Kopf (Druecken).',
      'Senke kontrolliert zur Schulter und zum Boden.',
    ],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 180,
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    nameEn: 'Kettlebell Swing',
    category: 'strength',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['shoulders', 'abs', 'lower_back'],
    equipment: ['kettlebell'],
    difficulty: 'intermediate',
    locations: ['gym', 'home'],
    instructions: [
      'Stehe hueftbreit, Kettlebell vor dir.',
      'Schwinge die Kettlebell zwischen den Beinen nach hinten.',
      'Druecke die Hueften explosiv nach vorne.',
      'Schwinge die Kettlebell bis auf Schulterhoehe.',
    ],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'turkish-getup',
    name: 'Turkish Get-Up',
    nameEn: 'Turkish Get-Up',
    category: 'strength',
    primaryMuscles: ['shoulders', 'abs'],
    secondaryMuscles: ['glutes', 'quads', 'traps'],
    equipment: ['kettlebell'],
    difficulty: 'advanced',
    locations: ['gym', 'home'],
    instructions: [
      'Lege dich auf den Ruecken, Kettlebell in einer Hand gestreckt.',
      'Stehe in mehreren Schritten auf, Gewicht immer oben.',
      'Lege dich in umgekehrter Reihenfolge wieder hin.',
    ],
    defaultSets: 3, defaultReps: 5, defaultRestSeconds: 120,
  },
  {
    id: 'thruster',
    name: 'Thruster',
    nameEn: 'Thruster',
    category: 'strength',
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['glutes', 'triceps', 'abs'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    locations: ['gym'],
    instructions: [
      'Halte die Stange auf den Schultern.',
      'Gehe in die Kniebeuge.',
      'Druecke explosiv hoch und die Stange ueber Kopf.',
      'Senke kontrolliert zurueck.',
    ],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'man-maker',
    name: 'Man Maker',
    nameEn: 'Man Maker',
    category: 'strength',
    primaryMuscles: ['chest', 'back', 'shoulders', 'quads'],
    secondaryMuscles: ['abs', 'triceps', 'biceps', 'glutes'],
    equipment: ['dumbbell'],
    difficulty: 'advanced',
    locations: ['gym', 'home'],
    instructions: [
      'Starte im Stand mit 2 Kurzhanteln.',
      'Gehe in die Liegestuetz-Position.',
      'Mache eine Liegestuetze.',
      'Rudere rechts, dann links.',
      'Springe in die Hocke.',
      'Druecke die Hanteln ueber Kopf.',
    ],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 120,
  },
]

// Merge base + extended exercises (deduplicate by ID)
const seenIds = new Set<string>()
export const EXERCISES: Exercise[] = [...EXERCISES_BASE, ...EXERCISES_EXTENDED].filter(e => {
  if (seenIds.has(e.id)) return false
  seenIds.add(e.id)
  return true
})

// --- Helper Functions ---

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id)
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(e =>
    e.primaryMuscles.includes(muscle as any) || e.secondaryMuscles.includes(muscle as any)
  )
}

export function getExercisesByEquipment(eq: string): Exercise[] {
  return EXERCISES.filter(e => e.equipment.includes(eq as any))
}

export function getExercisesByLocation(loc: string): Exercise[] {
  return EXERCISES.filter(e => e.locations.includes(loc as any))
}

export function getExercisesByCategory(cat: string): Exercise[] {
  return EXERCISES.filter(e => e.category === cat)
}

export function searchExercises(query: string): Exercise[] {
  const q = query.toLowerCase()
  return EXERCISES.filter(e =>
    e.name.toLowerCase().includes(q) ||
    (e.nameEn && e.nameEn.toLowerCase().includes(q))
  )
}
