import { Exercise } from './fitness-types'

// ============================================
// FitTutto - Erweiterte Uebungsbibliothek
// 150+ zusaetzliche Uebungen
// ============================================

export const EXERCISES_EXTENDED: Exercise[] = [
  // ==================== BRUST (erweitert) ====================
  {
    id: 'decline-bench-press', name: 'Negativ-Bankdruecken', nameEn: 'Decline Bench Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Bank auf -15 bis -30 Grad stellen.', 'Stange zur unteren Brust senken.', 'Explosiv hochdruecken.'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'svend-press', name: 'Svend Press', nameEn: 'Svend Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Halte eine Hantelscheibe mit beiden Haenden vor der Brust.', 'Druecke sie nach vorne und zusammen.', 'Langsam zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'pec-deck', name: 'Butterfly (Maschine)', nameEn: 'Pec Deck',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich an die Maschine, Arme auf den Polstern.', 'Fuehre die Arme vor der Brust zusammen.', 'Kontrolliert oeffnen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'landmine-press', name: 'Landmine Press', nameEn: 'Landmine Press',
    category: 'strength', primaryMuscles: ['chest', 'shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Klemme ein Stangenende in eine Ecke.', 'Halte das andere Ende mit beiden Haenden.', 'Druecke nach oben/vorne.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'diamond-push-ups', name: 'Diamant-Liegestuetze', nameEn: 'Diamond Push-Ups',
    category: 'bodyweight', primaryMuscles: ['chest', 'triceps'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Haende unter der Brust, Daumen und Zeigefinger bilden ein Dreieck.', 'Senke dich ab.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'incline-cable-fly', name: 'Schraegbank Kabel-Flys', nameEn: 'Incline Cable Fly',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['cable', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Bank auf 30-45 Grad, Kabel unten.', 'Fuehre die Griffe in einem Bogen ueber der Brust zusammen.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },

  // ==================== RUECKEN (erweitert) ====================
  {
    id: 'tbar-row', name: 'T-Bar Rudern', nameEn: 'T-Bar Row',
    category: 'strength', primaryMuscles: ['back', 'lats'], secondaryMuscles: ['biceps', 'traps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe ueber der Stange, V-Griff befestigt.', 'Ruecken gerade, Oberkoerper 45 Grad.', 'Ziehe zur Brust.'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'pendlay-row', name: 'Pendlay Row', nameEn: 'Pendlay Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'traps', 'lower_back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange am Boden, Oberkoerper parallel zum Boden.', 'Explosiv zur Brust ziehen.', 'Stange komplett ablegen.'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 120,
  },
  {
    id: 'chest-supported-row', name: 'Rudern mit Brustauflage', nameEn: 'Chest-Supported Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Lege dich baeuchlings auf eine Schraegbank.', 'Kurzhanteln haengend.', 'Ziehe beide Hanteln hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'meadows-row', name: 'Meadows Row', nameEn: 'Meadows Row',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'traps'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stehe seitlich zur Landmine.', 'Greife das Stangenende im Obergriff.', 'Ziehe explosiv zur Huefte.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', nameEn: 'Straight-Arm Pulldown',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['abs'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe vor dem oberen Kabelzug.', 'Arme gestreckt, ziehe die Stange zu den Oberschenkeln.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'inverted-row', name: 'Bodyweight Rudern', nameEn: 'Inverted Row',
    category: 'bodyweight', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Haenge unter einer niedrigen Stange.', 'Ziehe die Brust zur Stange.', 'Senke kontrolliert.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'rack-pull', name: 'Rack Pull', nameEn: 'Rack Pull',
    category: 'strength', primaryMuscles: ['back', 'traps'], secondaryMuscles: ['lower_back', 'forearms'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange im Rack auf Kniehoehe.', 'Greife schulterbreit.', 'Ziehe hoch, Schultern zurueck.'],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 120,
  },
  {
    id: 'wide-grip-pulldown', name: 'Weiter Latzug', nameEn: 'Wide-Grip Lat Pulldown',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Greife die Stange sehr breit.', 'Ziehe zur oberen Brust.', 'Schultern nach unten.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'close-grip-pulldown', name: 'Enger Latzug', nameEn: 'Close-Grip Pulldown',
    category: 'strength', primaryMuscles: ['lats', 'biceps'], secondaryMuscles: ['back'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['V-Griff am Latzug.', 'Ziehe zum Brustbein.', 'Ellbogen nah am Koerper.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'single-arm-lat-pulldown', name: 'Einarmiger Latzug', nameEn: 'Single-Arm Lat Pulldown',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps'],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Greife den Kabelgriff mit einer Hand.', 'Ziehe den Ellbogen zur Huefte.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== SCHULTERN (erweitert) ====================
  {
    id: 'cable-lateral-raise', name: 'Kabel-Seitheben', nameEn: 'Cable Lateral Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe seitlich zum unteren Kabelzug.', 'Hebe den Arm seitlich an.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'upright-row', name: 'Aufrechtes Rudern', nameEn: 'Upright Row',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['biceps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange eng greifen.', 'Ziehe entlang des Koerpers zum Kinn.', 'Ellbogen fuehren.'],
    tips: ['Vorsicht bei Schulterproblemen - Alternative: Seitheben'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'behind-neck-press', name: 'Nacken-Druecken', nameEn: 'Behind the Neck Press',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'traps'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange hinter dem Kopf auf den Schultern.', 'Druecke nach oben.', 'Nur mit guter Schulter-Mobilitaet!'],
    tips: ['Nur fuer erfahrene Sportler mit guter Schultermobilitaet'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'plate-front-raise', name: 'Frontheben mit Scheibe', nameEn: 'Plate Front Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Halte eine Hantelscheibe mit beiden Haenden.', 'Hebe sie auf Schulterhoehe.', 'Senke kontrolliert.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'lu-raise', name: 'Lu Raise', nameEn: 'Lu Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['traps'],
    equipment: ['dumbbell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Kurzhanteln seitlich.', 'Hebe seitlich auf 90 Grad.', 'Dann rotiere nach oben (wie ein Y).', 'Umgekehrt zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== ARME (erweitert) ====================
  {
    id: 'concentration-curl', name: 'Konzentrations-Curls', nameEn: 'Concentration Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Sitzend, Ellbogen am Oberschenkel.', 'Curle die Hantel nach oben.', 'Langsam senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'spider-curl', name: 'Spider Curls', nameEn: 'Spider Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['dumbbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Baeuchlings auf Schraegbank.', 'Arme haengen frei.', 'Curle nach oben.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'bayesian-curl', name: 'Bayesian Curl', nameEn: 'Bayesian Cable Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe mit dem Ruecken zum Kabelzug.', 'Greife den unteren Griff.', 'Curle nach vorne/oben.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'reverse-curl', name: 'Reverse Curls', nameEn: 'Reverse Curl',
    category: 'strength', primaryMuscles: ['forearms', 'biceps'], secondaryMuscles: [],
    equipment: ['barbell'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Greife die Stange im Obergriff.', 'Curle nach oben.', 'Langsam senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'tricep-kickback', name: 'Trizeps Kickback', nameEn: 'Tricep Kickback',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Beuge dich vor, Oberarm parallel zum Boden.', 'Strecke den Unterarm nach hinten.', 'Kontrolliert beugen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'rope-pushdown', name: 'Seil-Druecken am Kabel', nameEn: 'Rope Pushdown',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Seilgriff am oberen Kabelzug.', 'Druecke nach unten und spreize am Ende.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'jm-press', name: 'JM Press', nameEn: 'JM Press',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: ['chest'],
    equipment: ['barbell', 'bench'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Wie enges Bankdruecken, aber Stange zur Stirn/Nase senken.', 'Ellbogen fallen nach vorne.', 'Trizeps-Fokus.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },

  // ==================== BEINE (erweitert) ====================
  {
    id: 'hack-squat', name: 'Hack Squat', nameEn: 'Hack Squat',
    category: 'strength', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Ruecken ans Polster, Fuesse schulterbreit.', 'Senke kontrolliert ab.', 'Druecke durch die Fersen hoch.'],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 120,
  },
  {
    id: 'sissy-squat', name: 'Sissy Squat', nameEn: 'Sissy Squat',
    category: 'bodyweight', primaryMuscles: ['quads'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Stehe aufrecht, halte dich fest.', 'Lehne den Oberkoerper zurueck, Knie nach vorne.', 'Senke dich tief ab.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'leg-press-narrow', name: 'Beinpresse eng', nameEn: 'Narrow Stance Leg Press',
    category: 'strength', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Fuesse eng und tief auf der Platte.', 'Fokus auf Quadrizeps.', 'Voller Bewegungsumfang.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90,
  },
  {
    id: 'walking-lunges', name: 'Walking Lunges', nameEn: 'Walking Lunges',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell'], difficulty: 'intermediate', locations: ['gym', 'outdoor'],
    instructions: ['Kurzhanteln seitlich halten.', 'Grosse Schritte nach vorne.', 'Abwechselnd links und rechts.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90,
  },
  {
    id: 'step-ups', name: 'Step-Ups', nameEn: 'Step-Ups',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bench'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Stelle einen Fuss auf eine Bank/Box.', 'Druecke dich hoch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'sumo-deadlift', name: 'Sumo Kreuzheben', nameEn: 'Sumo Deadlift',
    category: 'strength', primaryMuscles: ['glutes', 'quads'], secondaryMuscles: ['hamstrings', 'back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Breiter Stand, Zehenspitzen nach aussen.', 'Greife die Stange eng.', 'Hebe durch Hueftstreckung.'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 180,
  },
  {
    id: 'stiff-leg-deadlift', name: 'Gestrecktes Kreuzheben', nameEn: 'Stiff-Leg Deadlift',
    category: 'strength', primaryMuscles: ['hamstrings'], secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Beine fast gestreckt.', 'Schiebe Hueften zurueck, Stange nah am Koerper.', 'Dehnung in den Beinbeugern spueren.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'nordic-hamstring-curl', name: 'Nordic Hamstring Curl', nameEn: 'Nordic Hamstring Curl',
    category: 'bodyweight', primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Knie auf dem Boden, Fuesse fixiert.', 'Lasse dich langsam nach vorne fallen.', 'Fange dich auf und druecke zurueck.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 120,
  },
  {
    id: 'good-morning', name: 'Good Mornings', nameEn: 'Good Morning',
    category: 'strength', primaryMuscles: ['hamstrings', 'lower_back'], secondaryMuscles: ['glutes'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange auf dem Ruecken.', 'Beuge den Oberkoerper nach vorne (Knie leicht gebeugt).', 'Richte dich auf.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'cable-pull-through', name: 'Cable Pull-Through', nameEn: 'Cable Pull-Through',
    category: 'strength', primaryMuscles: ['glutes', 'hamstrings'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe mit dem Ruecken zum Kabelzug.', 'Seilgriff zwischen den Beinen.', 'Hueften nach vorne stossen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'hip-abduction', name: 'Abduktoren (Maschine)', nameEn: 'Hip Abduction',
    category: 'strength', primaryMuscles: ['glutes'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine.', 'Oeffne die Beine gegen den Widerstand.', 'Kontrolliert schliessen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'hip-adduction', name: 'Adduktoren (Maschine)', nameEn: 'Hip Adduction',
    category: 'strength', primaryMuscles: ['hip_flexors'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine, Beine geoeffnet.', 'Schliesse die Beine.', 'Kontrolliert oeffnen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'donkey-calf-raise', name: 'Donkey Calf Raise', nameEn: 'Donkey Calf Raise',
    category: 'strength', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Beuge dich vor, Polster auf den Hueften.', 'Hebe die Fersen hoch.', 'Senke langsam ab.'],
    defaultSets: 4, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'single-leg-calf-raise', name: 'Einbeiniges Wadenheben', nameEn: 'Single-Leg Calf Raise',
    category: 'bodyweight', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Stehe auf einem Bein (auf einer Stufe).', 'Hebe dich auf die Zehenspitzen.', 'Senke tief ab, volle Dehnung.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== BAUCH (erweitert) ====================
  {
    id: 'cable-crunch', name: 'Kabel-Crunches', nameEn: 'Cable Crunch',
    category: 'strength', primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Knie vor dem Kabelzug.', 'Seilgriff hinter dem Kopf.', 'Rolle den Oberkoerper ein.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'decline-crunch', name: 'Crunches auf Negativbank', nameEn: 'Decline Crunch',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Lege dich auf die Negativbank, Fuesse fixiert.', 'Hebe den Oberkoerper hoch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'v-ups', name: 'V-Ups', nameEn: 'V-Ups',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Arme ueber dem Kopf.', 'Hebe Beine und Arme gleichzeitig.', 'Beruehre die Zehen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'dead-bug', name: 'Dead Bug', nameEn: 'Dead Bug',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Auf dem Ruecken, Arme und Beine in der Luft.', 'Strecke gegenueber Arm und Bein.', 'Wechsle die Seiten.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'bicycle-crunch', name: 'Fahrrad-Crunches', nameEn: 'Bicycle Crunch',
    category: 'bodyweight', primaryMuscles: ['abs', 'obliques'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Haende am Kopf.', 'Fuehre Ellbogen zum gegenueber Knie.', 'Radfahrbewegung.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },
  {
    id: 'side-plank', name: 'Seitlicher Plank', nameEn: 'Side Plank',
    category: 'bodyweight', primaryMuscles: ['obliques'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stuetze dich seitlich auf einen Unterarm.', 'Hebe die Huefte an.', 'Halte die Position.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 45,
  },
  {
    id: 'pallof-press', name: 'Pallof Press', nameEn: 'Pallof Press',
    category: 'strength', primaryMuscles: ['abs', 'obliques'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe seitlich zum Kabelzug.', 'Druecke den Griff vor die Brust.', 'Halte und widersetze der Rotation.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'dragon-flag', name: 'Dragon Flag', nameEn: 'Dragon Flag',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['lower_back'],
    equipment: ['bench'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Lege dich auf eine Bank, halte dich oben fest.', 'Hebe den gesamten Koerper als Brett.', 'Senke kontrolliert ab.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 120,
  },
  {
    id: 'toe-touches', name: 'Zehen-Beruehrung', nameEn: 'Toe Touches',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Beine senkrecht.', 'Hebe den Oberkoerper und beruehre die Zehen.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== COMPOUND / OLYMPISCH ====================
  {
    id: 'power-clean', name: 'Power Clean', nameEn: 'Power Clean',
    category: 'strength', primaryMuscles: ['quads', 'glutes', 'traps'], secondaryMuscles: ['shoulders', 'back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange am Boden, greife schulterbreit.', 'Explosiv hochziehen (1. Pull).', 'Unter die Stange springen (Catch).'],
    defaultSets: 4, defaultReps: 3, defaultRestSeconds: 180,
  },
  {
    id: 'hang-clean', name: 'Hang Clean', nameEn: 'Hang Clean',
    category: 'strength', primaryMuscles: ['quads', 'traps'], secondaryMuscles: ['glutes', 'shoulders'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange auf Kniehoehe halten.', 'Explosiv nach oben ziehen.', 'Unter die Stange springen.'],
    defaultSets: 4, defaultReps: 3, defaultRestSeconds: 180,
  },
  {
    id: 'snatch', name: 'Snatch (Reissen)', nameEn: 'Snatch',
    category: 'strength', primaryMuscles: ['shoulders', 'quads', 'glutes'], secondaryMuscles: ['traps', 'back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Breiter Griff, Stange am Boden.', 'Explosiv hochziehen.', 'Unter die Stange springen, Arme gestreckt.'],
    defaultSets: 4, defaultReps: 2, defaultRestSeconds: 180,
  },
  {
    id: 'push-press', name: 'Push Press', nameEn: 'Push Press',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'quads'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange auf den Schultern.', 'Leichtes Einbeugen der Knie.', 'Explosiv hochdruecken mit Beinunterstuetzung.'],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 120,
  },

  // ==================== CARDIO (erweitert) ====================
  {
    id: 'rowing-machine', name: 'Rudergeraet', nameEn: 'Rowing Machine',
    category: 'cardio', primaryMuscles: ['back', 'quads'], secondaryMuscles: ['biceps', 'abs'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Fuesse fixieren, Griff greifen.', 'Zuerst Beine strecken, dann Arme ziehen.', 'Kontrolliert zurueck.'],
    defaultSets: 1, defaultReps: 300, defaultRestSeconds: 0,
  },
  {
    id: 'assault-bike', name: 'Assault Bike', nameEn: 'Assault Bike',
    category: 'cardio', primaryMuscles: ['quads', 'shoulders'], secondaryMuscles: ['abs', 'calves'],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Setze dich aufs Bike.', 'Haende an die Griffe.', 'Trete und druecke/ziehe gleichzeitig.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 60,
  },
  {
    id: 'sled-push', name: 'Schlittenpressen', nameEn: 'Sled Push',
    category: 'cardio', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves', 'shoulders'],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Haende an die Griffe des Schlittens.', 'Druecke mit voller Kraft nach vorne.', 'Koerper leicht nach vorne geneigt.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 90,
  },
  {
    id: 'high-knees', name: 'Kniehebelauf', nameEn: 'High Knees',
    category: 'cardio', primaryMuscles: ['quads', 'hip_flexors'], secondaryMuscles: ['calves', 'abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Laufe auf der Stelle.', 'Ziehe die Knie abwechselnd hoch.', 'Arme mitschwingen.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 30,
  },
  {
    id: 'skater-hops', name: 'Skater Hops', nameEn: 'Skater Hops',
    category: 'cardio', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Springe seitlich von einem Bein aufs andere.', 'Wie ein Eisschnelllaeufer.', 'Arme mitschwingen.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },

  // ==================== BEWEGLICHKEIT (erweitert) ====================
  {
    id: 'world-greatest-stretch', name: "World's Greatest Stretch", nameEn: "World's Greatest Stretch",
    category: 'flexibility', primaryMuscles: ['hip_flexors', 'hamstrings'], secondaryMuscles: ['shoulders', 'obliques'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Ausfallschritt, Hand am Boden.', 'Drehe den Oberkoerper zur offenen Seite.', 'Halte 15 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 5, defaultRestSeconds: 0,
  },
  {
    id: 'thoracic-rotation', name: 'Brustwirbel-Rotation', nameEn: 'Thoracic Rotation',
    category: 'flexibility', primaryMuscles: ['obliques'], secondaryMuscles: ['back'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Vierfuesslerstand.', 'Hand hinter den Kopf.', 'Drehe den Oberkoerper zur Seite, oeffne die Brust.'],
    defaultSets: 2, defaultReps: 10, defaultRestSeconds: 0,
  },
  {
    id: 'hamstring-stretch', name: 'Beinbeuger-Dehnung', nameEn: 'Hamstring Stretch',
    category: 'flexibility', primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Strecke ein Bein auf einer erhoehten Flaeche.', 'Beuge dich mit geradem Ruecken nach vorne.', 'Halte 30 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'chest-doorway-stretch', name: 'Brust-Dehnung im Tuerhrahmen', nameEn: 'Doorway Chest Stretch',
    category: 'flexibility', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['home'],
    instructions: ['Arme an den Tuerrahmen, 90 Grad.', 'Einen Schritt nach vorne.', 'Dehnung in der Brust spueren.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'couch-stretch', name: 'Couch Stretch', nameEn: 'Couch Stretch',
    category: 'flexibility', primaryMuscles: ['hip_flexors', 'quads'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['home', 'gym'],
    instructions: ['Knie an einer Wand, Fuss zeigt nach oben.', 'Vorderes Bein aufgestellt (90 Grad).', 'Aufrechthalten, 60 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'lat-stretch', name: 'Latissimus-Dehnung', nameEn: 'Lat Stretch',
    category: 'flexibility', primaryMuscles: ['lats'], secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Greife eine Stange oder Tuerrahmen auf Kopfhoehe.', 'Lehne dich zurueck und zur Seite.', 'Dehnung im Lat spueren.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },

  // ==================== HOME / RESISTANCE BAND ====================
  {
    id: 'band-pull-apart', name: 'Band Pull-Apart', nameEn: 'Band Pull-Apart',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['back'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Halte das Band vor dir auf Schulterhoehe.', 'Ziehe es auseinander.', 'Druecke die Schulterblaetter zusammen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 30,
  },
  {
    id: 'band-squat', name: 'Band Kniebeugen', nameEn: 'Banded Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: [],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Band unter den Fuessen, Enden in den Haenden.', 'Kniebeugen mit Widerstand.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-row', name: 'Band Rudern', nameEn: 'Banded Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Setze dich hin, Band um die Fuesse.', 'Ziehe die Enden zum Bauch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-chest-press', name: 'Band Brustdruecken', nameEn: 'Banded Chest Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Band hinter dem Ruecken, Enden in den Haenden.', 'Druecke nach vorne.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-face-pull', name: 'Band Face Pull', nameEn: 'Banded Face Pull',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['back'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'gym'],
    instructions: ['Band an einer Tuer oder Stange befestigt.', 'Ziehe zum Gesicht mit Ellbogen hoch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 30,
  },

  // ==================== TRX / SCHLINGENTRAINER ====================
  {
    id: 'trx-row', name: 'TRX Rudern', nameEn: 'TRX Row',
    category: 'bodyweight', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['trx'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Greife die TRX-Griffe, lehne dich zurueck.', 'Ziehe die Brust zu den Haenden.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'trx-chest-press', name: 'TRX Brustdruecken', nameEn: 'TRX Chest Press',
    category: 'bodyweight', primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['trx'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Haende in den TRX-Griffen, Koerper geneigt.', 'Senke dich ab wie bei Liegestuetzen.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'trx-pike', name: 'TRX Pike', nameEn: 'TRX Pike',
    category: 'bodyweight', primaryMuscles: ['abs', 'shoulders'], secondaryMuscles: ['hip_flexors'],
    equipment: ['trx'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Fuesse in den TRX-Schlaufen, Liegestuetzposition.', 'Ziehe die Hueften hoch zum Pike.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== KETTLEBELL (erweitert) ====================
  {
    id: 'kb-goblet-squat', name: 'Kettlebell Goblet Squat', nameEn: 'KB Goblet Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['abs'],
    equipment: ['kettlebell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Halte die KB vor der Brust.', 'Tiefe Kniebeuge.', 'Druecke durch die Fersen hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'kb-clean-press', name: 'KB Clean & Press', nameEn: 'KB Clean & Press',
    category: 'strength', primaryMuscles: ['shoulders', 'glutes'], secondaryMuscles: ['back', 'abs'],
    equipment: ['kettlebell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['KB zwischen den Beinen schwingen.', 'Umsetzen zur Schulter.', 'Ueber Kopf druecken.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'kb-snatch', name: 'Kettlebell Snatch', nameEn: 'KB Snatch',
    category: 'strength', primaryMuscles: ['shoulders', 'glutes'], secondaryMuscles: ['back', 'abs'],
    equipment: ['kettlebell'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['KB einarmig schwingen.', 'In einer Bewegung ueber Kopf reissen.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'kb-windmill', name: 'Kettlebell Windmill', nameEn: 'KB Windmill',
    category: 'strength', primaryMuscles: ['obliques', 'shoulders'], secondaryMuscles: ['hip_flexors'],
    equipment: ['kettlebell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['KB in einer Hand ueber Kopf gestreckt.', 'Beuge dich seitlich zum Boden.', 'Blick zur KB, langsam zurueck.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 60,
  },
]
