import { Exercise } from './fitness-types'

// ============================================
// FitTutto - Erweiterte Uebungsbibliothek
// 150+ zusaetzliche Uebungen
// ============================================

export const EXERCISES_EXTENDED: Exercise[] = [
  // ==================== BRUST (erweitert) ====================
  {
    id: 'decline-bench-press', name: 'Negativ-Bankdruecken', nameEn: 'Decline Bench Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Bank auf -15 bis -30 Grad stellen.', 'Stange zur unteren Brust senken.', 'Explosiv hochdruecken.'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'svend-press', name: 'Svend Press', nameEn: 'Svend Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Halte eine Hantelscheibe mit beiden Haenden vor der Brust.', 'Druecke sie nach vorne und zusammen.', 'Langsam zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'pec-deck', name: 'Butterfly (Maschine)', nameEn: 'Pec Deck',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich an die Maschine, Arme auf den Polstern.', 'Fuehre die Arme vor der Brust zusammen.', 'Kontrolliert oeffnen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'landmine-press', name: 'Landmine Press', nameEn: 'Landmine Press',
    category: 'strength', primaryMuscles: ['chest', 'shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Klemme ein Stangenende in eine Ecke.', 'Halte das andere Ende mit beiden Haenden.', 'Druecke nach oben/vorne.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'diamond-push-ups', name: 'Diamant-Liegestuetze', nameEn: 'Diamond Push-Ups',
    category: 'bodyweight', primaryMuscles: ['chest', 'triceps'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Haende unter der Brust, Daumen und Zeigefinger bilden ein Dreieck.', 'Senke dich ab.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'incline-cable-fly', name: 'Schraegbank Kabel-Flys', nameEn: 'Incline Cable Fly',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['cable', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Bank auf 30-45 Grad, Kabel unten.', 'Fuehre die Griffe in einem Bogen ueber der Brust zusammen.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },

  // ==================== RUECKEN (erweitert) ====================
  {
    id: 'tbar-row', name: 'T-Bar Rudern', nameEn: 'T-Bar Row',
    category: 'strength', primaryMuscles: ['back', 'lats'], secondaryMuscles: ['biceps', 'traps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe ueber der Stange, V-Griff befestigt.', 'Ruecken gerade, Oberkoerper 45 Grad.', 'Ziehe zur Brust.'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'pendlay-row', name: 'Pendlay Row', nameEn: 'Pendlay Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'traps', 'lower_back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange am Boden, Oberkoerper parallel zum Boden.', 'Explosiv zur Brust ziehen.', 'Stange komplett ablegen.'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 120,
  },
  {
    id: 'chest-supported-row', name: 'Rudern mit Brustauflage', nameEn: 'Chest-Supported Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Lege dich baeuchlings auf eine Schraegbank.', 'Kurzhanteln haengend.', 'Ziehe beide Hanteln hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'meadows-row', name: 'Meadows Row', nameEn: 'Meadows Row',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'traps'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stehe seitlich zur Landmine.', 'Greife das Stangenende im Obergriff.', 'Ziehe explosiv zur Huefte.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', nameEn: 'Straight-Arm Pulldown',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['abs'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe vor dem oberen Kabelzug.', 'Arme gestreckt, ziehe die Stange zu den Oberschenkeln.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'inverted-row', name: 'Bodyweight Rudern', nameEn: 'Inverted Row',
    category: 'bodyweight', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Haenge unter einer niedrigen Stange.', 'Ziehe die Brust zur Stange.', 'Senke kontrolliert.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'rack-pull', name: 'Rack Pull', nameEn: 'Rack Pull',
    category: 'strength', primaryMuscles: ['back', 'traps'], secondaryMuscles: ['lower_back', 'forearms'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange im Rack auf Kniehoehe.', 'Greife schulterbreit.', 'Ziehe hoch, Schultern zurueck.'],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 120,
  },
  {
    id: 'wide-grip-pulldown', name: 'Weiter Latzug', nameEn: 'Wide-Grip Lat Pulldown',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Greife die Stange sehr breit.', 'Ziehe zur oberen Brust.', 'Schultern nach unten.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'close-grip-pulldown', name: 'Enger Latzug', nameEn: 'Close-Grip Pulldown',
    category: 'strength', primaryMuscles: ['lats', 'biceps'], secondaryMuscles: ['back'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['V-Griff am Latzug.', 'Ziehe zum Brustbein.', 'Ellbogen nah am Koerper.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'single-arm-lat-pulldown', name: 'Einarmiger Latzug', nameEn: 'Single-Arm Lat Pulldown',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps'],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Greife den Kabelgriff mit einer Hand.', 'Ziehe den Ellbogen zur Huefte.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== SCHULTERN (erweitert) ====================
  {
    id: 'cable-lateral-raise', name: 'Kabel-Seitheben', nameEn: 'Cable Lateral Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe seitlich zum unteren Kabelzug.', 'Hebe den Arm seitlich an.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'upright-row', name: 'Aufrechtes Rudern', nameEn: 'Upright Row',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['biceps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange eng greifen.', 'Ziehe entlang des Koerpers zum Kinn.', 'Ellbogen fuehren.'],
    tips: ['Vorsicht bei Schulterproblemen - Alternative: Seitheben'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'behind-neck-press', name: 'Nacken-Druecken', nameEn: 'Behind the Neck Press',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'traps'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange hinter dem Kopf auf den Schultern.', 'Druecke nach oben.', 'Nur mit guter Schulter-Mobilitaet!'],
    tips: ['Nur fuer erfahrene Sportler mit guter Schultermobilitaet'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'plate-front-raise', name: 'Frontheben mit Scheibe', nameEn: 'Plate Front Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Halte eine Hantelscheibe mit beiden Haenden.', 'Hebe sie auf Schulterhoehe.', 'Senke kontrolliert.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'lu-raise', name: 'Lu Raise', nameEn: 'Lu Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['traps'],
    equipment: ['dumbbell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Kurzhanteln seitlich.', 'Hebe seitlich auf 90 Grad.', 'Dann rotiere nach oben (wie ein Y).', 'Umgekehrt zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== ARME (erweitert) ====================
  {
    id: 'concentration-curl', name: 'Konzentrations-Curls', nameEn: 'Concentration Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Sitzend, Ellbogen am Oberschenkel.', 'Curle die Hantel nach oben.', 'Langsam senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'spider-curl', name: 'Spider Curls', nameEn: 'Spider Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['dumbbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Baeuchlings auf Schraegbank.', 'Arme haengen frei.', 'Curle nach oben.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'bayesian-curl', name: 'Bayesian Curl', nameEn: 'Bayesian Cable Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe mit dem Ruecken zum Kabelzug.', 'Greife den unteren Griff.', 'Curle nach vorne/oben.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'reverse-curl', name: 'Reverse Curls', nameEn: 'Reverse Curl',
    category: 'strength', primaryMuscles: ['forearms', 'biceps'], secondaryMuscles: [],
    equipment: ['barbell'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Greife die Stange im Obergriff.', 'Curle nach oben.', 'Langsam senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'tricep-kickback', name: 'Trizeps Kickback', nameEn: 'Tricep Kickback',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Beuge dich vor, Oberarm parallel zum Boden.', 'Strecke den Unterarm nach hinten.', 'Kontrolliert beugen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'rope-pushdown', name: 'Seil-Druecken am Kabel', nameEn: 'Rope Pushdown',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Seilgriff am oberen Kabelzug.', 'Druecke nach unten und spreize am Ende.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'jm-press', name: 'JM Press', nameEn: 'JM Press',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: ['chest'],
    equipment: ['barbell', 'bench'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Wie enges Bankdruecken, aber Stange zur Stirn/Nase senken.', 'Ellbogen fallen nach vorne.', 'Trizeps-Fokus.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },

  // ==================== BEINE (erweitert) ====================
  {
    id: 'hack-squat', name: 'Hack Squat', nameEn: 'Hack Squat',
    category: 'strength', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Ruecken ans Polster, Fuesse schulterbreit.', 'Senke kontrolliert ab.', 'Druecke durch die Fersen hoch.'],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 120,
  },
  {
    id: 'sissy-squat', name: 'Sissy Squat', nameEn: 'Sissy Squat',
    category: 'bodyweight', primaryMuscles: ['quads'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Stehe aufrecht, halte dich fest.', 'Lehne den Oberkoerper zurueck, Knie nach vorne.', 'Senke dich tief ab.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'leg-press-narrow', name: 'Beinpresse eng', nameEn: 'Narrow Stance Leg Press',
    category: 'strength', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Fuesse eng und tief auf der Platte.', 'Fokus auf Quadrizeps.', 'Voller Bewegungsumfang.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90,
  },
  {
    id: 'walking-lunges', name: 'Walking Lunges', nameEn: 'Walking Lunges',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell'], difficulty: 'intermediate', locations: ['gym', 'outdoor'],
    instructions: ['Kurzhanteln seitlich halten.', 'Grosse Schritte nach vorne.', 'Abwechselnd links und rechts.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90,
  },
  {
    id: 'step-ups', name: 'Step-Ups', nameEn: 'Step-Ups',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bench'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Stelle einen Fuss auf eine Bank/Box.', 'Druecke dich hoch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'sumo-deadlift', name: 'Sumo Kreuzheben', nameEn: 'Sumo Deadlift',
    category: 'strength', primaryMuscles: ['glutes', 'quads'], secondaryMuscles: ['hamstrings', 'back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Breiter Stand, Zehenspitzen nach aussen.', 'Greife die Stange eng.', 'Hebe durch Hueftstreckung.'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 180,
  },
  {
    id: 'stiff-leg-deadlift', name: 'Gestrecktes Kreuzheben', nameEn: 'Stiff-Leg Deadlift',
    category: 'strength', primaryMuscles: ['hamstrings'], secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Beine fast gestreckt.', 'Schiebe Hueften zurueck, Stange nah am Koerper.', 'Dehnung in den Beinbeugern spueren.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'nordic-hamstring-curl', name: 'Nordic Hamstring Curl', nameEn: 'Nordic Hamstring Curl',
    category: 'bodyweight', primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Knie auf dem Boden, Fuesse fixiert.', 'Lasse dich langsam nach vorne fallen.', 'Fange dich auf und druecke zurueck.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 120,
  },
  {
    id: 'good-morning', name: 'Good Mornings', nameEn: 'Good Morning',
    category: 'strength', primaryMuscles: ['hamstrings', 'lower_back'], secondaryMuscles: ['glutes'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange auf dem Ruecken.', 'Beuge den Oberkoerper nach vorne (Knie leicht gebeugt).', 'Richte dich auf.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'cable-pull-through', name: 'Cable Pull-Through', nameEn: 'Cable Pull-Through',
    category: 'strength', primaryMuscles: ['glutes', 'hamstrings'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe mit dem Ruecken zum Kabelzug.', 'Seilgriff zwischen den Beinen.', 'Hueften nach vorne stossen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'hip-abduction', name: 'Abduktoren (Maschine)', nameEn: 'Hip Abduction',
    category: 'strength', primaryMuscles: ['glutes'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine.', 'Oeffne die Beine gegen den Widerstand.', 'Kontrolliert schliessen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'hip-adduction', name: 'Adduktoren (Maschine)', nameEn: 'Hip Adduction',
    category: 'strength', primaryMuscles: ['hip_flexors'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine, Beine geoeffnet.', 'Schliesse die Beine.', 'Kontrolliert oeffnen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'donkey-calf-raise', name: 'Donkey Calf Raise', nameEn: 'Donkey Calf Raise',
    category: 'strength', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Beuge dich vor, Polster auf den Hueften.', 'Hebe die Fersen hoch.', 'Senke langsam ab.'],
    defaultSets: 4, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'single-leg-calf-raise', name: 'Einbeiniges Wadenheben', nameEn: 'Single-Leg Calf Raise',
    category: 'bodyweight', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Stehe auf einem Bein (auf einer Stufe).', 'Hebe dich auf die Zehenspitzen.', 'Senke tief ab, volle Dehnung.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== BAUCH (erweitert) ====================
  {
    id: 'cable-crunch', name: 'Kabel-Crunches', nameEn: 'Cable Crunch',
    category: 'strength', primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Knie vor dem Kabelzug.', 'Seilgriff hinter dem Kopf.', 'Rolle den Oberkoerper ein.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'decline-crunch', name: 'Crunches auf Negativbank', nameEn: 'Decline Crunch',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Lege dich auf die Negativbank, Fuesse fixiert.', 'Hebe den Oberkoerper hoch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'v-ups', name: 'V-Ups', nameEn: 'V-Ups',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Arme ueber dem Kopf.', 'Hebe Beine und Arme gleichzeitig.', 'Beruehre die Zehen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'dead-bug', name: 'Dead Bug', nameEn: 'Dead Bug',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Auf dem Ruecken, Arme und Beine in der Luft.', 'Strecke gegenueber Arm und Bein.', 'Wechsle die Seiten.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'bicycle-crunch', name: 'Fahrrad-Crunches', nameEn: 'Bicycle Crunch',
    category: 'bodyweight', primaryMuscles: ['abs', 'obliques'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Haende am Kopf.', 'Fuehre Ellbogen zum gegenueber Knie.', 'Radfahrbewegung.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },
  {
    id: 'side-plank', name: 'Seitlicher Plank', nameEn: 'Side Plank',
    category: 'bodyweight', primaryMuscles: ['obliques'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stuetze dich seitlich auf einen Unterarm.', 'Hebe die Huefte an.', 'Halte die Position.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 45,
  },
  {
    id: 'pallof-press', name: 'Pallof Press', nameEn: 'Pallof Press',
    category: 'strength', primaryMuscles: ['abs', 'obliques'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe seitlich zum Kabelzug.', 'Druecke den Griff vor die Brust.', 'Halte und widersetze der Rotation.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'dragon-flag', name: 'Dragon Flag', nameEn: 'Dragon Flag',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['lower_back'],
    equipment: ['bench'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Lege dich auf eine Bank, halte dich oben fest.', 'Hebe den gesamten Koerper als Brett.', 'Senke kontrolliert ab.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 120,
  },
  {
    id: 'toe-touches', name: 'Zehen-Beruehrung', nameEn: 'Toe Touches',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Beine senkrecht.', 'Hebe den Oberkoerper und beruehre die Zehen.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== COMPOUND / OLYMPISCH ====================
  {
    id: 'power-clean', name: 'Power Clean', nameEn: 'Power Clean',
    category: 'strength', primaryMuscles: ['quads', 'glutes', 'traps'], secondaryMuscles: ['shoulders', 'back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange am Boden, greife schulterbreit.', 'Explosiv hochziehen (1. Pull).', 'Unter die Stange springen (Catch).'],
    defaultSets: 4, defaultReps: 3, defaultRestSeconds: 180,
  },
  {
    id: 'hang-clean', name: 'Hang Clean', nameEn: 'Hang Clean',
    category: 'strength', primaryMuscles: ['quads', 'traps'], secondaryMuscles: ['glutes', 'shoulders'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange auf Kniehoehe halten.', 'Explosiv nach oben ziehen.', 'Unter die Stange springen.'],
    defaultSets: 4, defaultReps: 3, defaultRestSeconds: 180,
  },
  {
    id: 'snatch', name: 'Snatch (Reissen)', nameEn: 'Snatch',
    category: 'strength', primaryMuscles: ['shoulders', 'quads', 'glutes'], secondaryMuscles: ['traps', 'back'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Breiter Griff, Stange am Boden.', 'Explosiv hochziehen.', 'Unter die Stange springen, Arme gestreckt.'],
    defaultSets: 4, defaultReps: 2, defaultRestSeconds: 180,
  },
  {
    id: 'push-press', name: 'Push Press', nameEn: 'Push Press',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'quads'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stange auf den Schultern.', 'Leichtes Einbeugen der Knie.', 'Explosiv hochdruecken mit Beinunterstuetzung.'],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 120,
  },

  // ==================== CARDIO (erweitert) ====================
  {
    id: 'rowing-machine', name: 'Rudergeraet', nameEn: 'Rowing Machine',
    category: 'cardio', primaryMuscles: ['back', 'quads'], secondaryMuscles: ['biceps', 'abs'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Fuesse fixieren, Griff greifen.', 'Zuerst Beine strecken, dann Arme ziehen.', 'Kontrolliert zurueck.'],
    defaultSets: 1, defaultReps: 300, defaultRestSeconds: 0,
  },
  {
    id: 'assault-bike', name: 'Assault Bike', nameEn: 'Assault Bike',
    category: 'cardio', primaryMuscles: ['quads', 'shoulders'], secondaryMuscles: ['abs', 'calves'],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Setze dich aufs Bike.', 'Haende an die Griffe.', 'Trete und druecke/ziehe gleichzeitig.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 60,
  },
  {
    id: 'sled-push', name: 'Schlittenpressen', nameEn: 'Sled Push',
    category: 'cardio', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves', 'shoulders'],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Haende an die Griffe des Schlittens.', 'Druecke mit voller Kraft nach vorne.', 'Koerper leicht nach vorne geneigt.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 90,
  },
  {
    id: 'high-knees', name: 'Kniehebelauf', nameEn: 'High Knees',
    category: 'cardio', primaryMuscles: ['quads', 'hip_flexors'], secondaryMuscles: ['calves', 'abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Laufe auf der Stelle.', 'Ziehe die Knie abwechselnd hoch.', 'Arme mitschwingen.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 30,
  },
  {
    id: 'skater-hops', name: 'Skater Hops', nameEn: 'Skater Hops',
    category: 'cardio', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Springe seitlich von einem Bein aufs andere.', 'Wie ein Eisschnelllaeufer.', 'Arme mitschwingen.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },

  // ==================== BEWEGLICHKEIT (erweitert) ====================
  {
    id: 'world-greatest-stretch', name: "World's Greatest Stretch", nameEn: "World's Greatest Stretch",
    category: 'flexibility', primaryMuscles: ['hip_flexors', 'hamstrings'], secondaryMuscles: ['shoulders', 'obliques'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Ausfallschritt, Hand am Boden.', 'Drehe den Oberkoerper zur offenen Seite.', 'Halte 15 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 5, defaultRestSeconds: 0,
  },
  {
    id: 'thoracic-rotation', name: 'Brustwirbel-Rotation', nameEn: 'Thoracic Rotation',
    category: 'flexibility', primaryMuscles: ['obliques'], secondaryMuscles: ['back'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Vierfuesslerstand.', 'Hand hinter den Kopf.', 'Drehe den Oberkoerper zur Seite, oeffne die Brust.'],
    defaultSets: 2, defaultReps: 10, defaultRestSeconds: 0,
  },
  {
    id: 'hamstring-stretch', name: 'Beinbeuger-Dehnung', nameEn: 'Hamstring Stretch',
    category: 'flexibility', primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Strecke ein Bein auf einer erhoehten Flaeche.', 'Beuge dich mit geradem Ruecken nach vorne.', 'Halte 30 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'chest-doorway-stretch', name: 'Brust-Dehnung im Tuerhrahmen', nameEn: 'Doorway Chest Stretch',
    category: 'flexibility', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['home'],
    instructions: ['Arme an den Tuerrahmen, 90 Grad.', 'Einen Schritt nach vorne.', 'Dehnung in der Brust spueren.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'couch-stretch', name: 'Couch Stretch', nameEn: 'Couch Stretch',
    category: 'flexibility', primaryMuscles: ['hip_flexors', 'quads'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['home', 'gym'],
    instructions: ['Knie an einer Wand, Fuss zeigt nach oben.', 'Vorderes Bein aufgestellt (90 Grad).', 'Aufrechthalten, 60 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'lat-stretch', name: 'Latissimus-Dehnung', nameEn: 'Lat Stretch',
    category: 'flexibility', primaryMuscles: ['lats'], secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Greife eine Stange oder Tuerrahmen auf Kopfhoehe.', 'Lehne dich zurueck und zur Seite.', 'Dehnung im Lat spueren.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },

  // ==================== HOME / RESISTANCE BAND ====================
  {
    id: 'band-pull-apart', name: 'Band Pull-Apart', nameEn: 'Band Pull-Apart',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['back'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Halte das Band vor dir auf Schulterhoehe.', 'Ziehe es auseinander.', 'Druecke die Schulterblaetter zusammen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 30,
  },
  {
    id: 'band-squat', name: 'Band Kniebeugen', nameEn: 'Banded Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: [],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Band unter den Fuessen, Enden in den Haenden.', 'Kniebeugen mit Widerstand.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-row', name: 'Band Rudern', nameEn: 'Banded Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Setze dich hin, Band um die Fuesse.', 'Ziehe die Enden zum Bauch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-chest-press', name: 'Band Brustdruecken', nameEn: 'Banded Chest Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Band hinter dem Ruecken, Enden in den Haenden.', 'Druecke nach vorne.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-face-pull', name: 'Band Face Pull', nameEn: 'Banded Face Pull',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['back'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'gym'],
    instructions: ['Band an einer Tuer oder Stange befestigt.', 'Ziehe zum Gesicht mit Ellbogen hoch.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 30,
  },

  // ==================== TRX / SCHLINGENTRAINER ====================
  {
    id: 'trx-row', name: 'TRX Rudern', nameEn: 'TRX Row',
    category: 'bodyweight', primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['trx'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Greife die TRX-Griffe, lehne dich zurueck.', 'Ziehe die Brust zu den Haenden.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'trx-chest-press', name: 'TRX Brustdruecken', nameEn: 'TRX Chest Press',
    category: 'bodyweight', primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['trx'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Haende in den TRX-Griffen, Koerper geneigt.', 'Senke dich ab wie bei Liegestuetzen.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'trx-pike', name: 'TRX Pike', nameEn: 'TRX Pike',
    category: 'bodyweight', primaryMuscles: ['abs', 'shoulders'], secondaryMuscles: ['hip_flexors'],
    equipment: ['trx'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Fuesse in den TRX-Schlaufen, Liegestuetzposition.', 'Ziehe die Hueften hoch zum Pike.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== KETTLEBELL (erweitert) ====================
  {
    id: 'kb-goblet-squat', name: 'Kettlebell Goblet Squat', nameEn: 'KB Goblet Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['abs'],
    equipment: ['kettlebell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Halte die KB vor der Brust.', 'Tiefe Kniebeuge.', 'Druecke durch die Fersen hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'kb-clean-press', name: 'KB Clean & Press', nameEn: 'KB Clean & Press',
    category: 'strength', primaryMuscles: ['shoulders', 'glutes'], secondaryMuscles: ['back', 'abs'],
    equipment: ['kettlebell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['KB zwischen den Beinen schwingen.', 'Umsetzen zur Schulter.', 'Ueber Kopf druecken.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'kb-snatch', name: 'Kettlebell Snatch', nameEn: 'KB Snatch',
    category: 'strength', primaryMuscles: ['shoulders', 'glutes'], secondaryMuscles: ['back', 'abs'],
    equipment: ['kettlebell'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['KB einarmig schwingen.', 'In einer Bewegung ueber Kopf reissen.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'kb-windmill', name: 'Kettlebell Windmill', nameEn: 'KB Windmill',
    category: 'strength', primaryMuscles: ['obliques', 'shoulders'], secondaryMuscles: ['hip_flexors'],
    equipment: ['kettlebell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['KB in einer Hand ueber Kopf gestreckt.', 'Beuge dich seitlich zum Boden.', 'Blick zur KB, langsam zurueck.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 60,
  },

  // ==================== BRUST (zusaetzlich) ====================
  {
    id: 'floor-press-db', name: 'Floor Press (Kurzhanteln)', nameEn: 'Dumbbell Floor Press',
    category: 'strength', primaryMuscles: ['chest', 'triceps'], secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Auf dem Ruecken liegend, Knie gebeugt.', 'Druecke die Hanteln nach oben.', 'Ellbogen beruehren den Boden.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'hex-press', name: 'Hex Press', nameEn: 'Hex Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Hanteln zusammendruecken ueber der Brust.', 'Druecke nach oben, Hanteln bleiben zusammen.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'decline-cable-fly', name: 'Negativ Cable Fly', nameEn: 'Decline Cable Fly',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Kabel oben, Schritt nach vorne.', 'Fuehre die Griffe nach unten und zusammen.', 'Kontrolliert oeffnen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'close-grip-bench', name: 'Enges Bankdruecken', nameEn: 'Close-Grip Bench Press',
    category: 'strength', primaryMuscles: ['triceps', 'chest'], secondaryMuscles: ['shoulders'],
    equipment: ['barbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Greife die Stange schulterbreit oder enger.', 'Senke zur Brust, Ellbogen am Koerper.', 'Explosiv hochdruecken.'],
    defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'wide-push-ups', name: 'Breite Liegestuetze', nameEn: 'Wide Push-Ups',
    category: 'bodyweight', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Haende deutlich weiter als schulterbreit.', 'Senke die Brust zum Boden.', 'Druecke dich hoch.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'archer-push-ups', name: 'Archer Push-Ups', nameEn: 'Archer Push-Ups',
    category: 'bodyweight', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Sehr breite Handposition.', 'Senke dich zu einer Seite, anderer Arm streckt sich.', 'Wechsle die Seiten.'],
    defaultSets: 3, defaultReps: 6, defaultRestSeconds: 90,
  },
  {
    id: 'db-pullover', name: 'Kurzhantel Pullover', nameEn: 'Dumbbell Pullover',
    category: 'strength', primaryMuscles: ['chest', 'lats'], secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Quer auf der Bank liegend.', 'Hantel ueber dem Kopf nach hinten fuehren.', 'Zurueck ueber die Brust.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },

  // ==================== RUECKEN (zusaetzlich) ====================
  {
    id: 'seal-row', name: 'Seal Row', nameEn: 'Seal Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'traps'],
    equipment: ['dumbbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Baeuchlings auf erhoehter Bank, Arme haengen frei.', 'Ziehe beide Hanteln hoch.', 'Kein Schwung moeglich.'],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'kroc-row', name: 'Kroc Row', nameEn: 'Kroc Row',
    category: 'strength', primaryMuscles: ['lats', 'back'], secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['dumbbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Schwere Kurzhantel, eine Hand an der Bank.', 'Hohe Wiederholungen, etwas Schwung erlaubt.', 'Maximaler Lat-Stretch.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 120,
  },
  {
    id: 'machine-pullover', name: 'Pullover Maschine', nameEn: 'Machine Pullover',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['chest'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine, Arme an den Polstern.', 'Ziehe den Bogen nach unten.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'db-shrug', name: 'Kurzhantel Shrugs', nameEn: 'Dumbbell Shrugs',
    category: 'strength', primaryMuscles: ['traps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Kurzhanteln seitlich halten.', 'Schultern hochziehen (Achselzucken).', 'Oben kurz halten, langsam senken.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'barbell-shrug', name: 'Langhantel Shrugs', nameEn: 'Barbell Shrugs',
    category: 'strength', primaryMuscles: ['traps'], secondaryMuscles: ['forearms'],
    equipment: ['barbell'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stange schulterbreit vor dem Koerper.', 'Schultern hochziehen.', 'Halte oben kurz, kontrolliert senken.'],
    defaultSets: 4, defaultReps: 12, defaultRestSeconds: 60,
  },

  // ==================== SCHULTERN (zusaetzlich) ====================
  {
    id: 'z-press', name: 'Z-Press', nameEn: 'Z-Press',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'abs'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Sitzend auf dem Boden, Beine gestreckt.', 'Stange auf den Schultern.', 'Druecke ueber Kopf ohne Rueckenlehne.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 120,
  },
  {
    id: 'cable-y-raise', name: 'Cable Y-Raise', nameEn: 'Cable Y-Raise',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Kabel unten, Griffe ueberkreuz.', 'Hebe die Arme in ein Y.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'bus-driver', name: 'Bus Driver', nameEn: 'Bus Driver',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Hantelscheibe vor dir halten, Arme gestreckt.', 'Rotiere wie ein Lenkrad.', 'Arme die ganze Zeit oben halten.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'rear-delt-fly-cable', name: 'Kabel Reverse Fly', nameEn: 'Cable Rear Delt Fly',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['traps'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Kabel auf Schulterhoehe, ueberkreuz greifen.', 'Ziehe die Arme nach aussen.', 'Schulterblaetter zusammen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'db-front-raise', name: 'Kurzhantel Frontheben', nameEn: 'Dumbbell Front Raise',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Kurzhanteln vor den Oberschenkeln.', 'Hebe abwechselnd auf Schulterhoehe.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'shoulder-press-machine', name: 'Schulterpresse Maschine', nameEn: 'Shoulder Press Machine',
    category: 'strength', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine, Griffe auf Schulterhoehe.', 'Druecke nach oben.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },

  // ==================== ARME (zusaetzlich) ====================
  {
    id: 'preacher-curl', name: 'Preacher Curl', nameEn: 'Preacher Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['ez_bar'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Arme auf der Preacher-Bank, SZ-Stange greifen.', 'Curle nach oben.', 'Langsam und kontrolliert senken.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'french-press', name: 'French Press', nameEn: 'French Press',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Liegend, SZ-Stange ueber dem Kopf.', 'Senke zur Stirn, nur Unterarme bewegen.', 'Strecke die Arme.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'cross-body-curl', name: 'Cross-Body Curl', nameEn: 'Cross-Body Hammer Curl',
    category: 'strength', primaryMuscles: ['biceps', 'forearms'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Kurzhanteln seitlich, Hammergriff.', 'Curle quer ueber den Koerper.', 'Abwechselnd links und rechts.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'overhead-tricep-ext', name: 'Ueberkopf Trizepsstrecker', nameEn: 'Overhead Tricep Extension',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Kurzhantel beidhaendig ueber dem Kopf.', 'Senke hinter den Kopf.', 'Strecke die Arme.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'cable-curl', name: 'Kabel Bizeps Curl', nameEn: 'Cable Bicep Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stehe vor dem unteren Kabelzug.', 'Curle die Stange nach oben.', 'Langsam zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'diamond-close-grip-pushup', name: 'Enge Liegestuetze', nameEn: 'Close-Grip Push-Up',
    category: 'bodyweight', primaryMuscles: ['triceps'], secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Haende eng zusammen, direkt unter der Brust.', 'Senke den Koerper ab, Ellbogen nah am Koerper.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'wrist-curl', name: 'Handgelenk-Curl', nameEn: 'Wrist Curl',
    category: 'strength', primaryMuscles: ['forearms'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Unterarme auf den Oberschenkeln, Handgelenke frei.', 'Curle die Hanteln mit den Handgelenken.', 'Langsam zurueck.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },

  // ==================== BEINE (zusaetzlich) ====================
  {
    id: 'belt-squat', name: 'Belt Squat', nameEn: 'Belt Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Gurt um die Huefte, Gewicht haengt unten.', 'Kniebeuge ohne Wirbelsaeulenbelastung.', 'Ideal bei Rueckenproblemen.'],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'front-squat', name: 'Front Squat', nameEn: 'Front Squat',
    category: 'strength', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'abs'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stange auf den vorderen Schultern (Front Rack).', 'Aufrechter Oberkoerper, tiefe Kniebeuge.', 'Druecke durch die Fersen hoch.'],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 150,
  },
  {
    id: 'goblet-squat-db', name: 'Goblet Squat (Kurzhantel)', nameEn: 'Dumbbell Goblet Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['abs'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Kurzhantel vertikal vor der Brust halten.', 'Tiefe Kniebeuge.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'pause-squat', name: 'Pause Squat', nameEn: 'Pause Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['abs'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Normale Kniebeuge, aber 2-3 Sekunden am tiefsten Punkt pausieren.', 'Kein Schwung beim Aufstehen.', 'Explosiv ausdruecken.'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 150,
  },
  {
    id: 'trap-bar-deadlift', name: 'Trap Bar Kreuzheben', nameEn: 'Trap Bar Deadlift',
    category: 'strength', primaryMuscles: ['quads', 'glutes', 'hamstrings'], secondaryMuscles: ['back', 'traps'],
    equipment: ['barbell'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe in der Trap Bar, greife die Griffe.', 'Hebe mit geradem Ruecken.', 'Strecke Hueften und Knie gleichzeitig.'],
    defaultSets: 4, defaultReps: 6, defaultRestSeconds: 150,
  },
  {
    id: 'deficit-deadlift', name: 'Deficit Kreuzheben', nameEn: 'Deficit Deadlift',
    category: 'strength', primaryMuscles: ['hamstrings', 'glutes', 'back'], secondaryMuscles: ['quads'],
    equipment: ['barbell'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Stehe auf einer Erhoehung (5-10cm).', 'Greife die Stange wie beim normalen Kreuzheben.', 'Erhoehter Bewegungsumfang.'],
    defaultSets: 4, defaultReps: 5, defaultRestSeconds: 180,
  },
  {
    id: 'glute-ham-raise', name: 'Glute Ham Raise', nameEn: 'GHR',
    category: 'strength', primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['lower_back'],
    equipment: ['machine'], difficulty: 'advanced', locations: ['gym'],
    instructions: ['Fuesse im GHD-Geraet fixiert.', 'Senke den Oberkoerper nach vorne.', 'Ziehe dich mit den Beinbeugern zurueck.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'leg-extension', name: 'Beinstrecker', nameEn: 'Leg Extension',
    category: 'strength', primaryMuscles: ['quads'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine, Polster auf dem Schienbein.', 'Strecke die Beine.', 'Oben kurz halten, kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'seated-leg-curl', name: 'Sitzender Beinbeuger', nameEn: 'Seated Leg Curl',
    category: 'strength', primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich in die Maschine.', 'Curle die Beine nach hinten.', 'Kontrolliert strecken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'standing-calf-raise-machine', name: 'Stehendes Wadenheben Maschine', nameEn: 'Standing Calf Raise Machine',
    category: 'strength', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Schultern unter die Polster, Fussballen auf der Kante.', 'Hebe die Fersen hoch.', 'Senke tief ab, volle Dehnung.'],
    defaultSets: 4, defaultReps: 15, defaultRestSeconds: 60,
  },
  {
    id: 'reverse-lunge', name: 'Reverse Lunges', nameEn: 'Reverse Lunge',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Kurzhanteln seitlich halten.', 'Tritt einen grossen Schritt zurueck.', 'Senke das Knie Richtung Boden, druecke zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },

  // ==================== BODYWEIGHT (zusaetzlich) ====================
  {
    id: 'muscle-up', name: 'Muscle-Up', nameEn: 'Muscle-Up',
    category: 'bodyweight', primaryMuscles: ['back', 'chest', 'triceps'], secondaryMuscles: ['shoulders', 'biceps'],
    equipment: ['pull_up_bar'], difficulty: 'advanced', locations: ['gym', 'outdoor'],
    instructions: ['Haenge an der Stange, Schwung holen.', 'Explosiv hochziehen und ueber die Stange druecken.', 'Dip oben, kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 3, defaultRestSeconds: 180,
  },
  {
    id: 'pike-push-up', name: 'Pike Push-Up', nameEn: 'Pike Push-Up',
    category: 'bodyweight', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Umgekehrtes V, Hueften hoch.', 'Senke den Kopf zum Boden.', 'Druecke zurueck hoch.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'pistol-squat', name: 'Pistol Squat', nameEn: 'Pistol Squat',
    category: 'bodyweight', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings', 'abs'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stehe auf einem Bein, anderes gestreckt nach vorne.', 'Senke dich tief auf einem Bein.', 'Druecke dich hoch.'],
    defaultSets: 3, defaultReps: 5, defaultRestSeconds: 90,
  },
  {
    id: 'l-sit', name: 'L-Sit', nameEn: 'L-Sit',
    category: 'bodyweight', primaryMuscles: ['abs', 'hip_flexors'], secondaryMuscles: ['triceps'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Haende auf Parallettes oder Boden.', 'Hebe den Koerper, Beine gestreckt nach vorne.', 'Halte die Position.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 90,
  },
  {
    id: 'hollow-body-hold', name: 'Hollow Body Hold', nameEn: 'Hollow Body Hold',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Auf dem Ruecken, Arme ueber dem Kopf gestreckt.', 'Hebe Arme, Schultern und Beine leicht an.', 'Unterer Ruecken am Boden, Position halten.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 60,
  },
  {
    id: 'planche-lean', name: 'Planche Lean', nameEn: 'Planche Lean',
    category: 'bodyweight', primaryMuscles: ['shoulders', 'chest'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Liegestuetzposition, Haende auf Huefthoehe.', 'Lehne den Koerper nach vorne ueber die Haende.', 'Halte die Position.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 90,
  },
  {
    id: 'handstand-push-up', name: 'Handstand Push-Up', nameEn: 'Handstand Push-Up',
    category: 'bodyweight', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'traps'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Handstand an der Wand.', 'Senke den Kopf zum Boden.', 'Druecke dich hoch.'],
    defaultSets: 3, defaultReps: 5, defaultRestSeconds: 120,
  },
  {
    id: 'box-jump', name: 'Box Jumps', nameEn: 'Box Jump',
    category: 'bodyweight', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Stehe vor einer stabilen Box.', 'Springe explosiv drauf.', 'Steige kontrolliert herunter.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'burpees', name: 'Burpees', nameEn: 'Burpees',
    category: 'bodyweight', primaryMuscles: ['quads', 'chest'], secondaryMuscles: ['shoulders', 'abs', 'glutes'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stehe aufrecht.', 'Springe in die Liegestuetzposition.', 'Liegestuetz, Springe auf, Springe hoch.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'commando-pull-up', name: 'Commando Pull-Up', nameEn: 'Commando Pull-Up',
    category: 'bodyweight', primaryMuscles: ['back', 'biceps'], secondaryMuscles: ['obliques'],
    equipment: ['pull_up_bar'], difficulty: 'advanced', locations: ['gym', 'outdoor'],
    instructions: ['Stehe seitlich zur Stange, Haende hintereinander.', 'Ziehe dich hoch, Kopf abwechselnd links und rechts.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'mountain-climbers', name: 'Mountain Climbers', nameEn: 'Mountain Climbers',
    category: 'bodyweight', primaryMuscles: ['abs', 'hip_flexors'], secondaryMuscles: ['shoulders', 'quads'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Liegestuetzposition.', 'Ziehe abwechselnd die Knie zur Brust.', 'Schnell und kontrolliert.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 45,
  },
  {
    id: 'bear-crawl', name: 'Bear Crawl', nameEn: 'Bear Crawl',
    category: 'bodyweight', primaryMuscles: ['shoulders', 'abs'], secondaryMuscles: ['quads', 'triceps'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Vierfuesslerstand, Knie knapp ueber dem Boden.', 'Bewege dich vorwaerts: gegengleiches Hand-Fuss-Paar.', 'Hueften niedrig halten.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 60,
  },
  {
    id: 'crab-walk', name: 'Crab Walk', nameEn: 'Crab Walk',
    category: 'bodyweight', primaryMuscles: ['triceps', 'glutes'], secondaryMuscles: ['shoulders', 'abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Setze dich, Haende hinter dir, Fuesse aufgestellt.', 'Hebe die Hueften an.', 'Bewege dich vorwaerts oder rueckwaerts.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },
  {
    id: 'tuck-jump', name: 'Tuck Jumps', nameEn: 'Tuck Jump',
    category: 'bodyweight', primaryMuscles: ['quads', 'calves'], secondaryMuscles: ['glutes', 'abs'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stehe hueftbreit.', 'Springe hoch und ziehe die Knie zur Brust.', 'Lande weich und wiederhole.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'shrimp-squat', name: 'Shrimp Squat', nameEn: 'Shrimp Squat',
    category: 'bodyweight', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Stehe auf einem Bein, anderes Bein hinter dir greifen.', 'Senke das Knie zum Boden.', 'Druecke dich hoch.'],
    defaultSets: 3, defaultReps: 5, defaultRestSeconds: 90,
  },

  // ==================== CARDIO (zusaetzlich) ====================
  {
    id: 'jump-rope', name: 'Seilspringen', nameEn: 'Jump Rope',
    category: 'cardio', primaryMuscles: ['calves'], secondaryMuscles: ['quads', 'shoulders', 'abs'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Springseil greifen, Ellbogen am Koerper.', 'Springe mit kleinen Spruengen.', 'Handgelenke drehen das Seil.'],
    defaultSets: 3, defaultReps: 60, defaultRestSeconds: 30,
  },
  {
    id: 'jump-rope-double-under', name: 'Double Unders', nameEn: 'Double Under Jump Rope',
    category: 'cardio', primaryMuscles: ['calves'], secondaryMuscles: ['shoulders', 'abs'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['gym', 'outdoor'],
    instructions: ['Springseil, aber das Seil dreht sich 2x pro Sprung.', 'Hoeher springen, schneller drehen.', 'Rhythmus halten.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 60,
  },
  {
    id: 'battle-ropes', name: 'Battle Ropes', nameEn: 'Battle Ropes',
    category: 'cardio', primaryMuscles: ['shoulders'], secondaryMuscles: ['abs', 'back', 'biceps'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Greife die Seile, leichte Kniebeuge.', 'Schlage die Seile abwechselnd auf und ab.', 'Maximale Intensitaet.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 60,
  },
  {
    id: 'sprint-intervals', name: 'Sprint-Intervalle', nameEn: 'Sprint Intervals',
    category: 'cardio', primaryMuscles: ['quads', 'hamstrings', 'glutes'], secondaryMuscles: ['calves', 'abs'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['outdoor'],
    instructions: ['Laufe 30 Sekunden mit voller Geschwindigkeit.', '60 Sekunden Gehen oder leichtes Joggen.', 'Wiederhole 8-10 Mal.'],
    defaultSets: 8, defaultReps: 30, defaultRestSeconds: 60,
  },
  {
    id: 'hill-sprints', name: 'Bergsprints', nameEn: 'Hill Sprints',
    category: 'cardio', primaryMuscles: ['quads', 'glutes', 'calves'], secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'], difficulty: 'advanced', locations: ['outdoor'],
    instructions: ['Finde einen steilen Huegel.', 'Sprinte nach oben mit maximaler Anstrengung.', 'Gehe zurueck, wiederhole.'],
    defaultSets: 6, defaultReps: 1, defaultRestSeconds: 120,
  },
  {
    id: 'stair-climber', name: 'Treppensteiger', nameEn: 'Stair Climber',
    category: 'cardio', primaryMuscles: ['quads', 'glutes', 'calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze ein moderates Tempo.', 'Ganze Fusssohle auf die Stufe.', 'Gleichmaessiger Rhythmus, aufrecht stehen.'],
    defaultSets: 1, defaultReps: 600, defaultRestSeconds: 0,
  },
  {
    id: 'elliptical', name: 'Crosstrainer', nameEn: 'Elliptical',
    category: 'cardio', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['shoulders', 'back'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Fuesse auf die Pedale, Haende an die Griffe.', 'Gleichmaessig treten und Arme mitschieben.', 'Widerstand nach Bedarf anpassen.'],
    defaultSets: 1, defaultReps: 900, defaultRestSeconds: 0,
  },
  {
    id: 'shuttle-run', name: 'Shuttle Run', nameEn: 'Shuttle Run',
    category: 'cardio', primaryMuscles: ['quads', 'calves'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['outdoor', 'gym'],
    instructions: ['Markiere 2 Punkte im Abstand von 20m.', 'Sprinte hin und zurueck.', 'Schnelle Richtungswechsel.'],
    defaultSets: 5, defaultReps: 4, defaultRestSeconds: 60,
  },
  {
    id: 'jumping-jacks', name: 'Hampelmaenner', nameEn: 'Jumping Jacks',
    category: 'cardio', primaryMuscles: ['calves', 'shoulders'], secondaryMuscles: ['quads'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stehe aufrecht, Arme seitlich.', 'Springe, spreize Beine und hebe Arme.', 'Springe zurueck in die Ausgangsposition.'],
    defaultSets: 3, defaultReps: 30, defaultRestSeconds: 30,
  },
  {
    id: 'speed-skaters', name: 'Speed Skaters', nameEn: 'Speed Skaters',
    category: 'cardio', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves', 'obliques'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Springe seitlich auf ein Bein.', 'Anderes Bein kreuzt hinter dem Standbein.', 'Wechsle dynamisch die Seiten.'],
    defaultSets: 3, defaultReps: 20, defaultRestSeconds: 45,
  },

  // ==================== BEWEGLICHKEIT (zusaetzlich) ====================
  {
    id: 'pigeon-pose', name: 'Taube (Pigeon Pose)', nameEn: 'Pigeon Pose',
    category: 'flexibility', primaryMuscles: ['glutes', 'hip_flexors'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Ein Bein angewinkelt vor dir, anderes gestreckt nach hinten.', 'Senke den Oberkoerper nach vorne.', 'Halte 60 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'frog-stretch', name: 'Frosch-Stretch', nameEn: 'Frog Stretch',
    category: 'flexibility', primaryMuscles: ['hip_flexors', 'glutes'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Knie am Boden, Beine weit gespreizt.', 'Schiebe die Hueften nach hinten.', 'Dehnung in der Leiste spueren.'],
    defaultSets: 2, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: '90-90-stretch', name: '90/90 Stretch', nameEn: '90/90 Hip Stretch',
    category: 'flexibility', primaryMuscles: ['glutes', 'hip_flexors'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Sitzend, vorderes Bein 90 Grad gebeugt, hinteres Bein 90 Grad seitlich.', 'Oberkoerper aufrecht.', 'Lehne dich ueber das vordere Bein.'],
    defaultSets: 2, defaultReps: 45, defaultRestSeconds: 0,
  },
  {
    id: 'cat-cow', name: 'Cat-Cow', nameEn: 'Cat-Cow Stretch',
    category: 'flexibility', primaryMuscles: ['back', 'abs'], secondaryMuscles: ['lower_back'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Vierfuesslerstand.', 'Rundruecken (Katze), dann Hohlruecken (Kuh).', 'Langsam und kontrolliert wechseln.'],
    defaultSets: 2, defaultReps: 10, defaultRestSeconds: 0,
  },
  {
    id: 'childs-pose', name: "Child's Pose", nameEn: "Child's Pose",
    category: 'flexibility', primaryMuscles: ['back', 'lats'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Knie am Boden, setze dich auf die Fersen.', 'Arme nach vorne strecken, Stirn zum Boden.', 'Atme tief, halte 60 Sekunden.'],
    defaultSets: 2, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'thread-the-needle', name: 'Thread the Needle', nameEn: 'Thread the Needle',
    category: 'flexibility', primaryMuscles: ['obliques', 'back'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Vierfuesslerstand.', 'Fuehre einen Arm unter dem Koerper durch.', 'Rotation im oberen Ruecken, Schulter zum Boden.'],
    defaultSets: 2, defaultReps: 8, defaultRestSeconds: 0,
  },
  {
    id: 'quad-stretch-standing', name: 'Stehende Quad-Dehnung', nameEn: 'Standing Quad Stretch',
    category: 'flexibility', primaryMuscles: ['quads'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stehe auf einem Bein.', 'Ziehe den anderen Fuss zum Gesaess.', 'Halte 30 Sekunden pro Seite.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'shoulder-cars', name: 'Schulter CARs', nameEn: 'Shoulder CARs',
    category: 'flexibility', primaryMuscles: ['shoulders'], secondaryMuscles: ['traps'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Stehe aufrecht, Arm seitlich.', 'Fuehre den Arm langsam in einem grossen Kreis.', 'Maximaler Bewegungsumfang, kontrolliert.'],
    defaultSets: 2, defaultReps: 5, defaultRestSeconds: 0,
  },
  {
    id: 'hip-cars', name: 'Huefte CARs', nameEn: 'Hip CARs',
    category: 'flexibility', primaryMuscles: ['hip_flexors', 'glutes'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Stehe auf einem Bein, halte dich fest.', 'Fuehre das Knie in einem grossen Kreis.', 'Vorwaerts und rueckwaerts kreisen.'],
    defaultSets: 2, defaultReps: 5, defaultRestSeconds: 0,
  },
  {
    id: 'ankle-mobility-drill', name: 'Sprunggelenk Mobilitaet', nameEn: 'Ankle Mobility Drill',
    category: 'flexibility', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Fuss an einer Wand, Knie nach vorne druecken.', 'Ferse bleibt am Boden.', 'Halte 30 Sekunden, dann wechseln.'],
    defaultSets: 2, defaultReps: 30, defaultRestSeconds: 0,
  },
  {
    id: 'foam-roll-back', name: 'Faszienrolle Ruecken', nameEn: 'Foam Roll Back',
    category: 'flexibility', primaryMuscles: ['back'], secondaryMuscles: ['lats'],
    equipment: ['foam_roller'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Lege dich mit dem oberen Ruecken auf die Rolle.', 'Arme vor der Brust verschraenkt.', 'Rolle langsam hoch und runter.'],
    defaultSets: 1, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'foam-roll-quads', name: 'Faszienrolle Quadrizeps', nameEn: 'Foam Roll Quads',
    category: 'flexibility', primaryMuscles: ['quads'], secondaryMuscles: [],
    equipment: ['foam_roller'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Baeuchlings, Rolle unter den Oberschenkeln.', 'Rolle langsam vom Knie zur Huefte.', 'Druckpunkte bearbeiten.'],
    defaultSets: 1, defaultReps: 60, defaultRestSeconds: 0,
  },
  {
    id: 'foam-roll-it-band', name: 'Faszienrolle IT-Band', nameEn: 'Foam Roll IT Band',
    category: 'flexibility', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['foam_roller'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Seitlich auf der Rolle, oberes Bein vor dem Koerper.', 'Rolle die Aussenseite des Oberschenkels.', 'Langsam und gruendlich.'],
    defaultSets: 1, defaultReps: 60, defaultRestSeconds: 0,
  },

  // ==================== WEITERE KRAFT ====================
  {
    id: 'smith-squat', name: 'Multipresse Kniebeuge', nameEn: 'Smith Machine Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['smith_machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Stange auf den Schultern, Fuesse leicht vorn.', 'Senke kontrolliert.', 'Druecke hoch.'],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'smith-bench-press', name: 'Multipresse Bankdruecken', nameEn: 'Smith Machine Bench Press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['smith_machine', 'bench'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Bank unter die Multipresse, Stange zur Brust senken.', 'Druecke hoch.', 'Gute Alternative fuer Anfaenger.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'incline-db-row', name: 'Schraegbank KH-Rudern', nameEn: 'Incline Dumbbell Row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'traps'],
    equipment: ['dumbbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Bank auf 30 Grad, baeuchlings anlehnen.', 'Hanteln haengen lassen.', 'Ziehe beide Hanteln zum Bauch.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'high-cable-curl', name: 'Hoher Kabel-Curl', nameEn: 'High Cable Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Kabel oben, stehe zwischen den Tuermen.', 'Curle die Griffe zu den Ohren.', 'Kontrolliert strecken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'cable-overhead-ext', name: 'Kabel Ueberkopf Trizeps', nameEn: 'Cable Overhead Tricep Extension',
    category: 'strength', primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Seilgriff am unteren Kabelzug, Ruecken zum Turm.', 'Strecke die Arme ueber den Kopf.', 'Kontrolliert beugen.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'dip-machine', name: 'Dip Maschine', nameEn: 'Assisted Dip Machine',
    category: 'strength', primaryMuscles: ['triceps', 'chest'], secondaryMuscles: ['shoulders'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Gegengewicht einstellen.', 'Greife die Griffe, senke den Koerper.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'lat-pulldown-machine', name: 'Latzug Maschine', nameEn: 'Lat Pulldown Machine',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich, Oberschenkel unter dem Polster.', 'Ziehe die Stange zur Brust.', 'Kontrolliert zurueck.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'cable-woodchop', name: 'Cable Woodchop', nameEn: 'Cable Woodchop',
    category: 'strength', primaryMuscles: ['obliques', 'abs'], secondaryMuscles: ['shoulders'],
    equipment: ['cable'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Kabel oben, stehe seitlich.', 'Ziehe diagonal nach unten und zur Seite.', 'Rotation aus der Hueften.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'ab-wheel-rollout', name: 'Ab-Wheel Rollout', nameEn: 'Ab Wheel Rollout',
    category: 'bodyweight', primaryMuscles: ['abs'], secondaryMuscles: ['shoulders', 'lats'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Knie auf dem Boden, Haende am Ab-Wheel.', 'Rolle vorwaerts, Koerper strecken.', 'Rolle zurueck, Bauch anspannen.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'hip-thrust-barbell', name: 'Barbell Hip Thrust', nameEn: 'Barbell Hip Thrust',
    category: 'strength', primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Oberen Ruecken an Bank, Stange ueber den Hueften.', 'Druecke die Hueften nach oben.', 'Oben maximal anspannen.'],
    defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'glute-bridge', name: 'Glute Bridge', nameEn: 'Glute Bridge',
    category: 'bodyweight', primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Auf dem Ruecken, Knie gebeugt, Fuesse flach.', 'Druecke die Hueften hoch.', 'Oben kurz halten, kontrolliert senken.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'single-leg-rdl', name: 'Einbeiniges Rumaenisches Kreuzheben', nameEn: 'Single-Leg RDL',
    category: 'strength', primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['lower_back'],
    equipment: ['dumbbell'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Stehe auf einem Bein, Kurzhantel in der gegenueber Hand.', 'Beuge dich vor, hinteres Bein geht nach hinten.', 'Ruecken gerade halten.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'sumo-squat-db', name: 'Sumo Squat (Kurzhantel)', nameEn: 'Dumbbell Sumo Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hip_flexors'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Breiter Stand, Zehenspitzen nach aussen.', 'Kurzhantel haengend zwischen den Beinen.', 'Kniebeuge, druecke hoch.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'face-pull', name: 'Face Pull', nameEn: 'Face Pull',
    category: 'strength', primaryMuscles: ['shoulders', 'traps'], secondaryMuscles: ['back'],
    equipment: ['cable'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Seilgriff am oberen Kabelzug.', 'Ziehe zum Gesicht, Ellbogen hoch.', 'Aussen rotieren, Schulterblaetter zusammen.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'incline-hammer-curl', name: 'Schraegbank Hammer Curl', nameEn: 'Incline Hammer Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    equipment: ['dumbbell', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Bank auf 45 Grad, Arme haengen lassen.', 'Curle im Hammergriff.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'ez-bar-curl', name: 'SZ-Stangen Curl', nameEn: 'EZ-Bar Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    equipment: ['ez_bar'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['SZ-Stange im Untergriff.', 'Curle nach oben, Ellbogen fixiert.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'dips-bodyweight', name: 'Dips (Koerpergewicht)', nameEn: 'Bodyweight Dips',
    category: 'bodyweight', primaryMuscles: ['triceps', 'chest'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'outdoor'],
    instructions: ['Stuetze dich auf Holmen ab.', 'Senke den Koerper, Ellbogen nach hinten.', 'Druecke dich hoch.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'chin-up', name: 'Chin-Up', nameEn: 'Chin-Up',
    category: 'bodyweight', primaryMuscles: ['biceps', 'lats'], secondaryMuscles: ['back'],
    equipment: ['pull_up_bar'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Greife die Stange im Untergriff, schulterbreit.', 'Ziehe dich hoch, Kinn ueber die Stange.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 90,
  },
  {
    id: 'hanging-leg-raise', name: 'Haengendes Beinheben', nameEn: 'Hanging Leg Raise',
    category: 'bodyweight', primaryMuscles: ['abs', 'hip_flexors'], secondaryMuscles: [],
    equipment: ['pull_up_bar'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Haenge an der Stange, Arme gestreckt.', 'Hebe die gestreckten Beine bis waagerecht.', 'Kontrolliert senken, kein Schwung.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'farmers-walk', name: 'Farmers Walk', nameEn: 'Farmers Walk',
    category: 'strength', primaryMuscles: ['forearms', 'traps'], secondaryMuscles: ['abs', 'shoulders'],
    equipment: ['dumbbell'], difficulty: 'beginner', locations: ['gym', 'outdoor'],
    instructions: ['Schwere Kurzhanteln oder Farmer Handles greifen.', 'Gehe aufrecht mit grossen Schritten.', 'Schultern unten, Rumpf angespannt.'],
    defaultSets: 3, defaultReps: 40, defaultRestSeconds: 90,
  },
  {
    id: 'turkish-get-up', name: 'Turkish Get-Up', nameEn: 'Turkish Get-Up',
    category: 'strength', primaryMuscles: ['shoulders', 'abs'], secondaryMuscles: ['glutes', 'quads'],
    equipment: ['kettlebell'], difficulty: 'advanced', locations: ['gym', 'home'],
    instructions: ['Liegend, KB in einer Hand ueber der Schulter.', 'Stehe auf, KB bleibt oben.', 'Langsam und kontrolliert in umgekehrter Reihenfolge zurueck.'],
    defaultSets: 3, defaultReps: 3, defaultRestSeconds: 90,
  },
  {
    id: 'wall-sit', name: 'Wall Sit', nameEn: 'Wall Sit',
    category: 'bodyweight', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Ruecken an der Wand, Knie 90 Grad gebeugt.', 'Halte die Position.', 'Oberschenkel parallel zum Boden.'],
    defaultSets: 3, defaultReps: 45, defaultRestSeconds: 60,
  },
  {
    id: 'superman', name: 'Superman', nameEn: 'Superman Hold',
    category: 'bodyweight', primaryMuscles: ['lower_back'], secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home'],
    instructions: ['Baeuchlings, Arme und Beine gestreckt.', 'Hebe Arme, Brust und Beine gleichzeitig.', 'Halte oben kurz, kontrolliert senken.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 45,
  },
  {
    id: 'back-extension', name: 'Rueckenstrecker', nameEn: 'Back Extension',
    category: 'strength', primaryMuscles: ['lower_back'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Lege dich in das Geraet, Hueften am Polster.', 'Senke den Oberkoerper nach unten.', 'Richte dich auf, Ruecken gerade.'],
    defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60,
  },
  {
    id: 'lateral-lunge', name: 'Seitliche Ausfallschritte', nameEn: 'Lateral Lunge',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 'beginner', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Breiter Schritt zur Seite.', 'Beuge das aeussere Knie, anderes Bein gestreckt.', 'Druecke zurueck und wechsle.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
  {
    id: 'bulgarian-split-squat-smith', name: 'Bulgarischer Split Squat Multipresse', nameEn: 'Smith Machine Bulgarian Split Squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['smith_machine', 'bench'], difficulty: 'intermediate', locations: ['gym'],
    instructions: ['Hinterer Fuss auf der Bank, Multipresse auf den Schultern.', 'Senke das hintere Knie Richtung Boden.', 'Druecke hoch.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90,
  },
  {
    id: 'seated-calf-raise', name: 'Sitzendes Wadenheben', nameEn: 'Seated Calf Raise',
    category: 'strength', primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 'beginner', locations: ['gym'],
    instructions: ['Setze dich, Knie unter dem Polster.', 'Hebe die Fersen hoch.', 'Senke tief ab, volle Dehnung.'],
    defaultSets: 4, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'cossack-squat', name: 'Kosaken-Kniebeuge', nameEn: 'Cossack Squat',
    category: 'bodyweight', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hip_flexors', 'hamstrings'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home'],
    instructions: ['Breiter Stand, Gewicht auf ein Bein verlagern.', 'Senke dich tief auf eine Seite, anderes Bein gestreckt.', 'Wechsle die Seiten.'],
    defaultSets: 3, defaultReps: 8, defaultRestSeconds: 60,
  },
  {
    id: 'band-bicep-curl', name: 'Band Bizeps Curl', nameEn: 'Banded Bicep Curl',
    category: 'strength', primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'outdoor'],
    instructions: ['Band unter den Fuessen, Enden greifen.', 'Curle nach oben.', 'Kontrolliert senken.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'band-lateral-walk', name: 'Band Seitliches Gehen', nameEn: 'Banded Lateral Walk',
    category: 'strength', primaryMuscles: ['glutes'], secondaryMuscles: ['quads'],
    equipment: ['resistance_band'], difficulty: 'beginner', locations: ['home', 'gym'],
    instructions: ['Mini-Band um die Knoechel oder Knie.', 'Leichte Kniebeuge, seitlich gehen.', 'Spannung im Band halten.'],
    defaultSets: 3, defaultReps: 15, defaultRestSeconds: 45,
  },
  {
    id: 'plank-to-push-up', name: 'Plank to Push-Up', nameEn: 'Plank to Push-Up',
    category: 'bodyweight', primaryMuscles: ['abs', 'triceps'], secondaryMuscles: ['shoulders', 'chest'],
    equipment: ['bodyweight'], difficulty: 'intermediate', locations: ['gym', 'home', 'outdoor'],
    instructions: ['Starte im Unterarmplank.', 'Druecke dich auf eine Hand, dann die andere hoch.', 'Senke zurueck in den Unterarmplank.'],
    defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60,
  },
]
