export interface Lesson {
  id: string;
  title: string;
  duration: string;
  free: boolean;
}

export interface Course {
  id: string;
  title: string;
  description: string;
  category: string;
  level: "anfaenger" | "fortgeschritten" | "experte";
  duration: string;
  lessons: Lesson[];
  icon: string;
  color: string;
  free: boolean;
  certificate: boolean;
}

export const COURSES: Course[] = [
  // ── Grundlagen ──────────────────────────────────────────────
  {
    id: "budgetierung-101",
    title: "Budgetierung 101",
    description: "Lerne die Grundlagen der Budgetplanung. Von der 50/30/20-Regel bis zum Zero-Based Budgeting.",
    category: "Grundlagen",
    level: "anfaenger",
    duration: "45 Min",
    icon: "from-green-500 to-emerald-600",
    color: "text-green-400",
    free: true,
    certificate: false,
    lessons: [
      { id: "1", title: "Warum Budgetierung wichtig ist", duration: "8 Min", free: true },
      { id: "2", title: "Die 50/30/20 Regel", duration: "12 Min", free: true },
      { id: "3", title: "Die Umschlag-Methode: Bargeld-Budgetierung", duration: "8 Min", free: true },
      { id: "4", title: "Zero-Based Budgeting", duration: "10 Min", free: true },
      { id: "5", title: "Bewusst ausgeben: Grosse Hebel statt kleine Verzichte", duration: "10 Min", free: true },
      { id: "6", title: "Dein erstes Budget erstellen", duration: "15 Min", free: true },
    ],
  },
  {
    id: "finanz-mindset",
    title: "Dein Finanz-Mindset",
    description: "Warum deine Ueberzeugungen ueber Geld dein Konto bestimmen – und wie du sie gezielt veraenderst.",
    category: "Grundlagen",
    level: "anfaenger",
    duration: "50 Min",
    icon: "from-violet-500 to-fuchsia-600",
    color: "text-violet-400",
    free: true,
    certificate: false,
    lessons: [
      { id: "1", title: "Deine Beziehung zu Geld verstehen", duration: "8 Min", free: true },
      { id: "2", title: "Limitierende Glaubenssaetze erkennen", duration: "10 Min", free: true },
      { id: "3", title: "Vom Mangel- zum Fuelle-Denken", duration: "8 Min", free: true },
      { id: "4", title: "Selbstwert und Verdienst", duration: "8 Min", free: true },
      { id: "5", title: "Die unsichtbaren Geld-Skripte deiner Kindheit", duration: "10 Min", free: true },
      { id: "6", title: "Das Finanz-Tagebuch: Klarheit schaffen", duration: "8 Min", free: true },
      { id: "7", title: "Dein Umfeld praeegt dein Konto", duration: "8 Min", free: true },
      { id: "8", title: "Gewohnheiten die Wohlstand foerdern", duration: "8 Min", free: true },
    ],
  },
  {
    id: "schulden-abbauen",
    title: "Schulden strategisch abbauen",
    description: "Verschaffe dir Ueberblick, priorisiere richtig und werde systematisch schuldenfrei.",
    category: "Grundlagen",
    level: "anfaenger",
    duration: "40 Min",
    icon: "from-red-500 to-rose-600",
    color: "text-red-400",
    free: true,
    certificate: false,
    lessons: [
      { id: "1", title: "Schulden-Inventur: Alles auf den Tisch", duration: "8 Min", free: true },
      { id: "2", title: "Gute vs. schlechte Schulden", duration: "8 Min", free: true },
      { id: "3", title: "Die Schneeball-Methode", duration: "8 Min", free: true },
      { id: "4", title: "Die Lawinen-Methode", duration: "8 Min", free: true },
      { id: "5", title: "Dein persoenlicher Tilgungsplan", duration: "8 Min", free: true },
    ],
  },

  // ── Sparen ──────────────────────────────────────────────────
  {
    id: "notgroschen-aufbauen",
    title: "Notgroschen aufbauen",
    description: "Wie du in 6 Monaten einen Notgroschen aufbaust und finanzielle Sicherheit gewinnst.",
    category: "Sparen",
    level: "anfaenger",
    duration: "30 Min",
    icon: "from-blue-500 to-cyan-600",
    color: "text-blue-400",
    free: true,
    certificate: false,
    lessons: [
      { id: "1", title: "Was ist ein Notgroschen?", duration: "5 Min", free: true },
      { id: "2", title: "Wie viel brauchst du?", duration: "8 Min", free: true },
      { id: "3", title: "Sparstrategien die funktionieren", duration: "10 Min", free: true },
      { id: "4", title: "Wo parken? Tagesgeld vs. Girokonto", duration: "7 Min", free: true },
    ],
  },
  {
    id: "automatisch-vermoegen-aufbauen",
    title: "Automatisch Vermoegen aufbauen",
    description: "Richte ein System ein, das dein Vermoegen im Hintergrund wachsen laesst – ohne taeglichen Aufwand.",
    category: "Sparen",
    level: "anfaenger",
    duration: "1 Std",
    icon: "from-emerald-500 to-green-600",
    color: "text-emerald-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Bezahle dich selbst zuerst", duration: "10 Min", free: true },
      { id: "2", title: "Das Mehrkonten-Modell einrichten", duration: "12 Min", free: true },
      { id: "3", title: "Dauerauftraege und Automatisierung", duration: "8 Min", free: false },
      { id: "4", title: "Die Kraft des Zinseszins", duration: "10 Min", free: false },
      { id: "5", title: "Die 10%-Regel: Minimum das immer bleibt", duration: "8 Min", free: false },
      { id: "6", title: "Dein Kapital schuetzen: Nie die Basis antasten", duration: "10 Min", free: false },
      { id: "7", title: "Gehaltserhoenung richtig verteilen", duration: "8 Min", free: false },
      { id: "8", title: "Mini-Gewohnheiten die dein Konto fuellen", duration: "8 Min", free: false },
      { id: "9", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },

  // ── Investieren ─────────────────────────────────────────────
  {
    id: "etf-investieren",
    title: "ETF-Investieren fuer Einsteiger",
    description: "Alles ueber ETFs: Was sie sind, wie du den richtigen waehlst und wie du einen Sparplan einrichtest.",
    category: "Investieren",
    level: "anfaenger",
    duration: "1,5 Std",
    icon: "from-purple-500 to-indigo-600",
    color: "text-purple-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Was sind ETFs?", duration: "10 Min", free: true },
      { id: "2", title: "Aktien vs. Anleihen vs. ETFs", duration: "12 Min", free: true },
      { id: "3", title: "Den richtigen ETF waehlen", duration: "15 Min", free: false },
      { id: "4", title: "Depot eroeffnen Schritt fuer Schritt", duration: "12 Min", free: false },
      { id: "5", title: "Sparplan einrichten", duration: "10 Min", free: false },
      { id: "6", title: "Rebalancing & Langzeit-Strategie", duration: "15 Min", free: false },
      { id: "7", title: "Kosten und TER: Der stille Rendite-Killer", duration: "10 Min", free: false },
      { id: "8", title: "Faktor-Investing: Small Cap, Value & Co.", duration: "12 Min", free: false },
      { id: "9", title: "Steuern auf ETF-Ertraege", duration: "12 Min", free: false },
      { id: "10", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "passives-einkommen",
    title: "Passives Einkommen aufbauen",
    description: "Lerne die verschiedenen Wege zu Einkommensquellen, die auch ohne taegliche Arbeit fliessen.",
    category: "Investieren",
    level: "fortgeschritten",
    duration: "2 Std",
    icon: "from-yellow-500 to-amber-600",
    color: "text-yellow-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Was ist passives Einkommen wirklich?", duration: "10 Min", free: true },
      { id: "2", title: "Aktives vs. passives Einkommen", duration: "10 Min", free: true },
      { id: "3", title: "Dividenden-Strategie aufbauen", duration: "15 Min", free: false },
      { id: "4", title: "Mieteinnahmen als Einkommensquelle", duration: "12 Min", free: false },
      { id: "5", title: "Digitale Produkte & Online-Einnahmen", duration: "15 Min", free: false },
      { id: "6", title: "Lizenzeinnahmen & Beteiligungen", duration: "12 Min", free: false },
      { id: "7", title: "Das 80/20-Prinzip: Fokus auf die groessten Hebel", duration: "10 Min", free: false },
      { id: "8", title: "Mini-Ruhestaende: Warum du nicht bis 67 warten musst", duration: "10 Min", free: false },
      { id: "9", title: "Mehrere Einkommensquellen kombinieren", duration: "15 Min", free: false },
      { id: "10", title: "Dein persoenlicher Einkommens-Mix", duration: "12 Min", free: false },
      { id: "11", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "immobilien-investment",
    title: "Immobilien als Kapitalanlage",
    description: "Von der Renditeberechnung bis zur Finanzierung: Immobilien-Investment Schritt fuer Schritt.",
    category: "Investieren",
    level: "experte",
    duration: "3 Std",
    icon: "from-teal-500 to-cyan-600",
    color: "text-teal-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Immobilien als Anlageklasse", duration: "12 Min", free: true },
      { id: "2", title: "Bruttorendite vs. Nettorendite", duration: "15 Min", free: false },
      { id: "3", title: "Kaufnebenkosten berechnen", duration: "12 Min", free: false },
      { id: "4", title: "Finanzierung & Eigenkapital", duration: "18 Min", free: false },
      { id: "5", title: "Mieteinnahmen & Cashflow", duration: "15 Min", free: false },
      { id: "6", title: "Steuervorteile: AfA & Werbungskosten", duration: "18 Min", free: false },
      { id: "7", title: "Standortanalyse & Due Diligence", duration: "20 Min", free: false },
      { id: "8", title: "Verwaltung mit Fintutto Tools", duration: "12 Min", free: false },
      { id: "9", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },

  {
    id: "fortgeschrittenes-investing",
    title: "Fortgeschrittenes Investieren",
    description: "Portfoliotheorie, Sicherheitsmarge, Markt-Effizienz und systematische Anlagestrategien.",
    category: "Investieren",
    level: "fortgeschritten",
    duration: "2 Std",
    icon: "from-violet-500 to-purple-600",
    color: "text-violet-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Moderne Portfoliotheorie einfach erklaert", duration: "12 Min", free: true },
      { id: "2", title: "Risiko vs. Rendite: Die Effizienzgrenze", duration: "12 Min", free: true },
      { id: "3", title: "Markteffizienz: Kann man den Markt schlagen?", duration: "12 Min", free: false },
      { id: "4", title: "Sicherheitsmarge: Kaufen mit Puffer", duration: "10 Min", free: false },
      { id: "5", title: "Value vs. Growth: Zwei Philosophien", duration: "12 Min", free: false },
      { id: "6", title: "Korrelation und Diversifikation in der Praxis", duration: "12 Min", free: false },
      { id: "7", title: "Wann und wie Rebalancing sinnvoll ist", duration: "10 Min", free: false },
      { id: "8", title: "Asset Allocation nach Lebensphasen", duration: "12 Min", free: false },
      { id: "9", title: "Dein persoenliches Anlageregelbuch erstellen", duration: "10 Min", free: false },
      { id: "10", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },

  // ── Steuern ─────────────────────────────────────────────────
  {
    id: "steuern-fuer-arbeitnehmer",
    title: "Steuern sparen als Arbeitnehmer",
    description: "Steuererklaerung verstehen, Absetzmoeglichkeiten nutzen und mehr Netto vom Brutto behalten.",
    category: "Steuern",
    level: "fortgeschritten",
    duration: "2 Std",
    icon: "from-amber-500 to-orange-600",
    color: "text-amber-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Grundlagen der Einkommensteuer", duration: "12 Min", free: true },
      { id: "2", title: "Werbungskosten richtig absetzen", duration: "15 Min", free: false },
      { id: "3", title: "Homeoffice-Pauschale & Pendlerpauschale", duration: "12 Min", free: false },
      { id: "4", title: "Sonderausgaben & Vorsorge", duration: "15 Min", free: false },
      { id: "5", title: "Handwerkerkosten & haushaltsnahe DL", duration: "10 Min", free: false },
      { id: "6", title: "ELSTER Steuererklaerung Walkthrough", duration: "20 Min", free: false },
      { id: "7", title: "Haeufige Fehler vermeiden", duration: "12 Min", free: false },
      { id: "8", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "steuern-fuer-freelancer",
    title: "Steuern fuer Freelancer & Selbststaendige",
    description: "EUeR, Umsatzsteuer, Abschreibungen und Vorauszahlungen – alles was Selbststaendige wissen muessen.",
    category: "Steuern",
    level: "fortgeschritten",
    duration: "1,5 Std",
    icon: "from-orange-500 to-amber-600",
    color: "text-orange-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Gewerbe vs. Freiberuf: Was gilt fuer dich?", duration: "10 Min", free: true },
      { id: "2", title: "Einnahmen-Ueberschuss-Rechnung (EUeR) verstehen", duration: "12 Min", free: true },
      { id: "3", title: "Umsatzsteuer und Kleinunternehmerregelung", duration: "12 Min", free: false },
      { id: "4", title: "Betriebsausgaben richtig absetzen", duration: "12 Min", free: false },
      { id: "5", title: "Abschreibungen: GWG, lineare und degressive AfA", duration: "10 Min", free: false },
      { id: "6", title: "Steuervorauszahlungen planen", duration: "8 Min", free: false },
      { id: "7", title: "Betriebliche Altersvorsorge fuer Selbststaendige", duration: "10 Min", free: false },
      { id: "8", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "kredite-schuldenmanagement",
    title: "Kredite und Schuldenmanagement",
    description: "Richtig mit Krediten umgehen, Zinsen vergleichen und Schulden systematisch abbauen.",
    category: "Steuern",
    level: "anfaenger",
    duration: "1 Std",
    icon: "from-red-500 to-orange-600",
    color: "text-red-400",
    free: true,
    certificate: false,
    lessons: [
      { id: "1", title: "Kreditarten im Ueberblick", duration: "10 Min", free: true },
      { id: "2", title: "Zinsen verstehen: Nominal vs. Effektivzins", duration: "10 Min", free: true },
      { id: "3", title: "Kreditwuerdigkeit und SCHUFA", duration: "10 Min", free: true },
      { id: "4", title: "Wann lohnt sich ein Kredit?", duration: "8 Min", free: true },
      { id: "5", title: "Umschuldung: Alte Kredite optimieren", duration: "10 Min", free: true },
      { id: "6", title: "Schuldenfallen erkennen und meiden", duration: "8 Min", free: true },
    ],
  },

  // ── Vorsorge ────────────────────────────────────────────────
  {
    id: "versicherungen-optimieren",
    title: "Versicherungen optimieren",
    description: "Welche Versicherungen brauchst du wirklich und wo zahlst du zu viel?",
    category: "Vorsorge",
    level: "anfaenger",
    duration: "1 Std",
    icon: "from-slate-500 to-gray-600",
    color: "text-slate-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Pflichtversicherungen vs. freiwillige Versicherungen", duration: "10 Min", free: true },
      { id: "2", title: "Haftpflicht: Die wichtigste Versicherung", duration: "8 Min", free: true },
      { id: "3", title: "Berufsunfaehigkeitsversicherung: Dein Einkommen schuetzen", duration: "12 Min", free: false },
      { id: "4", title: "Krankenversicherung: GKV vs. PKV", duration: "12 Min", free: false },
      { id: "5", title: "Hausrat und Rechtsschutz: Braucht man das?", duration: "8 Min", free: false },
      { id: "6", title: "Versicherungen die du NICHT brauchst", duration: "8 Min", free: false },
      { id: "7", title: "Versicherungs-Check: Dein persoenlicher Bestandsplan", duration: "10 Min", free: false },
      { id: "8", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "altersvorsorge-planen",
    title: "Altersvorsorge richtig planen",
    description: "Rente, Riester, Ruerup, bAV und private Vorsorge: Welche Bausteine brauchst du wirklich?",
    category: "Vorsorge",
    level: "fortgeschritten",
    duration: "2,5 Std",
    icon: "from-rose-500 to-pink-600",
    color: "text-rose-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Die Rentenluecke berechnen", duration: "15 Min", free: true },
      { id: "2", title: "Gesetzliche Rente verstehen", duration: "12 Min", free: true },
      { id: "3", title: "Riester-Rente: Lohnt sich das?", duration: "15 Min", free: false },
      { id: "4", title: "Ruerup / Basisrente", duration: "12 Min", free: false },
      { id: "5", title: "Betriebliche Altersvorsorge (bAV)", duration: "15 Min", free: false },
      { id: "6", title: "Private Rentenversicherung vs. ETF", duration: "18 Min", free: false },
      { id: "7", title: "Dein persoenlicher Vorsorge-Mix", duration: "15 Min", free: false },
      { id: "8", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },

  // ── Geld-Psychologie ─────────────────────────────────────────
  {
    id: "psychologie-des-geldes",
    title: "Die Psychologie des Geldes",
    description: "Warum wir irrational mit Geld umgehen und wie du bessere Finanzentscheidungen triffst.",
    category: "Geld-Psychologie",
    level: "anfaenger",
    duration: "1,5 Std",
    icon: "from-pink-500 to-rose-600",
    color: "text-pink-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Geld ist nie nur Mathematik", duration: "10 Min", free: true },
      { id: "2", title: "Warum Erfahrung wichtiger ist als Wissen", duration: "10 Min", free: true },
      { id: "3", title: "Die Illusion der Kontrolle an den Maerkten", duration: "12 Min", free: false },
      { id: "4", title: "Tail-Events: Warum seltene Ereignisse alles aendern", duration: "12 Min", free: false },
      { id: "5", title: "Genug: Wann Vermoegen zum Risiko wird", duration: "10 Min", free: false },
      { id: "6", title: "Geduld als Rendite-Booster", duration: "10 Min", free: false },
      { id: "7", title: "Freiheit als ultimative Rendite", duration: "10 Min", free: false },
      { id: "8", title: "Dein persoenlicher Entscheidungsrahmen", duration: "10 Min", free: false },
      { id: "9", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "denkfallen-geldentscheidungen",
    title: "Denkfallen bei Geldentscheidungen",
    description: "Verlustaversion, Ankereffekte und andere kognitive Verzerrungen – und wie du sie umgehst.",
    category: "Geld-Psychologie",
    level: "fortgeschritten",
    duration: "1,5 Std",
    icon: "from-fuchsia-500 to-purple-600",
    color: "text-fuchsia-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Schnelles und langsames Denken bei Finanzen", duration: "12 Min", free: true },
      { id: "2", title: "Verlustaversion: Warum Verluste doppelt schmerzen", duration: "10 Min", free: true },
      { id: "3", title: "Der Ankereffekt bei Preisen und Kursen", duration: "10 Min", free: false },
      { id: "4", title: "Herdenverhalten und FOMO an der Boerse", duration: "10 Min", free: false },
      { id: "5", title: "Bestaetigungsfehler: Nur sehen was man glaubt", duration: "10 Min", free: false },
      { id: "6", title: "Mentale Buchfuehrung: Geld ist nicht gleich Geld", duration: "10 Min", free: false },
      { id: "7", title: "Sunk-Cost-Falle: Loslassen lernen", duration: "10 Min", free: false },
      { id: "8", title: "Nudging: Dich selbst zu besseren Entscheidungen fuehren", duration: "10 Min", free: false },
      { id: "9", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },

  // ── Boerse verstehen ────────────────────────────────────────
  {
    id: "boersenpsychologie",
    title: "Boersenpsychologie verstehen",
    description: "Wie Emotionen die Maerkte bewegen – und warum die Masse meist falsch liegt.",
    category: "Boerse verstehen",
    level: "fortgeschritten",
    duration: "1,5 Std",
    icon: "from-indigo-500 to-violet-600",
    color: "text-indigo-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Warum Boersen ueberreagieren", duration: "10 Min", free: true },
      { id: "2", title: "Gier und Angst: Die zwei Grundemotionen", duration: "10 Min", free: true },
      { id: "3", title: "Der Marktzyklus und seine Phasen", duration: "12 Min", free: false },
      { id: "4", title: "Kontraer denken: Kaufen wenn andere verkaufen", duration: "12 Min", free: false },
      { id: "5", title: "Warum die meisten Anleger dem Markt hinterherlaufen", duration: "10 Min", free: false },
      { id: "6", title: "Geduld an der Boerse: Die unterschaetzte Superkraft", duration: "10 Min", free: false },
      { id: "7", title: "Medienpanikmache vs. Realitaet", duration: "10 Min", free: false },
      { id: "8", title: "Deine persoenliche Anleger-Checkliste", duration: "10 Min", free: false },
      { id: "9", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "krisensicheres-portfolio",
    title: "Dein krisensicheres Portfolio",
    description: "Wie du ein Portfolio baust, das in jeder Marktlage stabil bleibt.",
    category: "Boerse verstehen",
    level: "experte",
    duration: "2 Std",
    icon: "from-cyan-500 to-blue-600",
    color: "text-cyan-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Was ist ein robustes Portfolio?", duration: "10 Min", free: true },
      { id: "2", title: "Die vier Jahreszeiten der Wirtschaft", duration: "12 Min", free: true },
      { id: "3", title: "Anlageklassen fuer jede Marktphase", duration: "15 Min", free: false },
      { id: "4", title: "Das Allwetter-Prinzip: Diversifikation auf Steroiden", duration: "15 Min", free: false },
      { id: "5", title: "Schwarze Schwaene: Auf das Unmoeglische vorbereitet sein", duration: "12 Min", free: false },
      { id: "6", title: "Die Barbell-Strategie: Sicher und spekulativ", duration: "12 Min", free: false },
      { id: "7", title: "Kosten minimieren, Rendite maximieren", duration: "10 Min", free: false },
      { id: "8", title: "Dein persoenliches Allwetter-Portfolio erstellen", duration: "15 Min", free: false },
      { id: "9", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },

  // ── Einkommen ───────────────────────────────────────────────
  {
    id: "investor-denken",
    title: "Denke wie ein Investor",
    description: "Lerne den Unterschied zwischen Werten und Verbindlichkeiten und denke in Cashflows statt Gehaeltern.",
    category: "Einkommen",
    level: "anfaenger",
    duration: "1 Std",
    icon: "from-amber-500 to-yellow-600",
    color: "text-amber-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Was ist ein Vermoegenswert wirklich?", duration: "10 Min", free: true },
      { id: "2", title: "Vermoegenswerte vs. Verbindlichkeiten erkennen", duration: "10 Min", free: true },
      { id: "3", title: "Die vier Einkommens-Typen", duration: "12 Min", free: false },
      { id: "4", title: "Cashflow-Denken statt Gehaltsdenken", duration: "10 Min", free: false },
      { id: "5", title: "Finanzielle Bildung als Investition", duration: "8 Min", free: false },
      { id: "6", title: "Wann lohnt sich Fremdkapital?", duration: "10 Min", free: false },
      { id: "7", title: "Dein erster Cashflow-Plan", duration: "10 Min", free: false },
      { id: "8", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "zeitlose-geldprinzipien",
    title: "Zeitlose Geld-Prinzipien",
    description: "Bewaehrte Weisheiten ueber Geld, die seit Jahrhunderten funktionieren – in moderner Anwendung.",
    category: "Einkommen",
    level: "anfaenger",
    duration: "1 Std",
    icon: "from-stone-500 to-zinc-600",
    color: "text-stone-400",
    free: true,
    certificate: false,
    lessons: [
      { id: "1", title: "Lege mindestens 10% jedes Einkommens zurueck", duration: "10 Min", free: true },
      { id: "2", title: "Lass dein Geld fuer dich arbeiten", duration: "10 Min", free: true },
      { id: "3", title: "Schuetze dein Vermoegen vor Verlusten", duration: "8 Min", free: true },
      { id: "4", title: "Investiere nur in das, was du verstehst", duration: "8 Min", free: true },
      { id: "5", title: "Mache dein Eigenheim zum Verbuendeten", duration: "8 Min", free: true },
      { id: "6", title: "Sichere kuenftige Einkuenfte ab", duration: "8 Min", free: true },
      { id: "7", title: "Steigere kontinuierlich deine Faehigkeiten", duration: "8 Min", free: true },
    ],
  },

  // ── Finanzielle Freiheit ────────────────────────────────────
  {
    id: "finanzielle-freiheit",
    title: "Der Weg zur finanziellen Freiheit",
    description: "Von der Absicherung bis zur Unabhaengigkeit: Die vier Stufen, die dich finanziell frei machen.",
    category: "Finanzielle Freiheit",
    level: "anfaenger",
    duration: "1,5 Std",
    icon: "from-sky-500 to-blue-600",
    color: "text-sky-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Was finanzielle Freiheit wirklich bedeutet", duration: "10 Min", free: true },
      { id: "2", title: "Stufe 1: Finanzielle Absicherung", duration: "12 Min", free: true },
      { id: "3", title: "Stufe 2: Finanzielle Sicherheit", duration: "12 Min", free: false },
      { id: "4", title: "Stufe 3: Finanzielle Unabhaengigkeit", duration: "12 Min", free: false },
      { id: "5", title: "Stufe 4: Finanzieller Ueberfluss", duration: "10 Min", free: false },
      { id: "6", title: "Die 4%-Regel: Wie viel Kapital reicht?", duration: "12 Min", free: false },
      { id: "7", title: "Deine persoenliche Freiheitszahl berechnen", duration: "15 Min", free: false },
      { id: "8", title: "Lebenskosten senken ohne Lebensqualitaet zu verlieren", duration: "10 Min", free: false },
      { id: "9", title: "Der 7-Jahres-Plan: Meilensteine setzen", duration: "12 Min", free: false },
      { id: "10", title: "Vorbilder und Mentoren finden", duration: "8 Min", free: false },
      { id: "11", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "einkommen-steigern",
    title: "Einkommen gezielt steigern",
    description: "Strategien um mehr zu verdienen: Gehaltsverhandlung, Nebeneinkuenfte und Wert-Positionierung.",
    category: "Finanzielle Freiheit",
    level: "fortgeschritten",
    duration: "1,5 Std",
    icon: "from-lime-500 to-green-600",
    color: "text-lime-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Warum Sparen allein nicht reicht", duration: "8 Min", free: true },
      { id: "2", title: "Deinen Marktwert kennen und steigern", duration: "12 Min", free: true },
      { id: "3", title: "Gehaltsverhandlung vorbereiten", duration: "15 Min", free: false },
      { id: "4", title: "Nebeneinkuenfte finden und aufbauen", duration: "12 Min", free: false },
      { id: "5", title: "Faehigkeiten monetarisieren", duration: "12 Min", free: false },
      { id: "6", title: "Hebelwirkung: Zeit entkoppeln von Einkommen", duration: "10 Min", free: false },
      { id: "7", title: "Spezialwissen als Wettbewerbsvorteil", duration: "10 Min", free: false },
      { id: "8", title: "Vom Angestellten zum Unternehmer denken", duration: "10 Min", free: false },
      { id: "9", title: "Die 72-Stunden-Regel: Ins Handeln kommen", duration: "8 Min", free: false },
      { id: "10", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
  {
    id: "vermoegen-schuetzen",
    title: "Vermoegen schuetzen und erhalten",
    description: "Wie du dein aufgebautes Vermoegen vor Inflation, Fehlentscheidungen und Risiken bewahrst.",
    category: "Finanzielle Freiheit",
    level: "experte",
    duration: "1,5 Std",
    icon: "from-orange-500 to-red-600",
    color: "text-orange-400",
    free: false,
    certificate: true,
    lessons: [
      { id: "1", title: "Warum Vermoegensschutz so wichtig ist", duration: "8 Min", free: true },
      { id: "2", title: "Inflation verstehen und gegensteuern", duration: "12 Min", free: true },
      { id: "3", title: "Diversifikation: Nicht alles auf eine Karte", duration: "12 Min", free: false },
      { id: "4", title: "Antifragil denken: Von Krisen profitieren", duration: "12 Min", free: false },
      { id: "5", title: "Versicherungen die du wirklich brauchst", duration: "12 Min", free: false },
      { id: "6", title: "Emotionale Fallen bei Geldentscheidungen", duration: "10 Min", free: false },
      { id: "7", title: "Liquiditaetsreserven: Handlungsfaehig bleiben", duration: "10 Min", free: false },
      { id: "8", title: "Vermoegen weitergeben: Erben und Schenken", duration: "15 Min", free: false },
      { id: "9", title: "Dein persoenlicher Schutzplan", duration: "10 Min", free: false },
      { id: "10", title: "Quiz & Zertifikat", duration: "10 Min", free: false },
    ],
  },
];

export const CATEGORIES = [...new Set(COURSES.map((c) => c.category))];

export const LEVEL_LABELS: Record<string, string> = {
  anfaenger: "Anfaenger",
  fortgeschritten: "Fortgeschritten",
  experte: "Experte",
};

// ── Lernpfade ─────────────────────────────────────────────────

export interface LearningPath {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  courseIds: string[];
  estimatedWeeks: number;
}

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: "finanz-anfaenger",
    title: "Finanz-Anfaenger",
    description: "Der perfekte Einstieg: Von null auf solide finanzielle Grundlagen in wenigen Wochen.",
    icon: "from-green-500 to-emerald-600",
    color: "text-green-400",
    estimatedWeeks: 4,
    courseIds: [
      "finanz-mindset",
      "budgetierung-101",
      "schulden-abbauen",
      "notgroschen-aufbauen",
      "zeitlose-geldprinzipien",
    ],
  },
  {
    id: "vermoegen-aufbauen",
    title: "Vermoegen systematisch aufbauen",
    description: "Vom Sparen zum Investieren: Lerne wie du automatisiert und langfristig Vermoegen bildest.",
    icon: "from-blue-500 to-indigo-600",
    color: "text-blue-400",
    estimatedWeeks: 8,
    courseIds: [
      "automatisch-vermoegen-aufbauen",
      "etf-investieren",
      "passives-einkommen",
      "finanzielle-freiheit",
    ],
  },
  {
    id: "kluger-investor",
    title: "Der kluge Investor",
    description: "Verstehe Maerkte, Psychologie und Strategie – und investiere mit System statt Bauchgefuehl.",
    icon: "from-purple-500 to-violet-600",
    color: "text-purple-400",
    estimatedWeeks: 10,
    courseIds: [
      "psychologie-des-geldes",
      "denkfallen-geldentscheidungen",
      "investor-denken",
      "etf-investieren",
      "boersenpsychologie",
      "krisensicheres-portfolio",
    ],
  },
  {
    id: "mehr-verdienen",
    title: "Mehr verdienen und wachsen",
    description: "Steigere aktiv dein Einkommen und baue mehrere Einkommensquellen auf.",
    icon: "from-amber-500 to-orange-600",
    color: "text-amber-400",
    estimatedWeeks: 6,
    courseIds: [
      "einkommen-steigern",
      "investor-denken",
      "passives-einkommen",
      "steuern-fuer-arbeitnehmer",
    ],
  },
  {
    id: "steuern-und-recht",
    title: "Steuern & Finanzen optimieren",
    description: "Spare legal Steuern und verstehe Kredite, Versicherungen und Vorsorge.",
    icon: "from-orange-500 to-red-600",
    color: "text-orange-400",
    estimatedWeeks: 6,
    courseIds: [
      "steuern-fuer-arbeitnehmer",
      "kredite-schuldenmanagement",
      "versicherungen-optimieren",
      "altersvorsorge-planen",
    ],
  },
  {
    id: "komplette-absicherung",
    title: "Rundum abgesichert",
    description: "Vorsorge, Versicherungen und Vermoegensschutz – damit du ruhig schlafen kannst.",
    icon: "from-rose-500 to-pink-600",
    color: "text-rose-400",
    estimatedWeeks: 5,
    courseIds: [
      "notgroschen-aufbauen",
      "versicherungen-optimieren",
      "altersvorsorge-planen",
      "vermoegen-schuetzen",
    ],
  },
  {
    id: "finanzielle-unabhaengigkeit",
    title: "Weg zur finanziellen Unabhaengigkeit",
    description: "Der komplette Pfad: Von den Grundlagen bis zur finanziellen Freiheit.",
    icon: "from-sky-500 to-cyan-600",
    color: "text-sky-400",
    estimatedWeeks: 20,
    courseIds: [
      "finanz-mindset",
      "budgetierung-101",
      "schulden-abbauen",
      "automatisch-vermoegen-aufbauen",
      "psychologie-des-geldes",
      "etf-investieren",
      "einkommen-steigern",
      "passives-einkommen",
      "finanzielle-freiheit",
      "vermoegen-schuetzen",
      "altersvorsorge-planen",
    ],
  },
];
