import { Link, useLocation } from 'react-router-dom'
import {
  LayoutDashboard,
  FileText,
  Upload,
  Clock,
  ShieldAlert,
  Search,
  Users,
  Settings,
  HelpCircle,
  BarChart3,
  ArrowLeftRight,
  CalendarDays,
  Calculator,
  User,
  Building2,
  ClipboardCheck,
  FileStack,
  FolderUp,
  FileDown,
  Archive,
  Zap,
  PieChart,
  FolderOpen,
  Bell,
  Activity,
  Lightbulb,
  LifeBuoy,
  FolderDown,
  Home,
  Receipt,
  ScanLine,
  LayoutGrid,
  Landmark,
  GitBranch,
  Wallet,
  Scale,
  Briefcase,
  Bot,
  BookOpen,
  UserCheck,
  TrendingUp,
  ReceiptText,
  Percent,
  Newspaper,
  CalendarClock,
  BadgeDollarSign,
  ShieldCheck,
  FileSignature,
  Navigation,
  KeyRound,
  Send,
  PiggyBank,
  HeartHandshake,
  CalendarCheck,
  BookOpenCheck,
  ReceiptEuro,
  Factory,
  History,
  Wrench,
  FileSpreadsheet,
  Building,
  HeartPulse,
  Umbrella,
  ArrowDownUp,
  Bitcoin,
  Coins,
  Baby,
  GitCompareArrows,
  SunMedium,
  Car,
  UsersRound,
  ArrowUpFromLine,
  Monitor,
  GraduationCap,
  HandCoins,
  Truck,
  Plane,
  FileSearch,
  ShieldPlus,
  BookMarked,
  Banknote,
  Gift,
  HeartCrack,
  TrendingDown,
  Building2 as Building2Icon,
  Accessibility,
  RefreshCcw,
  BadgeInfo,
  Church,
  Utensils,
  LineChart,
  FileBarChart,
  Target,
  MapPin,
  Gavel,
  Table2,
} from 'lucide-react'
import { cn } from '../../lib/utils'

const navigation = [
  { name: 'Dashboard', href: '/', icon: LayoutDashboard },
  { name: 'Bescheide', href: '/bescheide', icon: FileText },
  { name: 'Upload & Analyse', href: '/upload', icon: Upload },
  { name: 'Analyse', href: '/analyse', icon: Search },
  { name: 'Fristen', href: '/fristen', icon: Clock },
  { name: 'Kalender', href: '/kalender', icon: CalendarDays },
  { name: 'Einspruch', href: '/einspruch', icon: ShieldAlert },
  { name: 'Vergleich', href: '/vergleich', icon: ArrowLeftRight },
  { name: 'Einspruch-Vorlagen', href: '/einspruch/vorlagen', icon: FileStack },
  { name: 'Steuer-Rechner', href: '/steuerrechner', icon: Calculator },
  { name: 'Checkliste', href: '/checkliste', icon: ClipboardCheck },
  { name: 'Finanzaemter', href: '/finanzaemter', icon: Building2 },
  { name: 'Mehrfach-Upload', href: '/mehrfach-upload', icon: FolderUp },
  { name: 'Schnellerfassung', href: '/schnellerfassung', icon: Zap },
  { name: 'Archiv', href: '/archiv', icon: Archive },
  { name: 'Statistiken', href: '/statistiken', icon: PieChart },
  { name: 'Dokumente', href: '/dokumente', icon: FolderOpen },
  { name: 'Benachrichtigungen', href: '/benachrichtigungen', icon: Bell },
  { name: 'Aktivitaeten', href: '/aktivitaeten', icon: Activity },
  { name: 'Steuer-Tipps', href: '/steuer-tipps', icon: Lightbulb },
  { name: 'Immobilien', href: '/immobilien', icon: Home },
  { name: 'Nebenkosten', href: '/nebenkosten', icon: Receipt },
  { name: 'Mieterbereich', href: '/mieterbereich', icon: Users },
  { name: 'Dokument-Scanner', href: '/dokument-scanner', icon: ScanLine },
  { name: 'Steuerkalender', href: '/steuerkalender', icon: CalendarDays },
  { name: 'Verwalter', href: '/verwalter', icon: LayoutGrid },
  { name: 'Grundsteuer-Simulator', href: '/grundsteuer-simulator', icon: Landmark },
  { name: 'Widerspruch-Tracker', href: '/widerspruch-tracker', icon: GitBranch },
  { name: 'Zahlungen', href: '/zahlungen', icon: Wallet },
  { name: 'Benchmark', href: '/benchmark', icon: Scale },
  { name: 'Steuerberater', href: '/steuerberater', icon: Briefcase },
  { name: 'Automatisierung', href: '/automatisierung', icon: Bot },
  { name: 'Wissens-Datenbank', href: '/wissensdatenbank', icon: BookOpen },
  { name: 'Mandanten', href: '/mandanten', icon: UserCheck },
  { name: 'Steuerlast-Prognose', href: '/steuerlast-prognose', icon: TrendingUp },
  { name: 'Beleg-Manager', href: '/belege', icon: ReceiptText },
  { name: 'AfA-Rechner', href: '/afa-rechner', icon: Percent },
  { name: 'Steuer-News', href: '/steuer-news', icon: Newspaper },
  { name: 'Vorauszahlungen', href: '/vorauszahlungen', icon: CalendarClock },
  { name: 'Steuerspar-Rechner', href: '/steuerspar-rechner', icon: BadgeDollarSign },
  { name: 'Betriebsprüfung', href: '/betriebspruefung', icon: ShieldCheck },
  { name: 'Dokument-Vorlagen', href: '/dokument-vorlagen', icon: FileSignature },
  { name: 'Pendler-Rechner', href: '/pendler-rechner', icon: Navigation },
  { name: 'Steuer-Ident', href: '/steuer-ident', icon: KeyRound },
  { name: 'ELSTER-Status', href: '/elster-status', icon: Send },
  { name: 'Finanzplanung', href: '/finanzplanung', icon: PiggyBank },
  { name: 'Erbschaftsteuer', href: '/erbschaftsteuer', icon: HeartHandshake },
  { name: 'Steuer-Termine', href: '/steuer-termine', icon: CalendarCheck },
  { name: 'Kassenbuch', href: '/kassenbuch', icon: BookOpenCheck },
  { name: 'Umsatzsteuer', href: '/umsatzsteuer', icon: ReceiptEuro },
  { name: 'Gewerbesteuer', href: '/gewerbesteuer', icon: Factory },
  { name: 'Steuer-Historie', href: '/steuer-historie', icon: History },
  { name: 'Haushaltsnahe', href: '/haushaltsnahe', icon: Wrench },
  { name: 'Steuer-Formulare', href: '/steuer-formulare', icon: FileSpreadsheet },
  { name: 'Doppelte Haushalt.', href: '/doppelte-haushaltsfuehrung', icon: Building },
  { name: 'Spenden-Rechner', href: '/spenden-rechner', icon: HeartPulse },
  { name: 'Riester-Rechner', href: '/riester-rechner', icon: Umbrella },
  { name: 'Verlustverrechnung', href: '/verlustverrechnung', icon: ArrowDownUp },
  { name: 'Krypto-Steuer', href: '/krypto-steuer', icon: Bitcoin },
  { name: 'Minijob-Rechner', href: '/minijob-rechner', icon: Coins },
  { name: 'Elterngeld', href: '/elterngeld-rechner', icon: Baby },
  { name: 'Bescheid-Vergleicher', href: '/bescheid-vergleicher', icon: GitCompareArrows },
  { name: 'Photovoltaik-Steuer', href: '/photovoltaik', icon: SunMedium },
  { name: 'Firmenwagen-Rechner', href: '/firmenwagen-rechner', icon: Car },
  { name: 'Steuerklassenwahl', href: '/steuerklassenwahl', icon: UsersRound },
  { name: 'Progressionsvorbeh.', href: '/progressionsvorbehalt', icon: ArrowUpFromLine },
  { name: 'Arbeitszimmer', href: '/arbeitszimmer', icon: Monitor },
  { name: 'Kinderfreibetrag', href: '/kinderfreibetrag', icon: GraduationCap },
  { name: 'Solidaritätszuschlag', href: '/solidaritaetszuschlag', icon: HandCoins },
  { name: 'Umzugskosten', href: '/umzugskosten', icon: Truck },
  { name: 'Reisekosten', href: '/reisekosten', icon: Plane },
  { name: 'Bewerbungskosten', href: '/bewerbungskosten', icon: FileSearch },
  { name: 'Vorsorgeaufwend.', href: '/vorsorgeaufwendungen', icon: ShieldPlus },
  { name: 'Fortbildungskosten', href: '/fortbildungskosten', icon: BookMarked },
  { name: 'Abfindungsrechner', href: '/abfindungsrechner', icon: Banknote },
  { name: 'Sachbezüge', href: '/sachbezuege', icon: Gift },
  { name: 'Außergew. Belast.', href: '/aussergewoehnliche-belastungen', icon: HeartCrack },
  { name: 'Kapitalerträge', href: '/kapitalertraege', icon: TrendingDown },
  { name: 'Vermietung', href: '/vermietung', icon: Building2Icon },
  { name: 'Behinderten-PB', href: '/behindertenpauschbetrag', icon: Accessibility },
  { name: 'LSt-Jahresausgleich', href: '/lohnsteuer-jahresausgleich', icon: RefreshCcw },
  { name: 'Steuerklassen-Info', href: '/steuerklassen-info', icon: BadgeInfo },
  { name: 'Grunderwerbsteuer', href: '/grunderwerbsteuer', icon: Landmark },
  { name: 'Entfernungspauschale', href: '/entfernungspauschale', icon: Car },
  { name: 'Kirchensteuer', href: '/kirchensteuer', icon: Church },
  { name: 'Steuererstattung', href: '/steuererstattung', icon: Receipt },
  { name: 'EÜR', href: '/einnahmen-ueberschuss', icon: FileBarChart },
  { name: 'Schenkungsteuer', href: '/schenkungsteuer', icon: Gift },
  { name: 'Verpflegungsmehaufw.', href: '/verpflegungsmehraufwand', icon: Utensils },
  { name: 'Investmentsteuer', href: '/investmentsteuer', icon: LineChart },
  { name: 'Pflegegeld', href: '/pflegegeld', icon: HeartPulse },
  { name: 'Steuerzinsen', href: '/steuerzinsen', icon: Percent },
  { name: 'Steueroptimierung', href: '/steueroptimierung', icon: Target },
  { name: 'Grundst.bewertung', href: '/grundstuecksbewertung', icon: MapPin },
  { name: 'StKl-Rechner', href: '/steuerklassen-rechner', icon: UsersRound },
  { name: 'Geldwerter Vorteil', href: '/geldwerter-vorteil', icon: Gift },
  { name: 'Steuerstrafrecht', href: '/steuerstrafrecht', icon: Gavel },
  { name: 'ESt-Tabellen', href: '/est-tabellen', icon: Table2 },
  { name: 'Wohnungsbauprämie', href: '/wohnungsbau-praemie', icon: Home },
  { name: 'Meister-BAföG', href: '/meister-bafoeg', icon: GraduationCap },
  { name: 'Zulagen-Rechner', href: '/zulagen-rechner', icon: Coins },
  { name: 'Steuer-Vergleich', href: '/steuer-vergleich', icon: ArrowLeftRight },
  { name: 'Brutto-Netto', href: '/brutto-netto', icon: Calculator },
  { name: 'Kurzarbeitergeld', href: '/kurzarbeitergeld', icon: Clock },
  { name: 'Midijob-Rechner', href: '/midijob-rechner', icon: Briefcase },
  { name: 'Rentenbesteuerung', href: '/rentenbesteuerung', icon: Landmark },
  { name: 'Daten-Export', href: '/daten-export', icon: FolderDown },
  { name: 'Bericht', href: '/bericht', icon: FileDown },
  { name: 'Jahresbericht', href: '/jahresbericht', icon: BarChart3 },
  { name: 'Mein Profil', href: '/profil', icon: User },
  { name: 'Freunde werben', href: '/referral', icon: Users },
  { name: 'Kontakt & Support', href: '/kontakt', icon: LifeBuoy },
  { name: 'Hilfe & Glossar', href: '/hilfe', icon: HelpCircle },
  { name: 'Einstellungen', href: '/einstellungen', icon: Settings },
]

export default function Sidebar() {
  const location = useLocation()

  return (
    <aside className="hidden lg:flex w-64 flex-col border-r border-border/40 bg-muted/30 p-4">
      <nav className="flex flex-col gap-1">
        {navigation.map((item) => {
          const isActive = location.pathname === item.href ||
            (item.href !== '/' && location.pathname.startsWith(item.href))

          return (
            <Link
              key={item.name}
              to={item.href}
              className={cn(
                'flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors',
                isActive
                  ? 'bg-primary text-primary-foreground'
                  : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'
              )}
            >
              <item.icon className="h-4 w-4" />
              {item.name}
            </Link>
          )
        })}
      </nav>

      <div className="mt-auto pt-4 border-t border-border/40">
        <div className="rounded-lg bg-gradient-to-br from-fintutto-blue-800 to-fintutto-blue-600 p-4 text-white">
          <p className="text-sm font-semibold">Bescheidboxer Pro</p>
          <p className="text-xs opacity-80 mt-1">
            Unbegrenzte Analysen & automatische Einsprueche
          </p>
          <Link to="/upgrade" className="mt-3 w-full rounded-md bg-white/20 px-3 py-1.5 text-xs font-medium hover:bg-white/30 transition-colors block text-center">
            Upgrade
          </Link>
        </div>
      </div>
    </aside>
  )
}
