import { useState } from 'react'
import type { Bescheid, Frist, DashboardStats, Einspruch } from '../types/bescheid'

const MOCK_BESCHEIDE: Bescheid[] = [
  {
    id: '1',
    titel: 'Einkommensteuerbescheid 2024',
    typ: 'einkommensteuer',
    steuerjahr: 2024,
    eingangsdatum: '2025-08-15',
    finanzamt: 'Finanzamt Muenchen I',
    aktenzeichen: '123/456/78901',
    status: 'geprueft',
    festgesetzteSteuer: 12450,
    erwarteteSteuer: 10200,
    abweichung: 2250,
    abweichungProzent: 22.06,
    einspruchsfrist: '2025-09-15',
    dokumentUrl: null,
    notizen: 'Werbungskosten nicht vollstaendig anerkannt',
    pruefungsergebnis: {
      abweichungen: [
        {
          id: 'a1',
          position: 'Werbungskosten - Homeoffice',
          beschreibung: 'Homeoffice-Pauschale nur teilweise anerkannt',
          erklaerterBetrag: 1260,
          festgesetzterBetrag: 600,
          differenz: 660,
          kategorie: 'werbungskosten',
          schweregrad: 'kritisch',
        },
        {
          id: 'a2',
          position: 'Werbungskosten - Fortbildung',
          beschreibung: 'Fortbildungskosten nicht anerkannt (Belege fehlen)',
          erklaerterBetrag: 2400,
          festgesetzterBetrag: 0,
          differenz: 2400,
          kategorie: 'werbungskosten',
          schweregrad: 'kritisch',
        },
        {
          id: 'a3',
          position: 'Sonderausgaben - Spenden',
          beschreibung: 'Spendenbescheinigung lag bei, wurde korrekt anerkannt',
          erklaerterBetrag: 500,
          festgesetzterBetrag: 500,
          differenz: 0,
          kategorie: 'sonderausgaben',
          schweregrad: 'info',
        },
      ],
      empfehlung: 'einspruch',
      zusammenfassung: 'Es wurden erhebliche Abweichungen bei den Werbungskosten festgestellt. Ein Einspruch wird empfohlen, da die Homeoffice-Pauschale und Fortbildungskosten nicht korrekt beruecksichtigt wurden.',
      einsparpotenzial: 2250,
    },
    createdAt: '2025-08-15T10:00:00Z',
    updatedAt: '2025-08-16T14:30:00Z',
  },
  {
    id: '2',
    titel: 'Einkommensteuerbescheid 2023',
    typ: 'einkommensteuer',
    steuerjahr: 2023,
    eingangsdatum: '2024-06-20',
    finanzamt: 'Finanzamt Muenchen I',
    aktenzeichen: '123/456/78901',
    status: 'erledigt',
    festgesetzteSteuer: 11800,
    erwarteteSteuer: 11800,
    abweichung: 0,
    abweichungProzent: 0,
    einspruchsfrist: '2024-07-20',
    dokumentUrl: null,
    notizen: null,
    pruefungsergebnis: {
      abweichungen: [],
      empfehlung: 'akzeptieren',
      zusammenfassung: 'Der Bescheid stimmt mit der Steuererklaerung ueberein. Keine Abweichungen festgestellt.',
      einsparpotenzial: 0,
    },
    createdAt: '2024-06-20T10:00:00Z',
    updatedAt: '2024-06-20T10:00:00Z',
  },
  {
    id: '3',
    titel: 'Umsatzsteuerbescheid 2024',
    typ: 'umsatzsteuer',
    steuerjahr: 2024,
    eingangsdatum: '2025-10-01',
    finanzamt: 'Finanzamt Muenchen II',
    aktenzeichen: '987/654/32100',
    status: 'neu',
    festgesetzteSteuer: 8900,
    erwarteteSteuer: null,
    abweichung: null,
    abweichungProzent: null,
    einspruchsfrist: '2025-11-01',
    dokumentUrl: null,
    notizen: null,
    pruefungsergebnis: null,
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-10-01T10:00:00Z',
  },
  {
    id: '4',
    titel: 'Gewerbesteuerbescheid 2024',
    typ: 'gewerbesteuer',
    steuerjahr: 2024,
    eingangsdatum: '2025-09-10',
    finanzamt: 'Finanzamt Muenchen III',
    aktenzeichen: '555/333/11100',
    status: 'in_pruefung',
    festgesetzteSteuer: 4200,
    erwarteteSteuer: 3800,
    abweichung: 400,
    abweichungProzent: 10.53,
    einspruchsfrist: '2025-10-10',
    dokumentUrl: null,
    notizen: 'Hinzurechnungen pruefen',
    pruefungsergebnis: null,
    createdAt: '2025-09-10T10:00:00Z',
    updatedAt: '2025-09-12T10:00:00Z',
  },
  {
    id: '5',
    titel: 'Grundsteuerbescheid 2025',
    typ: 'grundsteuer',
    steuerjahr: 2025,
    eingangsdatum: '2025-11-20',
    finanzamt: 'Finanzamt Muenchen I',
    aktenzeichen: '111/222/33344',
    status: 'einspruch',
    festgesetzteSteuer: 1850,
    erwarteteSteuer: 1200,
    abweichung: 650,
    abweichungProzent: 54.17,
    einspruchsfrist: '2025-12-20',
    dokumentUrl: null,
    notizen: 'Grundstueckswert erscheint zu hoch bewertet',
    pruefungsergebnis: {
      abweichungen: [
        {
          id: 'a4',
          position: 'Grundstueckswert',
          beschreibung: 'Bodenrichtwert scheint fuer die Lage zu hoch angesetzt',
          erklaerterBetrag: 185000,
          festgesetzterBetrag: 245000,
          differenz: 60000,
          kategorie: 'sonstige',
          schweregrad: 'kritisch',
        },
      ],
      empfehlung: 'einspruch',
      zusammenfassung: 'Der angesetzte Grundstueckswert weicht erheblich von der eigenen Berechnung ab. Ein Einspruch wurde bereits eingereicht.',
      einsparpotenzial: 650,
    },
    createdAt: '2025-11-20T10:00:00Z',
    updatedAt: '2025-12-01T10:00:00Z',
  },
]

const MOCK_FRISTEN: Frist[] = [
  {
    id: 'f1',
    bescheidId: '3',
    bescheidTitel: 'Umsatzsteuerbescheid 2024',
    typ: 'einspruch',
    fristdatum: '2025-11-01',
    erledigt: false,
    notiz: 'Bescheid noch nicht geprueft',
  },
  {
    id: 'f2',
    bescheidId: '4',
    bescheidTitel: 'Gewerbesteuerbescheid 2024',
    typ: 'einspruch',
    fristdatum: '2025-10-10',
    erledigt: false,
    notiz: 'Pruefung laeuft',
  },
  {
    id: 'f3',
    bescheidId: '1',
    bescheidTitel: 'Einkommensteuerbescheid 2024',
    typ: 'zahlung',
    fristdatum: '2025-09-30',
    erledigt: false,
    notiz: 'Nachzahlung faellig',
  },
  {
    id: 'f4',
    bescheidId: '5',
    bescheidTitel: 'Grundsteuerbescheid 2025',
    typ: 'nachreichung',
    fristdatum: '2026-01-15',
    erledigt: false,
    notiz: 'Gutachten nachreichen',
  },
]

const MOCK_EINSPRUECHE: Einspruch[] = [
  {
    id: 'e1',
    bescheidId: '5',
    status: 'eingereicht',
    begruendung: 'Der im Bescheid angesetzte Grundstueckswert von 245.000 EUR weicht erheblich vom tatsaechlichen Verkehrswert ab. Gemaess beigefuegtem Gutachten betraegt der Verkehrswert lediglich 185.000 EUR. Wir beantragen eine Korrektur des Grundsteuermessbetrags auf Basis des korrekten Grundstueckswerts.',
    forderung: 650,
    eingereichtAm: '2025-12-01',
    frist: '2025-12-20',
    antwortErhalten: null,
    ergebnis: null,
    createdAt: '2025-12-01T10:00:00Z',
  },
]

export function useMockData() {
  const [bescheide, setBescheide] = useState<Bescheid[]>(MOCK_BESCHEIDE)
  const [fristen] = useState<Frist[]>(MOCK_FRISTEN)
  const [einsprueche] = useState<Einspruch[]>(MOCK_EINSPRUECHE)

  const stats: DashboardStats = {
    bescheideGesamt: bescheide.length,
    offenePruefungen: bescheide.filter(b => b.status === 'neu' || b.status === 'in_pruefung').length,
    einsprueche: bescheide.filter(b => b.status === 'einspruch').length,
    einsparpotenzial: bescheide.reduce((sum, b) => sum + (b.pruefungsergebnis?.einsparpotenzial ?? 0), 0),
    ablaufendeFristen: fristen.filter(f => !f.erledigt).length,
    abweichungenGesamt: bescheide.reduce((sum, b) => sum + (b.pruefungsergebnis?.abweichungen.length ?? 0), 0),
  }

  const addBescheid = (bescheid: Bescheid) => {
    setBescheide(prev => [bescheid, ...prev])
  }

  return {
    bescheide,
    fristen,
    einsprueche,
    stats,
    addBescheid,
  }
}
