-- 025_ai_cfo.sql
-- AI CFO Brain: Financial Events, Predictions, Risk Scores, Actions, Feedback Loop

-- Immutable event store for all financial events (append-only pattern)
CREATE TABLE IF NOT EXISTS public.financial_events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  source TEXT NOT NULL, -- bank_sync, stripe, invoice, manual, api
  event_type TEXT NOT NULL, -- transaction, balance_update, invoice_paid, goal_reached, subscription_change
  amount NUMERIC,
  currency TEXT DEFAULT 'EUR',
  metadata JSONB DEFAULT '{}',
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_financial_events_user_date ON public.financial_events(user_id, occurred_at DESC);
CREATE INDEX idx_financial_events_type ON public.financial_events(event_type);

ALTER TABLE public.financial_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_events" ON public.financial_events FOR ALL USING (user_id = auth.uid());

-- Cashflow predictions (generated by AI pipeline)
CREATE TABLE IF NOT EXISTS public.cashflow_predictions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  horizon_days INT DEFAULT 90,
  forecast JSONB NOT NULL, -- [{day, projected_balance, confidence_low, confidence_high}]
  negative_balance_probability NUMERIC,
  model_version TEXT DEFAULT 'v1_rules',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_cashflow_user ON public.cashflow_predictions(user_id, created_at DESC);
ALTER TABLE public.cashflow_predictions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_predictions" ON public.cashflow_predictions FOR ALL USING (user_id = auth.uid());

-- Risk scores (updated periodically)
CREATE TABLE IF NOT EXISTS public.risk_scores (
  user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  score INT NOT NULL CHECK (score BETWEEN 0 AND 1000),
  default_probability NUMERIC,
  risk_band TEXT CHECK (risk_band IN ('prime', 'standard', 'subprime', 'high_risk')),
  factors JSONB DEFAULT '{}', -- {income_stability: 0.8, expense_discipline: 0.6, ...}
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.risk_scores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_risk" ON public.risk_scores FOR ALL USING (user_id = auth.uid());

-- AI-generated actions/recommendations
CREATE TABLE IF NOT EXISTS public.ai_actions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  action_type TEXT NOT NULL, -- savings_tip, expense_alert, invest_suggestion, risk_warning, refinance_offer
  title TEXT NOT NULL,
  description TEXT,
  confidence NUMERIC,
  potential_savings NUMERIC, -- estimated EUR savings if acted upon
  payload JSONB DEFAULT '{}',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'expired')),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ai_actions_user ON public.ai_actions(user_id, created_at DESC);
ALTER TABLE public.ai_actions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_actions" ON public.ai_actions FOR ALL USING (user_id = auth.uid());

-- Feedback loop for model improvement
CREATE TABLE IF NOT EXISTS public.ai_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  action_id UUID REFERENCES public.ai_actions(id) ON DELETE CASCADE NOT NULL,
  outcome TEXT CHECK (outcome IN ('accepted', 'rejected', 'ignored')),
  financial_delta NUMERIC, -- measured impact in EUR
  user_rating INT CHECK (user_rating BETWEEN 1 AND 5),
  measured_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ai_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_feedback" ON public.ai_feedback
  FOR ALL USING (
    action_id IN (SELECT id FROM public.ai_actions WHERE user_id = auth.uid())
  );

-- AI usage tracking (for metered billing)
CREATE TABLE IF NOT EXISTS public.ai_usage (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  service TEXT NOT NULL, -- finance_coach, biz_cfo, learn_tutor
  tokens_used INT DEFAULT 0,
  cost_cents NUMERIC DEFAULT 0,
  model TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ai_usage_user ON public.ai_usage(user_id, created_at DESC);
ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_ai_usage" ON public.ai_usage FOR ALL USING (user_id = auth.uid());
